### ISSUE TITLE
使用magic-pdf命令，报错OpenBLAS线程限制

### ISSUE THREAD

**Issue by Muyi030** [opendatalab/MinerU#1019]
### Description of the bug | 错误描述

magic-pdf -p ./demo.pdf -o ./output -m auto

报错：
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 10: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 10: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 10: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 4 of 10: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 5 of 10: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 6 of 10: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 7 of 10: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 8 of 10: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 9 of 10: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
Traceback (most recent call last):
  File "/miniconda/envs/MinerU/bin/magic-pdf", line 5, in <module>
    from magic_pdf.tools.cli import cli
  File "/miniconda/envs/MinerU/lib/python3.10/site-packages/magic_pdf/tools/cli.py", line 11, in <module>
    from magic_pdf.tools.common import do_parse, parse_pdf_methods
  File "/miniconda/envs/MinerU/lib/python3.10/site-packages/magic_pdf/tools/common.py", line 9, in <module>
    from magic_pdf.libs.draw_bbox import (draw_layout_bbox, draw_line_sort_bbox,
  File "/miniconda/envs/MinerU/lib/python3.10/site-packages/magic_pdf/libs/draw_bbox.py", line 1, in <module>
    from magic_pdf.data.dataset import PymuDocDataset
  File "/miniconda/envs/MinerU/lib/python3.10/site-packages/magic_pdf/data/dataset.py", line 8, in <module>
    from magic_pdf.data.utils import fitz_doc_to_image
  File "/miniconda/envs/MinerU/lib/python3.10/site-packages/magic_pdf/data/utils.py", line 3, in <module>
    import numpy as np
  File "/miniconda/envs/MinerU/lib/python3.10/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/miniconda/envs/MinerU/lib/python3.10/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/miniconda/envs/MinerU/lib/python3.10/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/miniconda/envs/MinerU/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/miniconda/envs/MinerU/lib/python3.10/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
  File "<frozen importlib._bootstrap>", line 216, in _lock_unlock_module
KeyboardInterrupt

### How to reproduce the bug | 如何复现

magic-pdf -p ./demo.pdf -o ./output -m auto

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.9.x

### Device mode | 设备模式

cpu

**Comment by Muyi030** [comment]
能帮忙看一下什么原因吗？十分感谢！

**Comment by ChangJing89** [comment]
我下载的这个Dockerfile，docker部署Miner,启动进入容器后，执行magic-pdf报上述错误
