### ISSUE TITLE
最新版本报错：ModuleNotFoundError: No module named 'paddleocr.paddleocr'; 'paddleocr' is not a package

### ISSUE THREAD

**Issue by charliedream1** [opendatalab/MinerU#1131]
### Description of the bug | 错误描述

最新版本报错：ModuleNotFoundError: No module named 'paddleocr.paddleocr'; 'paddleocr' is not a package

用cli没有错，用python就出现了

### How to reproduce the bug | 如何复现

使用python调用

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
pip list看一下是否有paddleocr包

**Comment by charliedream1** [comment]
```bash
paddleocr                 2.7.3                    pypi_0    pypi
paddlepaddle              3.0.0b1                  pypi_0    pypi
rapidocr-paddle           1.4.0                    pypi_0    pypi
```
有的，卸了重装也不行

**Comment by myhloli** [comment]
是不是开了多线程

**Comment by charliedream1** [comment]
没有开。你意思是把模型调用嵌到多线程里面吗？没有嵌入。0.9.2版本还没有这个问题的

**Comment by myhloli** [comment]
你的python代码能发一下吗

**Comment by hzspyy** [comment]
我0.10.1版本下，使用multi gpu 也会出现同样的问题

**Comment by charliedream1** [comment]
我试了下单跑命令行和python都没问题。我目前嵌套在sanic里了，sanic好像调用multiprocess了，但我设的worker是1
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/miniconda3/envs/MinerU/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/miniconda3/envs/MinerU/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/miniconda3/envs/MinerU/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/miniconda3/envs/MinerU/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/miniconda3/envs/MinerU/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/miniconda3/envs/MinerU/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
```
咱们代码是不能在multi-process里调吗？之前0.9的版本还没有问题

**Comment by myhloli** [comment]
可能是paddleocr不支持多次初始化，0.10使用了混合ocr，需要在两个不同的地方初始化paddleocr，因此可能和multiprocess发生了一些冲突

**Comment by charliedream1** [comment]
那怎么能修复下。或者使用sanic包装成一个服务，该怎么规避。把worker设为1，他也会自己调multiprocess库

**Comment by myhloli** [comment]
worker能改成0吗

**Comment by charliedream1** [comment]
不行，他好像默认即便是1路，也要调multiprocess

**Comment by fanggaoshang** [comment]
我也有同样的问题，求解决
![局部截取_20241128_191521](https://github.com/user-attachments/assets/955586d2-b64a-45b7-9fd5-731efdcccceb)

**Comment by fanggaoshang** [comment]
> 我也有同样的问题，求解决 ![局部截取_20241128_191521](https://private-user-images.githubusercontent.com/55520523/390759689-955586d2-b64a-45b7-9fd5-731efdcccceb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3OTI4MjksIm5iZiI6MTczMjc5MjUyOSwicGF0aCI6Ii81NTUyMDUyMy8zOTA3NTk2ODktOTU1NTg2ZDItYjY0YS00NWI3LTlmZDUtNzMxZWZkY2NjY2ViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDExMTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NmJjODZhN2RjMGM0ZTM0ZWU5YjJmZDUyOWMxYjFiZTU2OGU0ODNmNzFiMzliN2EyOGRhMGRjODBkMDBlNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.V7LRWjpBPpzTtwkFZGfUUfIdE0HOsAYASqsuCsQJZvs)

我用的GPU版本也是这种报错

**Comment by myhloli** [comment]
@charliedream1 @fanggaoshang 能上传一份最小化的复现代码吗，我这边调试下

**Comment by fanggaoshang** [comment]
> @charliedream1 @fanggaoshang 能上传一份最小化的复现代码吗，我这边调试下

我是在centos7上，根据这个提供的安装步骤并且运行这个server.py文件出现的这个报错，我安装的magic-pdf是magic-pdf[full,old-linux]

![局部截取_20241128_195137](https://github.com/user-attachments/assets/c7ffb023-19f6-4407-8bd8-854f376be07c)

**Comment by fanggaoshang** [comment]
> @charliedream1 @fanggaoshang 能上传一份最小化的复现代码吗，我这边调试下

![局部截取_20241128_195708](https://github.com/user-attachments/assets/360f6b4f-7472-4c2f-a787-936dcb3a7dff)

**Comment by xcvil** [comment]
我在#667里也出现了同样的错误

**Comment by randydl** [comment]
我这边有个临时方案，大家帮忙验证一下，思路是在进程内部import包，比如：
```python
import os
import fitz
import torch
import base64
import litserve as ls
from uuid import uuid4
from fastapi import HTTPException
from filetype import guess_extension
# from magic_pdf.tools.common import do_parse
# from magic_pdf.model.doc_analyze_by_custom_model import ModelSingleton


class MinerUAPI(ls.LitAPI):
    def __init__(self, output_dir='/tmp'):
        self.output_dir = output_dir

    def setup(self, device):
        from magic_pdf.model.doc_analyze_by_custom_model import ModelSingleton
        if device.startswith('cuda'):
            os.environ['CUDA_VISIBLE_DEVICES'] = device.split(':')[-1]
            if torch.cuda.device_count() > 1:
                raise RuntimeError("Remove any CUDA actions before setting 'CUDA_VISIBLE_DEVICES'.")

        model_manager = ModelSingleton()
        model_manager.get_model(True, False)
        model_manager.get_model(False, False)
        print(f'Model initialization complete on {device}!')

    def decode_request(self, request):
        file = request['file']
        file = self.to_pdf(file)
        opts = request.get('kwargs', {})
        opts.setdefault('debug_able', False)
        opts.setdefault('parse_method', 'auto')
        return file, opts

    def predict(self, inputs):
        from magic_pdf.tools.common import do_parse
        try:
            do_parse(self.output_dir, pdf_name := str(uuid4()), inputs[0], [], **inputs[1])
            return pdf_name
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))
        finally:
            self.clean_memory()

    def encode_response(self, response):
        return {'output_dir': response}

    def clean_memory(self):
        import gc
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
            torch.cuda.ipc_collect()
        gc.collect()

    def to_pdf(self, file_base64):
        try:
            file_bytes = base64.b64decode(file_base64)
            file_ext = guess_extension(file_bytes)
            with fitz.open(stream=file_bytes, filetype=file_ext) as f:
                if f.is_pdf: return f.tobytes()
                return f.convert_to_pdf()
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))
```

我会尝试一些更好的思路，验证好的话我提出来PR

**Comment by myhloli** [comment]
> 我这边有个临时方案，大家帮忙验证一下，思路是在进程内部import包，比如：
> 
> ```python
> import os
> import fitz
> import torch
> import base64
> import litserve as ls
> from uuid import uuid4
> from fastapi import HTTPException
> from filetype import guess_extension
> # from magic_pdf.tools.common import do_parse
> # from magic_pdf.model.doc_analyze_by_custom_model import ModelSingleton
> 
> 
> class MinerUAPI(ls.LitAPI):
>     def __init__(self, output_dir='/tmp'):
>         self.output_dir = output_dir
> 
>     def setup(self, device):
>         from magic_pdf.model.doc_analyze_by_custom_model import ModelSingleton
>         if device.startswith('cuda'):
>             os.environ['CUDA_VISIBLE_DEVICES'] = device.split(':')[-1]
>             if torch.cuda.device_count() > 1:
>                 raise RuntimeError("Remove any CUDA actions before setting 'CUDA_VISIBLE_DEVICES'.")
> 
>         model_manager = ModelSingleton()
>         model_manager.get_model(True, False)
>         model_manager.get_model(False, False)
>         print(f'Model initialization complete on {device}!')
> 
>     def decode_request(self, request):
>         file = request['file']
>         file = self.to_pdf(file)
>         opts = request.get('kwargs', {})
>         opts.setdefault('debug_able', False)
>         opts.setdefault('parse_method', 'auto')
>         return file, opts
> 
>     def predict(self, inputs):
>         from magic_pdf.tools.common import do_parse
>         try:
>             do_parse(self.output_dir, pdf_name := str(uuid4()), inputs[0], [], **inputs[1])
>             return pdf_name
>         except Exception as e:
>             raise HTTPException(status_code=500, detail=str(e))
>         finally:
>             self.clean_memory()
> 
>     def encode_response(self, response):
>         return {'output_dir': response}
> 
>     def clean_memory(self):
>         import gc
>         if torch.cuda.is_available():
>             torch.cuda.empty_cache()
>             torch.cuda.ipc_collect()
>         gc.collect()
> 
>     def to_pdf(self, file_base64):
>         try:
>             file_bytes = base64.b64decode(file_base64)
>             file_ext = guess_extension(file_bytes)
>             with fitz.open(stream=file_bytes, filetype=file_ext) as f:
>                 if f.is_pdf: return f.tobytes()
>                 return f.convert_to_pdf()
>         except Exception as e:
>             raise HTTPException(status_code=500, detail=str(e))
> ```
> 
> 我会尝试一些更好的思路，验证好的话我提出来PR

我这边刚修复了，今天可以发release出来
https://github.com/opendatalab/MinerU/pull/1141/files

**Comment by charliedream1** [comment]
刚看到，还没来及发调试代码，楼主就解决了，太神速了，👍

**Comment by charliedream1** [comment]
另外，能支持batch推理吗？

**Comment by myhloli** [comment]
> 另外，能支持batch推理吗？

未来会更新batch的功能，需要24G以上显存，速度可以提升几倍

**Comment by charliedream1** [comment]
👍
另外，建议增加一个图片扭曲修正的模型，发现拍照的有些扭曲的图片，里面表格有时候识别不到。然后有些表格，降低像素后就识别不出来了，但人眼看着很清晰，且和原始的清晰度效果差不多

**Comment by myhloli** [comment]
> 👍 另外，建议增加一个图片扭曲修正的模型，发现拍照的有些扭曲的图片，里面表格有时候识别不到。然后有些表格，降低像素后就识别不出来了，但人眼看着很清晰，且和原始的清晰度效果差不多

有计划，这个暂排到明年初了

**Comment by charliedream1** [comment]
期待

**Comment by myhloli** [comment]
fixed in 0.10.3

**Comment by charliedream1** [comment]
用最新版本，还是报错
```bash
File "<string>", line 1, in <module>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 3
               │     └ 46
               └ <function _main at 0x7f3629577eb0>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 3
           │    └ <function BaseProcess._bootstrap at 0x7f3629756680>
           └ <SpawnProcess name='Sanic-Server-0-0' parent=2254192 started daemon>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f3629755cf0>
    └ <SpawnProcess name='Sanic-Server-0-0' parent=2254192 started daemon>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'protocol': <class 'sanic.server.protocols.http_protocol.HttpProtocol'>, 'host': N
one, 'port': None, 'version': <HTTP.VERSIO...
    │    │        │    │        └ <SpawnProcess name='Sanic-Server-0-0' parent=2254192 started daemon>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='Sanic-Server-0-0' parent=2254192 started daemon>
    │    └ <function worker_serve at 0x7f36234ce560>
    └ <SpawnProcess name='Sanic-Server-0-0' parent=2254192 started daemon>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/sanic/worker/serve.py", line 121, in worker_serve
    return _serve_http_1(
           └ <function _serve_http_1 at 0x7f36235a35b0>
File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/sanic/server/runners.py", line 183, in _run_server
_forever
    loop.run_forever()
    │    └ <cyfunction Loop.run_forever at 0x7f3624083920>
    └ <uvloop.Loop running=True closed=False debug=False>
  File "connection_task", line 15, in connection_task
    from asyncio import CancelledError
                        └ <class 'asyncio.exceptions.CancelledError'>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/sanic/http/http1.py", line 123, in http1
    await self.protocol.request_handler(self.request)
          │    │                        │    └ <member 'request' of 'Http' objects>
          │    │                        └ <sanic.http.http1.Http object at 0x7f3623dbe5a0>
          │    └ <member 'protocol' of 'Http' objects>
          └ <sanic.http.http1.Http object at 0x7f3623dbe5a0>
  File "handle_request", line 102, in handle_request
    if TYPE_CHECKING:
       └ False
pipe.pipe_parse()
    │    └ <function UNIPipe.pipe_parse at 0x7f3520823be0>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f352083f5e0>

  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 49, in pipe_parse
    self.pdf_mid_data = parse_ocr_pdf(self.pdf_bytes, self.model_list, self.image_writer,
    │    │              │             │    │          │    │           │    └ <magic_pdf.rw.DiskReaderWriter.DiskReaderWri
ter object at 0x7f352083fbb0>
    │    │              │             │    │          │    │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f352
083f5e0>
    │    │              │             │    │          │    └ [{'layout_dets': [{'category_id': 1, 'poly': [348.79034423828
125, 427.2013854980469, 1198.7896728515625, 427.2013854980469, 1...
    │    │              │             │    │          └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f352083f5e0>
    │    │              │             │    └ b'%PDF-1.7\n%\xc2\xb5\xc2\xb6\n\n1 0 obj\n<</Type/Catalog/Pages 2 0 R>>\nendo
bj\n\n2 0 obj\n<</Type/Pages/Count 1/Kids[6 0 R]...
    │    │              │             └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f352083f5e0>
    │    │              └ <function parse_ocr_pdf at 0x7f3520823910>
    │    └ None
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f352083f5e0>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/user_api.py", line 50, in parse_ocr_pdf
    pdf_info_dict = parse_pdf_by_ocr(
                    └ <function parse_pdf_by_ocr at 0x7f356481b130>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pdf_parse_by_ocr.py", line 15, in parse_
pdf_by_ocr
return pdf_parse_union(dataset,
           │               └ <magic_pdf.data.dataset.PymuDocDataset object at 0x7f351c61f850>
           └ <function pdf_parse_union at 0x7f35208236d0>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core_v2.py", line 808, i
n pdf_parse_union
    page_info = parse_page_core(
                └ <function parse_page_core at 0x7f3520823640>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core_v2.py", line 718, i
n parse_page_core
    spans = ocr_cut_image_and_table(
            └ <function ocr_cut_image_and_table at 0x7f35208223b0>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pre_proc/cut_image.py", line 22, in ocr_
cut_image_and_table
    span['image_path'] = cut_image(span['bbox'], page_id, page, return_path=return_path('tables'),
    │                    │         │             │        │                 └ <function ocr_cut_image_and_table.<locals>.r
eturn_path at 0x7f351a8a0280>
    │                    │         │             │        └ <magic_pdf.data.dataset.Doc object at 0x7f351ed291e0>
    │                    │         │             └ 0
    │                    │         └ {'bbox': [123, 426, 496, 612], 'score': 0.9072770476341248, 'html': '<html><body><tab
le><tr><td>序 号</td><td>品牌</td><td>物资名 称<...
    │                    └ <function cut_image at 0x7f35648460e0>
    └ {'bbox': [123, 426, 496, 612], 'score': 0.9072770476341248, 'html': '<html><body><table><tr><td>序 号</td><td>品牌</
td><td>物资名 称<...
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/libs/pdf_image_tools.py", line 33, in cu
t_image
imageWriter.write(img_hash256_path, byte_data)
    │           │     │                 └ b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00`\x00`\x00\x00\xff\xdb\x00C\x0
0\x02\x01\x01\x01\x01\x01\x02\x01\x01\x01\x02...
    │           │     └ '386a36b9e49da2cdda4a6aeb28c5d06e546d5a80ce3dfa9e96d7d28dec975c7f.jpg'
    │           └ <function DiskReaderWriter.write at 0x7f3520830ca0>
    └ <magic_pdf.rw.DiskReaderWriter.DiskReaderWriter object at 0x7f352083fbb0>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/rw/DiskReaderWriter.py", line 32, in wri
te
    abspath = os.path.join(self.path, path)
              │  │    │    │    │     └ b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00`\x00`\x00\x00\xff\xdb\x00C\x00\
x02\x01\x01\x01\x01\x01\x02\x01\x01\x01\x02...
              │  │    │    │    └ '/home/dependent_server/pdf
_2_md_serve/461c1f17-32a7-4912-ae68-0...
              │  │    │    └ <magic_pdf.rw.DiskReaderWriter.DiskReaderWriter object at 0x7f352083fbb0>
              │  │    └ <function join at 0x7f36298b2f80>
              │  └ <module 'posixpath' from '/home/miniconda3/envs/MinerU/lib/python3.10/posixpath.py'>
              └ <module 'os' from '/home/miniconda3/envs/MinerU/lib/python3.10/os.py'>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
    │           │                        │   └ (b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00`\x00`\x00\x00\xff\xdb\x
00C\x00\x02\x01\x01\x01\x01\x01\x02\x01\x01\x01\x0...
    │           │                        └ '/home/dependent_s
erver/pdf_2_md_serve/461c1f17-32a7-4912-ae68-0...
    │           └ <function _check_arg_types at 0x7f36298b2dd0>
    └ <module 'genericpath' from '/home/miniconda3/envs/MinerU/lib/python3.10/genericpath.py'>
  File "/home/miniconda3/envs/MinerU/lib/python3.10/genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None

TypeError: Can't mix strings and bytes in path components
```

**Comment by myhloli** [comment]
@charliedream1 文件读写类重构了，你需要参考demo中的示例更新一下自己的代码

**Comment by charliedream1** [comment]
好的
