### ISSUE TITLE
python document ssl fail

### ISSUE THREAD

**Issue by 1caiji23** [opendatalab/MinerU#1172]
### Description of the bug | 错误描述

is it unuseful for chinese public,i try vpn but noting change,is someone can help?(rapid start model)

### How to reproduce the bug | 如何复现

maybe。。。

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
Please describe in detail what kind of problem you encountered and under what circumstances it occurred.

**Comment by 1caiji23** [comment]
> Please describe in detail what kind of problem you encountered and under what circumstances it occurred.

Model file initial download, my region has network restrictions, can not link to hug face, vpn also does not give force, there are other ways to download models?

**Comment by myhloli** [comment]
Try this way


https://github.com/opendatalab/MinerU/blob/master/docs/how_to_download_models_zh_cn.md

**Comment by 1caiji23** [comment]
> Try this way
> 
> https://github.com/opendatalab/MinerU/blob/master/docs/how_to_download_models_zh_cn.md

ok，thank you

**Comment by 1caiji23** [comment]
> 试试这个方式
> 
> https://github.com/opendatalab/MinerU/blob/master/docs/how_to_download_models_zh_cn.md
 magic-pdf -v
Traceback (most recent call last):
  File "D:\anaconda\envs\MinerU\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda\envs\MinerU\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\envs\MinerU\Scripts\magic-pdf.exe\__main__.py", line 4, in <module>
    from magic_pdf.tools.cli import cli
  File "D:\anaconda\envs\MinerU\lib\site-packages\magic_pdf\tools\cli.py", line 10, in <module>
    from magic_pdf.tools.common import do_parse, parse_pdf_methods
  File "D:\anaconda\envs\MinerU\lib\site-packages\magic_pdf\tools\common.py", line 14, in <module>
    from magic_pdf.pipe.OCRPipe import OCRPipe
  File "D:\anaconda\envs\MinerU\lib\site-packages\magic_pdf\pipe\OCRPipe.py", line 5, in <module>
    from magic_pdf.model.doc_analyze_by_custom_model import doc_analyze
  File "D:\anaconda\envs\MinerU\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line 7, in <module>
    from magic_pdf.libs.clean_memory import clean_memory
  File "D:\anaconda\envs\MinerU\lib\site-packages\magic_pdf\libs\clean_memory.py", line 2, in <module>
    import torch
  File "D:\anaconda\envs\MinerU\lib\site-packages\torch\__init__.py", line 132, in <module>
    raise err
OSError: [WinError 1114] 动态链接库(DLL)初始化例程失败。 Error loading "D:\anaconda\envs\MinerU\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
(MinerU) PS C:\Users\wuhuu> magic-pdf
Traceback (most recent call last):
  File "D:\anaconda\envs\MinerU\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda\envs\MinerU\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\envs\MinerU\Scripts\magic-pdf.exe\__main__.py", line 4, in <module>
    from magic_pdf.tools.cli import cli
  File "D:\anaconda\envs\MinerU\lib\site-packages\magic_pdf\tools\cli.py", line 10, in <module>
    from magic_pdf.tools.common import do_parse, parse_pdf_methods
  File "D:\anaconda\envs\MinerU\lib\site-packages\magic_pdf\tools\common.py", line 14, in <module>
    from magic_pdf.pipe.OCRPipe import OCRPipe
  File "D:\anaconda\envs\MinerU\lib\site-packages\magic_pdf\pipe\OCRPipe.py", line 5, in <module>
    from magic_pdf.model.doc_analyze_by_custom_model import doc_analyze
  File "D:\anaconda\envs\MinerU\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line 7, in <module>
    from magic_pdf.libs.clean_memory import clean_memory
  File "D:\anaconda\envs\MinerU\lib\site-packages\magic_pdf\libs\clean_memory.py", line 2, in <module>
    import torch
  File "D:\anaconda\envs\MinerU\lib\site-packages\torch\__init__.py", line 132, in <module>
    raise err
OSError: [WinError 1114] 动态链接库(DLL)初始化例程失败。 Error loading "D:\anaconda\envs\MinerU\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.                                                                                                                                 
is there any mistake？

**Comment by myhloli** [comment]
torch没装好，可能和安装时网络不稳定有关，卸了torch重装下

**Comment by 1caiji23** [comment]
> torch没装好，可能和安装时网络不稳定有关，卸了torch重装下

thank you,it is useful!!!
!
![屏幕截图 2024-12-05 093647](https://github.com/user-attachments/assets/17bec755-4497-4ac6-9430-eab9f0bf8868)
