### ISSUE TITLE
Bug on running the UNIPipe on 0.10.5

### ISSUE THREAD

**Issue by JianyuZhan** [opendatalab/MinerU#1180]
### Description of the bug | 错误描述

I followed the install instructions:
`conda create -n MinerU python=3.10
conda activate MinerU
pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com`

and I encoutered a bug when running code using `UNIPipe`:

`  File "/home/ubuntu/MinerU/magic_pdf/pipe/UNIPipe.py", line 8, in <module>
    from magic_pdf.model.doc_analyze_by_custom_model import doc_analyze
  File "/home/ubuntu/MinerU/magic_pdf/model/doc_analyze_by_custom_model.py", line 7, in <module>
    from magic_pdf.libs.clean_memory import clean_memory
  File "/home/ubuntu/MinerU/magic_pdf/libs/clean_memory.py", line 2, in <module>
    import torch
  File "/home/ubuntu/miniconda3/envs/CondaMinerU/lib/python3.10/site-packages/torch/__init__.py", line 239, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/ubuntu/miniconda3/envs/CondaMinerU/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkAddData_12_1, version libnvJitLink.so.12`

I am using `tag: magic_pdf-0.10.5-released`, and running on a Ubuntu without GPU. 

### How to reproduce the bug | 如何复现

Follow the conda install instruction, using the latest master code(tag: magic_pdf-0.10.5-released) , and run the below script on any pdf

```
import os
import sys

from magic_pdf.data.data_reader_writer import FileBasedDataWriter, FileBasedDataReader
from magic_pdf.config.make_content_config import DropMode, MakeMode
from magic_pdf.pipe.UNIPipe import UNIPipe

## 从命令行读取 PDF 文件名
if len(sys.argv) < 2:
    print("请提供 PDF 文件的路径作为命令行参数。")
    sys.exit(1)

pdf_file_name = sys.argv[1]

## 准备环境
local_image_dir, local_md_dir = "output/images", "output"
os.makedirs(local_image_dir, exist_ok=True)

image_writer = FileBasedDataWriter(local_image_dir)
md_writer = FileBasedDataWriter(local_md_dir)
image_dir = os.path.basename(local_image_dir)

reader1 = FileBasedDataReader("")
pdf_bytes = reader1.read(pdf_file_name)  

model_list = []
pipe = UNIPipe(pdf_bytes, model_list, image_writer)

pipe.pipe_classify()
pipe.pipe_analyze()
pipe.pipe_parse()

pdf_info = pipe.pdf_mid_data["pdf_info"]

md_content = pipe.pipe_mk_markdown(
    image_dir, drop_mode=DropMode.NONE, md_make_mode=MakeMode.MM_MD
)

if isinstance(md_content, list):
    md_writer.write_string(f"{pdf_file_name}.md", "\n".join(md_content))
else:
    md_writer.write_string(f"{pdf_file_name}.md", md_content)
```

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
Please upload some information to help us determine what issue has occurred.
```
cat ~/magic-pdf.json
```
and
```
pip list
```

**Comment by JianyuZhan** [comment]
**magic-pdf.json**:

```
$ cat ~/magic-pdf.json
{
    "bucket_info": {
        "bucket-name-1": [
            "ak",
            "sk",
            "endpoint"
        ],
        "bucket-name-2": [
            "ak",
            "sk",
            "endpoint"
        ]
    },
    "models-dir": "/home/ubuntu/.cache/huggingface/hub/models--opendatalab--PDF-Extract-Kit-1.0/snapshots/38e484355b9acf5654030286bf72490e27842a3c/models",
    "layoutreader-model-dir": "/home/ubuntu/.cache/huggingface/hub/models--hantian--layoutreader/snapshots/641226775a0878b1014a96ad01b9642915136853",
    "device-mode": "cpu",
    "layout-config": {
        "model": "layoutlmv3"
    },
    "formula-config": {
        "mfd_model": "yolo_v8_mfd",
        "mfr_model": "unimernet_small",
        "enable": true
    },
    "table-config": {
        "model": "rapid_table",
        "enable": true,
        "max_time": 400
    },
    "config_version": "1.0.0"
}
```
**pip list**
```
$ pip list
Package                  Version
------------------------ --------------------
absl-py                  2.1.0
accelerate               1.1.1
aiohappyeyeballs         2.4.4
aiohttp                  3.11.9
aiosignal                1.3.1
albucore                 0.0.20
albumentations           1.4.21
annotated-types          0.7.0
antlr4-python3-runtime   4.9.3
anyio                    4.6.2.post1
astor                    0.8.1
async-timeout            5.0.1
attrdict                 2.0.1
attrs                    24.2.0
babel                    2.16.0
bce-python-sdk           0.9.23
beautifulsoup4           4.12.3
black                    24.10.0
blinker                  1.9.0
boto3                    1.35.73
botocore                 1.35.73
braceexpand              0.1.7
Brotli                   1.1.0
cachetools               5.5.0
certifi                  2024.8.30
charset-normalizer       3.4.0
click                    8.1.7
cloudpickle              3.1.0
coloredlogs              15.0.1
colorlog                 6.9.0
contourpy                1.3.1
cssselect                1.2.0
cssutils                 2.11.1
cycler                   0.12.1
Cython                   3.0.11
datasets                 3.1.0
decorator                5.1.1
detectron2               0.6
dill                     0.3.8
doclayout_yolo           0.0.2
einops                   0.8.0
et_xmlfile               2.0.0
eva-decord               0.6.1
eval_type_backport       0.2.0
evaluate                 0.4.3
exceptiongroup           1.2.2
fairscale                0.4.13
fast-langdetect          0.2.0
fasttext-wheel           0.9.2
filelock                 3.16.1
fire                     0.7.0
Flask                    3.1.0
flask-babel              4.0.0
flatbuffers              24.3.25
fonttools                4.55.1
frozenlist               1.5.0
fsspec                   2024.9.0
ftfy                     6.3.1
future                   1.0.0
fvcore                   0.1.5.post20221221
grpcio                   1.68.1
h11                      0.14.0
httpcore                 1.0.7
httpx                    0.28.0
huggingface-hub          0.26.3
humanfriendly            10.0
hydra-core               1.3.2
idna                     3.10
imageio                  2.36.1
imgaug                   0.4.0
iopath                   0.1.9
itsdangerous             2.2.0
Jinja2                   3.1.4
jmespath                 1.0.1
joblib                   1.4.2
kiwisolver               1.4.7
langdetect               1.0.9
lazy_loader              0.4
lmdb                     1.5.1
loguru                   0.7.2
lxml                     5.3.0
magic-pdf                0.10.5
Markdown                 3.7
MarkupSafe               3.0.2
matplotlib               3.9.3
more-itertools           10.5.0
mpmath                   1.3.0
multidict                6.1.0
multiprocess             0.70.16
mypy-extensions          1.0.0
networkx                 3.4.2
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.85
nvidia-nvtx-cu12         12.1.105
omegaconf                2.3.0
onnxruntime              1.20.1
opencv-contrib-python    4.6.0.66
opencv-python            4.6.0.66
opencv-python-headless   4.10.0.84
openpyxl                 3.1.5
opt-einsum               3.3.0
packaging                24.2
paddleocr                2.7.3
paddlepaddle             3.0.0b1
pandas                   2.2.3
pathspec                 0.12.1
pdf2docx                 0.5.8
pillow                   11.0.0
pip                      24.2
platformdirs             4.3.6
portalocker              3.0.0
premailer                3.10.0
propcache                0.2.1
protobuf                 5.29.0
psutil                   6.1.0
py-cpuinfo               9.0.0
pyarrow                  18.1.0
pybind11                 2.13.6
pyclipper                1.3.0.post6
pycocotools              2.0.8
pycryptodome             3.21.0
pydantic                 2.7.4
pydantic_core            2.18.4
PyMuPDF                  1.24.14
pyparsing                3.2.0
python-dateutil          2.9.0.post0
python-docx              1.1.2
pytz                     2024.2
PyYAML                   6.0.2
rapid-table              0.3.0
RapidFuzz                3.10.1
rapidocr-paddle          1.4.0
rarfile                  4.2
regex                    2024.11.6
requests                 2.32.3
robust-downloader        0.0.2
s3transfer               0.10.4
safetensors              0.4.5
scikit-image             0.24.0
scikit-learn             1.5.2
scipy                    1.14.1
seaborn                  0.13.2
setuptools               75.1.0
shapely                  2.0.6
simsimd                  6.2.1
six                      1.16.0
sniffio                  1.3.1
soupsieve                2.6
stringzilla              3.11.0
struct-eqtable           0.3.2
sympy                    1.13.3
tabulate                 0.9.0
tensorboard              2.18.0
tensorboard-data-server  0.7.2
termcolor                2.5.0
thop                     0.1.1.post2209072238
threadpoolctl            3.5.0
tifffile                 2024.9.20
timm                     0.9.16
tokenizers               0.19.1
tomli                    2.2.1
torch                    2.3.1
torchtext                0.18.0
torchvision              0.18.1
tqdm                     4.67.1
transformers             4.42.4
triton                   2.3.1
typing_extensions        4.12.2
tzdata                   2024.2
ultralytics              8.3.40
ultralytics-thop         2.0.12
unimernet                0.2.1
urllib3                  2.2.3
visualdl                 2.5.3
Wand                     0.6.13
wcwidth                  0.2.13
webdataset               0.2.100
Werkzeug                 3.1.3
wheel                    0.44.0
xxhash                   3.5.0
yacs                     0.1.8
yarl                     1.18.3

```

**Comment by myhloli** [comment]
You can try to reproduce the issue in the current environment by using `import torch`. If you can reproduce it, it likely indicates that the PyTorch environment is not installed correctly.

**Comment by JianyuZhan** [comment]
Yep, in the conda venv, I tried it and had same error:

```
$ python
Python 3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/miniconda3/envs/conMinerU/lib/python3.10/site-packages/torch/__init__.py", line 239, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/ubuntu/miniconda3/envs/conMinerU/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkAddData_12_1, version libnvJitLink.so.12
```

I tried to recreate a new conda environment, but still to no avail... 

Appraently, the torch tries to load a nv* function, but my instance has no GPU. I doubt`pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com` installed wrong version.

**Comment by myhloli** [comment]
You can create a new conda environment and install torch using `pip install torch==2.3.1`, then try using `import torch`.

**Comment by JianyuZhan** [comment]
@myhloli  same, using a new conda env and do only `pip install torch==2.3.1` got the same error.

**Comment by myhloli** [comment]
Please check if the system's environment variables point to the CUDA directory installed on the system. If there are such configuration items, please clear these CUDA-related environment variables and try again.

**Comment by JianyuZhan** [comment]
I check the CUDA related variables and found nothing. But I used a new instance and tried reinstall, it works ok now!
