### ISSUE TITLE
pip安装成功，但是magic-pdf --version错误

### ISSUE THREAD

**Issue by qushencn** [opendatalab/MinerU#1182]
### Description of the bug | 错误描述

(MinerU) C:\Windows\System32>magic-pdf --version
Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\envs\MinerU\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ASUS\anaconda3\envs\MinerU\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ASUS\anaconda3\envs\MinerU\Scripts\magic-pdf.exe\__main__.py", line 4, in <module>
    from magic_pdf.tools.cli import cli
  File "C:\Users\ASUS\anaconda3\envs\MinerU\lib\site-packages\magic_pdf\tools\cli.py", line 10, in <module>
    from magic_pdf.tools.common import do_parse, parse_pdf_methods
  File "C:\Users\ASUS\anaconda3\envs\MinerU\lib\site-packages\magic_pdf\tools\common.py", line 14, in <module>
    from magic_pdf.pipe.OCRPipe import OCRPipe
  File "C:\Users\ASUS\anaconda3\envs\MinerU\lib\site-packages\magic_pdf\pipe\OCRPipe.py", line 7, in <module>
    from magic_pdf.user_api import parse_ocr_pdf
  File "C:\Users\ASUS\anaconda3\envs\MinerU\lib\site-packages\magic_pdf\user_api.py", line 15, in <module>
    from magic_pdf.pdf_parse_by_ocr import parse_pdf_by_ocr
  File "C:\Users\ASUS\anaconda3\envs\MinerU\lib\site-packages\magic_pdf\pdf_parse_by_ocr.py", line 3, in <module>
    from magic_pdf.pdf_parse_union_core_v2 import pdf_parse_union
  File "C:\Users\ASUS\anaconda3\envs\MinerU\lib\site-packages\magic_pdf\pdf_parse_union_core_v2.py", line 34, in <module>
    from magic_pdf.model.sub_modules.model_init import AtomModelSingleton
  File "C:\Users\ASUS\anaconda3\envs\MinerU\lib\site-packages\magic_pdf\model\sub_modules\model_init.py", line 10, in <module>
    from magic_pdf.model.sub_modules.mfr.unimernet.Unimernet import UnimernetModel
  File "C:\Users\ASUS\anaconda3\envs\MinerU\lib\site-packages\magic_pdf\model\sub_modules\mfr\unimernet\Unimernet.py", line 9, in <module>
    from unimernet.common.config import Config
  File "C:\Users\ASUS\anaconda3\envs\MinerU\lib\site-packages\unimernet\__init__.py", line 16, in <module>
    from unimernet.models import *
  File "C:\Users\ASUS\anaconda3\envs\MinerU\lib\site-packages\unimernet\models\__init__.py", line 16, in <module>
    from unimernet.models.unimernet.unimernet import UniMERModel
  File "C:\Users\ASUS\anaconda3\envs\MinerU\lib\site-packages\unimernet\models\unimernet\unimernet.py", line 4, in <module>
    from unimernet.models.blip2_models.blip2 import Blip2Base
  File "C:\Users\ASUS\anaconda3\envs\MinerU\lib\site-packages\unimernet\models\blip2_models\blip2.py", line 26, in <module>
    from unimernet.models.clip_vit import create_clip_vit_L
  File "C:\Users\ASUS\anaconda3\envs\MinerU\lib\site-packages\unimernet\models\clip_vit.py", line 10, in <module>
    from fairscale.nn.checkpoint.checkpoint_activations import checkpoint_wrapper
ModuleNotFoundError: No module named 'fairscale'

### How to reproduce the bug | 如何复现

![Uploading image.png…]()

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/blob/master/docs/FAQ_zh_cn.md#5%E9%81%87%E5%88%B0%E6%8A%A5%E9%94%99-modulenotfounderror--nomodulenamed-fairscale
