### ISSUE TITLE
magic-pdf --version报错

### ISSUE THREAD

**Issue by liyuhan355** [opendatalab/MinerU#1184]
### Description of the bug | 错误描述

Traceback (most recent call last):
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1567, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/site-packages/transformers/models/mbart/modeling_mbart.py", line 53, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "/home/nlppublic/.local/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/home/nlppublic/.local/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nvme01/anaconda3/envs/mineru/bin/magic-pdf", line 5, in <module>
    from magic_pdf.tools.cli import cli
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/tools/cli.py", line 10, in <module>
    from magic_pdf.tools.common import do_parse, parse_pdf_methods
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/tools/common.py", line 14, in <module>
    from magic_pdf.pipe.OCRPipe import OCRPipe
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/pipe/OCRPipe.py", line 7, in <module>
    from magic_pdf.user_api import parse_ocr_pdf
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/user_api.py", line 15, in <module>
    from magic_pdf.pdf_parse_by_ocr import parse_pdf_by_ocr
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/pdf_parse_by_ocr.py", line 3, in <module>
    from magic_pdf.pdf_parse_union_core_v2 import pdf_parse_union
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core_v2.py", line 34, in <module>
    from magic_pdf.model.sub_modules.model_init import AtomModelSingleton
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/model/sub_modules/model_init.py", line 10, in <module>
    from magic_pdf.model.sub_modules.mfr.unimernet.Unimernet import UnimernetModel
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/model/sub_modules/mfr/unimernet/Unimernet.py", line 9, in <module>
    from unimernet.common.config import Config
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/site-packages/unimernet/__init__.py", line 16, in <module>
    from unimernet.models import *
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/site-packages/unimernet/models/__init__.py", line 16, in <module>
    from unimernet.models.unimernet.unimernet import UniMERModel
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/site-packages/unimernet/models/unimernet/unimernet.py", line 5, in <module>
    from unimernet.models.unimernet.encoder_decoder import DonutEncoderDecoder, DonutTokenizer
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/site-packages/unimernet/models/unimernet/encoder_decoder.py", line 13, in <module>
    from transformers import AutoModel, VisionEncoderDecoderModel, AutoImageProcessor, MBartForCausalLM
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1558, in __getattr__
    value = getattr(module, name)
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1557, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/nvme01/anaconda3/envs/mineru/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1569, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.mbart.modeling_mbart because of the following error (look up to see its traceback):
libcudart.so.11.0: cannot open shared object file: No such file or directory

### How to reproduce the bug | 如何复现

。。。

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
我们没有测试过项目在flash_attn_2 上的兼容性，可以创建一个新环境先按官方教程安装测试下是否可用吗
