### ISSUE TITLE
多线程下paddle报错

### ISSUE THREAD

**Issue by ElsaReedz** [opendatalab/MinerU#1186]
### Description of the bug | 错误描述

使用celery进行任务管理，在一个task中调用MinerU进行文档解析，并在worker初始化时，初始化MinerU相关模型。线程池策略为-P threads

同时创建多个task，处理多份文档。

在前面一两页显示正常并行处理

```bash
2024-12-04 06:00:17.282 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:184 - layout detection time: 1.81
2024-12-04 06:00:19.666 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:230 - ocr time: 2.34
2024-12-04 06:00:19.666 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:doc_analyze:168 - -----page_id : 0, page total time: 4.19-----
2024-12-04 06:00:20.443 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:184 - layout detection time: 0.78
2024-12-04 06:00:20.521 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:184 - layout detection time: 1.48
2024-12-04 06:00:20.583 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:184 - layout detection time: 1.17
2024-12-04 06:00:20.714 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:184 - layout detection time: 0.54
2024-12-04 06:00:20.726 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:230 - ocr time: 0.28
2024-12-04 06:00:20.726 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:doc_analyze:168 - -----page_id : 1, page total time: 1.06-----
2024-12-04 06:00:20.993 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:230 - ocr time: 0.47
2024-12-04 06:00:20.993 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:doc_analyze:168 - -----page_id : 0, page total time: 1.95-----
2024-12-04 06:00:21.247 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:230 - ocr time: 0.66
2024-12-04 06:00:21.248 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:doc_analyze:168 - -----page_id : 0, page total time: 1.83-----
2024-12-04 06:00:21.327 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:230 - ocr time: 0.61
2024-12-04 06:00:21.327 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:doc_analyze:168 - -----page_id : 0, page total time: 1.16-----
2024-12-04 06:00:21.949 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:184 - layout detection time: 0.62
2024-12-04 06:00:21.964 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:184 - layout detection time: 0.97
2024-12-04 06:00:22.013 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:184 - layout detection time: 0.77
2024-12-04 06:00:22.056 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:184 - layout detection time: 1.33
2024-12-04 06:00:22.293 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:230 - ocr time: 0.34
2024-12-04 06:00:22.293 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:doc_analyze:168 - -----page_id : 1, page total time: 0.97-----
2024-12-04 06:00:22.320 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:230 - ocr time: 0.28
2024-12-04 06:00:22.320 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:doc_analyze:168 - -----page_id : 1, page total time: 1.07-----
2024-12-04 06:00:22.478 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:230 - ocr time: 0.51
2024-12-04 06:00:22.478 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:doc_analyze:168 - -----page_id : 1, page total time: 1.48-----
2024-12-04 06:00:22.932 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:230 - ocr time: 0.87
2024-12-04 06:00:22.933 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:doc_analyze:168 - -----page_id : 2, page total time: 2.21-----
2024-12-04 06:00:23.384 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:184 - layout detection time: 0.91
2024-12-04 06:00:23.423 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:184 - layout detection time: 1.1
2024-12-04 06:00:23.433 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:184 - layout detection time: 1.14
2024-12-04 06:00:23.457 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:184 - layout detection time: 0.52
```

但在之后几页开始陆续报错

```bash
[2024-12-04 06:00:23,627: ERROR/MainProcess] Task app.celery_app.tasks.tasks.task_document_vectorize[9f0b0bda-e160-4978-9ce1-af94ee9832aa] raised unexpected: IndexError('index 1 is out of bounds for axis 0 with size 1')
Traceback (most recent call last):
  File "/opt/conda/envs/test_concurrency_MinerU/lib/python3.10/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/conda/envs/test_concurrency_MinerU/lib/python3.10/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/workspace/jiulian_dev/app/celery_app/tasks/tasks.py", line 238, in task_document_vectorize
    app_state["qdrant_vectorstore_management"].add_docs(file_keys)
  File "/workspace/jiulian_dev/utils/qdrant_vectorstore_manage.py", line 219, in add_docs
    model_json = transfer_to_model_json(pdf_bytes=pdf_bytes)
  File "/workspace/jiulian_dev/utils/qdrant_vectorstore_manage.py", line 67, in transfer_to_model_json
    model_json = doc_analyze(pdf_bytes=pdf_bytes, ocr=True, show_log=True)
  File "/opt/conda/envs/test_concurrency_MinerU/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 167, in doc_analyze
    result = custom_model(img)
  File "/opt/conda/envs/test_concurrency_MinerU/lib/python3.10/site-packages/magic_pdf/model/pdf_extract_kit.py", line 219, in __call__
    ocr_res = self.ocr_model.ocr(new_image, mfd_res=adjusted_mfdetrec_res)[0]
  File "/opt/conda/envs/test_concurrency_MinerU/lib/python3.10/site-packages/magic_pdf/model/sub_modules/ocr/paddleocr/ppocr_273_mod.py", line 70, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls, mfd_res=mfd_res)
  File "/opt/conda/envs/test_concurrency_MinerU/lib/python3.10/site-packages/magic_pdf/model/sub_modules/ocr/paddleocr/ppocr_273_mod.py", line 163, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/opt/conda/envs/test_concurrency_MinerU/lib/python3.10/site-packages/paddleocr/tools/infer/predict_rec.py", line 630, in __call__
    rec_res[indices[beg_img_no + rno]] = rec_result[rno]
IndexError: index 1 is out of bounds for axis 0 with size 1
```
并最终只剩下一个或两个线程的task正常完成

### How to reproduce the bug | 如何复现

pip list
```pip list
absl-py                                  2.1.0
accelerate                               1.1.1
aiohappyeyeballs                         2.4.4
aiohttp                                  3.11.9
aiosignal                                1.3.1
albucore                                 0.0.20
albumentations                           1.4.21
amqp                                     5.3.1
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                                    4.6.2.post1
argon2-cffi                              23.1.0
argon2-cffi-bindings                     21.2.0
asgiref                                  3.8.1
astor                                    0.8.1
async-timeout                            4.0.3
attrdict                                 2.0.1
attrs                                    24.2.0
babel                                    2.16.0
backoff                                  2.2.1
bce-python-sdk                           0.9.23
bcrypt                                   4.2.1
beautifulsoup4                           4.12.3
billiard                                 4.2.1
black                                    24.10.0
blinker                                  1.9.0
boto3                                    1.35.74
botocore                                 1.35.74
braceexpand                              0.1.7
Brotli                                   1.1.0
build                                    1.2.2.post1
cachetools                               5.5.0
celery                                   5.4.0
certifi                                  2024.8.30
cffi                                     1.17.1
charset-normalizer                       3.4.0
chroma-hnswlib                           0.7.6
chromadb                                 0.5.21
click                                    8.1.7
click-didyoumean                         0.3.1
click-plugins                            1.1.1
click-repl                               0.3.0
cloudpickle                              3.1.0
coloredlogs                              15.0.1
colorlog                                 6.9.0
contourpy                                1.3.1
cssselect                                1.2.0
cssutils                                 2.11.1
cycler                                   0.12.1
Cython                                   3.0.11
dashscope                                1.20.14
dataclasses-json                         0.6.7
datasets                                 3.1.0
decorator                                5.1.1
Deprecated                               1.2.15
detectron2                               0.6
dill                                     0.3.8
distro                                   1.9.0
doclayout_yolo                           0.0.2
durationpy                               0.9
einops                                   0.8.0
et_xmlfile                               2.0.0
eva-decord                               0.6.1
eval_type_backport                       0.2.0
evaluate                                 0.4.3
exceptiongroup                           1.2.2
fairscale                                0.4.13
fast-langdetect                          0.2.0
fastapi                                  0.115.6
fasttext-wheel                           0.9.2
filelock                                 3.16.1
fire                                     0.7.0
Flask                                    3.1.0
flask-babel                              4.0.0
flatbuffers                              24.3.25
fonttools                                4.55.1
frozenlist                               1.5.0
fsspec                                   2024.9.0
ftfy                                     6.3.1
future                                   1.0.0
fvcore                                   0.1.5.post20221221
gevent                                   24.11.1
google-auth                              2.36.0
googleapis-common-protos                 1.66.0
greenlet                                 3.1.1
grpcio                                   1.68.1
grpcio-tools                             1.68.1
h11                                      0.14.0
h2                                       4.1.0
hpack                                    4.0.0
httpcore                                 1.0.7
httptools                                0.6.4
httpx                                    0.28.0
httpx-sse                                0.4.0
huggingface-hub                          0.26.3
humanfriendly                            10.0
hydra-core                               1.3.2
hyperframe                               6.0.1
idna                                     3.10
imageio                                  2.36.1
imgaug                                   0.4.0
importlib_metadata                       8.5.0
importlib_resources                      6.4.5
iopath                                   0.1.9
itsdangerous                             2.2.0
Jinja2                                   3.1.4
jiter                                    0.8.0
jmespath                                 1.0.1
joblib                                   1.4.2
jsonpatch                                1.33
jsonpointer                              3.0.0
kiwisolver                               1.4.7
kombu                                    5.4.2
kubernetes                               31.0.0
langchain                                0.3.9
langchain-chroma                         0.1.4
langchain-community                      0.3.9
langchain-core                           0.3.21
langchain-huggingface                    0.1.2
langchain-openai                         0.2.11
langchain-qdrant                         0.2.0
langchain-text-splitters                 0.3.2
langdetect                               1.0.9
langsmith                                0.1.147
lazy_loader                              0.4
lmdb                                     1.5.1
loguru                                   0.7.2
lxml                                     5.3.0
magic-pdf                                0.10.5
Markdown                                 3.7
markdown-it-py                           3.0.0
MarkupSafe                               3.0.2
marshmallow                              3.23.1
matplotlib                               3.9.3
mdurl                                    0.1.2
minio                                    7.2.12
mmh3                                     5.0.1
monotonic                                1.6
more-itertools                           10.5.0
mpmath                                   1.3.0
multidict                                6.1.0
multiprocess                             0.70.16
mypy-extensions                          1.0.0
networkx                                 3.4.2
numpy                                    1.26.4
nvidia-cublas-cu11                       11.11.3.6
nvidia-cublas-cu12                       12.1.3.1
nvidia-cuda-cupti-cu11                   11.8.87
nvidia-cuda-cupti-cu12                   12.1.105
nvidia-cuda-nvrtc-cu11                   11.8.89
nvidia-cuda-nvrtc-cu12                   12.1.105
nvidia-cuda-runtime-cu11                 11.8.89
nvidia-cuda-runtime-cu12                 12.1.105
nvidia-cudnn-cu11                        8.7.0.84
nvidia-cudnn-cu12                        8.9.2.26
nvidia-cufft-cu11                        10.9.0.58
nvidia-cufft-cu12                        11.0.2.54
nvidia-curand-cu11                       10.3.0.86
nvidia-curand-cu12                       10.3.2.106
nvidia-cusolver-cu11                     11.4.1.48
nvidia-cusolver-cu12                     11.4.5.107
nvidia-cusparse-cu11                     11.7.5.86
nvidia-cusparse-cu12                     12.1.0.106
nvidia-nccl-cu11                         2.19.3
nvidia-nccl-cu12                         2.20.5
nvidia-nvjitlink-cu12                    12.6.85
nvidia-nvtx-cu11                         11.8.86
nvidia-nvtx-cu12                         12.1.105
oauthlib                                 3.2.2
omegaconf                                2.3.0
onnxruntime                              1.20.1
openai                                   1.56.1
opencv-contrib-python                    4.6.0.66
opencv-python                            4.6.0.66
opencv-python-headless                   4.10.0.84
openpyxl                                 3.1.5
opentelemetry-api                        1.28.2
opentelemetry-exporter-otlp-proto-common 1.28.2
opentelemetry-exporter-otlp-proto-grpc   1.28.2
opentelemetry-instrumentation            0.49b2
opentelemetry-instrumentation-asgi       0.49b2
opentelemetry-instrumentation-fastapi    0.49b2
opentelemetry-proto                      1.28.2
opentelemetry-sdk                        1.28.2
opentelemetry-semantic-conventions       0.49b2
opentelemetry-util-http                  0.49b2
opt-einsum                               3.3.0
orjson                                   3.10.12
overrides                                7.7.0
packaging                                24.2
paddleocr                                2.7.3
paddlepaddle                             3.0.0b1
paddlepaddle-gpu                         3.0.0b1
pandas                                   2.2.3
pathspec                                 0.12.1
pdf2docx                                 0.5.8
pillow                                   11.0.0
pip                                      24.2
platformdirs                             4.3.6
portalocker                              2.10.1
posthog                                  3.7.4
premailer                                3.10.0
prompt_toolkit                           3.0.48
propcache                                0.2.1
protobuf                                 5.29.0
psutil                                   6.1.0
py-cpuinfo                               9.0.0
pyarrow                                  18.1.0
pyasn1                                   0.6.1
pyasn1_modules                           0.4.1
pybind11                                 2.13.6
pyclipper                                1.3.0.post6
pycocotools                              2.0.8
pycparser                                2.22
pycryptodome                             3.21.0
pydantic                                 2.7.4
pydantic_core                            2.18.4
pydantic-settings                        2.6.1
Pygments                                 2.18.0
PyMuPDF                                  1.24.14
pypandoc                                 1.14
pyparsing                                3.2.0
PyPika                                   0.48.9
pyproject_hooks                          1.2.0
python-dateutil                          2.9.0.post0
python-docx                              1.1.2
python-dotenv                            1.0.1
pytz                                     2024.2
PyYAML                                   6.0.2
qdrant-client                            1.12.1
rapid-table                              0.3.0
RapidFuzz                                3.10.1
rapidocr-paddle                          1.4.1
rarfile                                  4.2
redis                                    5.2.0
regex                                    2024.11.6
requests                                 2.32.3
requests-oauthlib                        2.0.0
requests-toolbelt                        1.0.0
rich                                     13.9.4
robust-downloader                        0.0.2
rsa                                      4.9
s3transfer                               0.10.4
safetensors                              0.4.5
scikit-image                             0.24.0
scikit-learn                             1.5.2
scipy                                    1.14.1
seaborn                                  0.13.2
sentence-transformers                    3.3.1
setuptools                               75.1.0
shapely                                  2.0.6
shellingham                              1.5.4
simsimd                                  6.2.1
six                                      1.16.0
sniffio                                  1.3.1
socksio                                  1.0.0
soupsieve                                2.6
SQLAlchemy                               2.0.36
starlette                                0.41.3
stringzilla                              3.11.0
struct-eqtable                           0.3.2
sympy                                    1.13.3
tabulate                                 0.9.0
tenacity                                 9.0.0
tensorboard                              2.18.0
tensorboard-data-server                  0.7.2
termcolor                                2.5.0
thop                                     0.1.1.post2209072238
threadpoolctl                            3.5.0
tifffile                                 2024.9.20
tiktoken                                 0.8.0
timm                                     0.9.16
tokenizers                               0.19.1
tomli                                    2.2.1
torch                                    2.3.1
torchtext                                0.18.0
torchvision                              0.18.1
tqdm                                     4.67.1
transformers                             4.42.4
triton                                   2.3.1
typer                                    0.15.0
typing_extensions                        4.12.2
typing-inspect                           0.9.0
tzdata                                   2024.2
ultralytics                              8.3.40
ultralytics-thop                         2.0.12
unimernet                                0.2.1
urllib3                                  2.2.3
uvicorn                                  0.32.1
uvloop                                   0.21.0
vine                                     5.1.0
visualdl                                 2.5.3
Wand                                     0.6.13
watchfiles                               1.0.0
wcwidth                                  0.2.13
webdataset                               0.2.100
websocket-client                         1.8.0
websockets                               14.1
Werkzeug                                 3.1.3
wheel                                    0.44.0
wrapt                                    1.17.0
xxhash                                   3.5.0
yacs                                     0.1.8
yarl                                     1.18.3
zipp                                     3.21.0
zope.event                               5.0
zope.interface                           7.2
```

 ~/magic-pdf.json
```json
{
    "bucket_info": {
        "bucket-name-1": [
            "ak",
            "sk",
            "endpoint"
        ],
        "bucket-name-2": [
            "ak",
            "sk",
            "endpoint"
        ]
    },
    "models-dir": "/root/.cache/modelscope/hub/opendatalab/PDF-Extract-Kit-1___0/models",
    "layoutreader-model-dir": "/root/.cache/modelscope/hub/ppaanngggg/layoutreader",
    "device-mode": "cuda",
    "layout-config": {
        "model": "layoutlmv3"
    },
    "formula-config": {
        "mfd_model": "yolo_v8_mfd",
        "mfr_model": "unimernet_small",
        "enable": false
    },
    "table-config": {
        "enable": false,
        "max_time": 400
    },
    "config_version": "1.0.0"
}
```

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
可以试着减少线程的数量直至稳定，或者在创建两个线程之间加入sleep

**Comment by myhloli** [comment]
问了qwen，感觉是paddle没有对多线程进行优化导致的
```
在多线程环境中遇到 IndexError 通常意味着可能存在竞态条件（race condition），即多个线程尝试同时访问和修改共享资源，导致数据不一致。对于你所描述的问题，以下是一些建议来解决这个问题：

线程安全
使用线程安全的数据结构：如果你的程序中使用了任何非线程安全的数据结构或对象（如列表、字典等），考虑替换为线程安全的版本，或者在操作这些对象时使用锁（Lock）机制。
加锁保护关键代码段：对于可能会被多个线程并发访问的关键代码段，比如对 rec_res 和 indices 的操作，可以使用 Python 的 threading.Lock 或 threading.RLock 来确保同一时间只有一个线程能够执行该段代码。这可以通过创建一个锁对象并在进入关键代码段之前获取锁，在退出时释放锁来实现。
```
多个ocr任务在一起会因为线程间共享了某些对象导致前后数据不一致，估计得在paddleocr上修

**Comment by ElsaReedz** [comment]
> 问了qwen，感觉是paddle没有对多线程进行优化导致的
> 
> ```
> 在多线程环境中遇到 IndexError 通常意味着可能存在竞态条件（race condition），即多个线程尝试同时访问和修改共享资源，导致数据不一致。对于你所描述的问题，以下是一些建议来解决这个问题：
> 
> 线程安全
> 使用线程安全的数据结构：如果你的程序中使用了任何非线程安全的数据结构或对象（如列表、字典等），考虑替换为线程安全的版本，或者在操作这些对象时使用锁（Lock）机制。
> 加锁保护关键代码段：对于可能会被多个线程并发访问的关键代码段，比如对 rec_res 和 indices 的操作，可以使用 Python 的 threading.Lock 或 threading.RLock 来确保同一时间只有一个线程能够执行该段代码。这可以通过创建一个锁对象并在进入关键代码段之前获取锁，在退出时释放锁来实现。
> ```
> 
> 多个ocr任务在一起会因为线程间共享了某些对象导致前后数据不一致，估计得在paddleocr上修

感谢回复，我查阅了paddle库的相关issue，确实在多线程下paddle不是线程安全的

https://github.com/PaddlePaddle/Paddle/issues/56524

但似乎也提供了解决方案
https://github.com/PaddlePaddle/Paddle/issues/56524#issuecomment-1687519237

是否可以考虑在后续版本中添加该特性

**Comment by myhloli** [comment]
我试着给ocr加了个锁，多线程的情况下有好转，4个并发正常，6个并发会挂一个，8个并发挂两个，之前不加锁的时候4个并发会挂俩，6个挂4个，但是加锁之后的结果和预期不符，理论应该不会再因为多线程挂任务，如果你的并发需求不高可以通过这种方式临时解决下

**Comment by ElsaReedz** [comment]
> 我试着给ocr加了个锁，多线程的情况下有好转，4个并发正常，6个并发会挂一个，8个并发挂两个，之前不加锁的时候4个并发会挂俩，6个挂4个，但是加锁之后的结果和预期不符，理论应该不会再因为多线程挂任务，如果你的并发需求不高可以通过这种方式临时解决下

感谢回复，请问您具体是在哪个位置加的锁呢，还有这个加锁之后与结果预期不符具体是指什么呢

**Comment by myhloli** [comment]
预期就是不再发生资源竞争导致的error，现在加了锁之后还是会有，也不知道哪里还有问题

**Comment by myhloli** [comment]
加锁的代码可以参考这个push

https://github.com/opendatalab/MinerU/pull/1193/files
如果有条件的话麻烦也帮忙测一下稳定性

**Comment by myhloli** [comment]
今天修复了多线程资源冲突的问题之后做了性能测试，多线程除了能够有效增加并发任务数以外，相比单线程没有任何性能上的提升，核心原因是由于paddle本身不支持多线程，本项目又在相当多的地方需要调用paddle的相关逻辑（det和rec），参考 https://github.com/PaddlePaddle/Paddle/issues/56524

paddle的设计是尽量吃满所有资源的，所以多个线程使用paddle时一定会发生严重的资源抢占情况，即使在多个线程中能够做到对象不相互干扰，也会存在大量的等待时间，导致所有任务整体上的降速，因此本项目将会终止对多线程的兼容工作，直到有更好的库换掉paddle之后。

**Comment by wpjgit** [comment]
> ### Description of the bug | 错误描述
> 使用celery进行任务管理，在一个task中调用MinerU进行文档解析，并在worker初始化时，初始化MinerU相关模型。线程池策略为-P threads

@ElsaReedz 

请教一下，celery是怎么结合MinerU使用的，我在celery中调用mineru的时候，会被mineru解析的代码阻塞住，这个时候celery就不消费其他任务了
celery启动命令：celery -A celery_main.celery worker -P gevent -Q test_queue --loglevel INFO
celery任务代码
`
@shared_task(queue='test_queue')
def task():
    xxx
    ds = PdfDataset(pdf_bytes)
    infer_result = ds.apply(doc_analyze, ocr=True)
    print(infer_result)
`

**Comment by ElsaReedz** [comment]
> > ### Description of the bug | 错误描述
> > 使用celery进行任务管理，在一个task中调用MinerU进行文档解析，并在worker初始化时，初始化MinerU相关模型。线程池策略为-P threads
> 
> [@ElsaReedz](https://github.com/ElsaReedz)
> 
> 请教一下，celery是怎么结合MinerU使用的，我在celery中调用mineru的时候，会被mineru解析的代码阻塞住，这个时候celery就不消费其他任务了 celery启动命令：celery -A celery_main.celery worker -P gevent -Q test_queue --loglevel INFO celery任务代码 `@shared_task(queue='test_queue') def task(): xxx ds = PdfDataset(pdf_bytes) infer_result = ds.apply(doc_analyze, ocr=True) print(infer_result)`

印象中是celery线程池策略设置的问题，gevent会拥塞到mineru所在的task执行结束。你可以在celery启动命令中尝试设置为-P threads模式，我用这个设置是可以正常并发的

**Comment by wpjgit** [comment]
> 印象中是celery线程池策略设置的问题，gevent会拥塞到mineru所在的task执行结束。你可以在celery启动命令中尝试设置为-P threads模式，我用这个设置是可以正常并发的

我试了下，是可以的，感谢感谢
