### ISSUE TITLE
Magic-pdf安装成功，运行时显示找不到路径'/tmp/ultralytics_runner'

### ISSUE THREAD

**Issue by luwin1127** [opendatalab/MinerU#1200]
### Description of the bug | 错误描述

按照要求下载新建conda环境，配置python 3.10，安装magic-pdf，并且下载好模型文件。运行`magic_pdf_parse_main.py`和`demo.py`，均显示：
```
2024-12-06 10:25:54.659 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars_by_pymupdf:84 - uffd_count: 0, text_len: 0, uffd_chars_radio: 0
2024-12-06 10:25:54.667 | WARNING  | magic_pdf.filter.pdf_classify_by_type:classify:334 - pdf is not classified by area and text_len, by_image_area: False, by_text: False, by_avg_words: False, by_img_num: True, by_text_layout: False, by_img_narrow_strips: False, by_invalid_chars: True
2024-12-06 10:25:54.674 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:78 - DocAnalysis init, this may take some times, layout_model: layoutlmv3, apply_formula: True, apply_ocr: True, apply_table: False, table_model: rapid_table, lang: None
2024-12-06 10:25:54.674 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:91 - using device: cpu
2024-12-06 10:25:54.674 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:95 - using models_dir: C:\Users\49431\.cache\modelscope\hub\opendatalab\PDF-Extract-Kit-1___0/models
curl: (23) client returned ERROR on write of 124 bytes
2024-12-06 10:25:55.039 | ERROR    | __main__:pdf_parse_main:136 - [WinError 3] 系统找不到指定的路径。: '/tmp/ultralytics_runner'
Traceback (most recent call last):

  File "c:\Users\49431\.conda\envs\MinerU\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
           │         └ <code object <module> at 0x00000233A9329790, file "c:\Users\49431\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bu...
           └ <function _run_code at 0x00000233A93312D0>

  File "c:\Users\49431\.conda\envs\MinerU\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
         └ <code object <module> at 0x00000233A9329790, file "c:\Users\49431\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bu...

  File "c:\Users\49431\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\__main__.py", line 71, in <module>
    cli.main()
    │   └ <function main at 0x00000233ABA8FEB0>
    └ <module 'debugpy.server.cli' from 'c:\\Users\\49431\\.vscode\\extensions\\ms-python.debugpy-2024.12.0-win32-x64\\bundled\\lib...

  File "c:\Users\49431\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 501, in main
    run()
    └ <function run_file at 0x00000233ABA8FC70>

  File "c:\Users\49431\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
    │     │        └ 'd:\\opps\\Desktop\\MinerU\\demo\\magic_pdf_parse_main.py'
    │     └ <function run_path at 0x00000233AB6FDF30>
    └ <module '_pydevd_bundle.pydevd_runpy' from 'c:\\Users\\49431\\.vscode\\extensions\\ms-python.debugpy-2024.12.0-win32-x64\\bun...

  File "c:\Users\49431\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
           │                │     │             │                  │                     └ 'd:\\opps\\Desktop\\MinerU\\demo\\magic_pdf_parse_main.py'
           │                │     │             │                  └ ''
           │                │     │             └ '__main__'
           │                │     └ None
           │                └ <code object <module> at 0x00000233ABB9F5D0, file "d:\opps\Desktop\MinerU\demo\magic_pdf_parse_main.py", line 1>
           └ <function _run_module_code at 0x00000233AB6FDBD0>

  File "c:\Users\49431\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
    │         │     │            │             │         │         │         └ 'd:\\opps\\Desktop\\MinerU\\demo\\magic_pdf_parse_main.py'
    │         │     │            │             │         │         └ ''
    │         │     │            │             │         └ None
    │         │     │            │             └ '__main__'
    │         │     │            └ None
    │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': None, '__spec__': None, '__file__': 'd:\\opps\\Des...
    │         └ <code object <module> at 0x00000233ABB9F5D0, file "d:\opps\Desktop\MinerU\demo\magic_pdf_parse_main.py", line 1>
    └ <function _run_code at 0x00000233AB6FD7E0>

  File "c:\Users\49431\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': None, '__spec__': None, '__file__': 'd:\\opps\\Des...
         └ <code object <module> at 0x00000233ABB9F5D0, file "d:\opps\Desktop\MinerU\demo\magic_pdf_parse_main.py", line 1>

  File "d:\opps\Desktop\MinerU\demo\magic_pdf_parse_main.py", line 147, in <module>
    pdf_parse_main(file_path)
    │              └ 'd:\\opps\\Desktop\\MinerU\\demo\\small_ocr.pdf'
    └ <function pdf_parse_main at 0x00000233EB9FE440>

> File "d:\opps\Desktop\MinerU\demo\magic_pdf_parse_main.py", line 119, in pdf_parse_main
    pipe.pipe_analyze()  # 解析
    │    └ <function UNIPipe.pipe_analyze at 0x00000233EB9FE170>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x00000233EB9E74C0>

  File "c:\Users\49431\.conda\envs\MinerU\lib\site-packages\magic_pdf\pipe\UNIPipe.py", line 36, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=True,
    │    │            │           │    └ b'%PDF-1.7\r\n%\xa1\xb3\xc5\xd7\r\n1 0 obj\r\n<</Pages 2 0 R /Type/Catalog>>\r\nendobj\r\n2 0 obj\r\n<</Count 8/Kids[ 4 0 R  ...
    │    │            │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x00000233EB9E74C0>
    │    │            └ <function doc_analyze at 0x00000233D38FBAC0>
    │    └ []
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x00000233EB9E74C0>

  File "c:\Users\49431\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line 147, in doc_analyze
    custom_model = model_manager.get_model(ocr, show_log, lang, layout_model, formula_enable, table_enable)
                   │             │         │    │         │     │             │               └ None
                   │             │         │    │         │     │             └ None
                   │             │         │    │         │     └ None
                   │             │         │    │         └ None
                   │             │         │    └ False
                   │             │         └ True
                   │             └ <function ModelSingleton.get_model at 0x00000233D38FBA30>
                   └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x00000233EB9E6AD0>

  File "c:\Users\49431\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line 75, in get_model
    self._models[key] = custom_model_init(ocr=ocr, show_log=show_log, lang=lang, layout_model=layout_model,
    │    │       │      │                     │             │              │                  └ None
    │    │       │      │                     │             │              └ None
    │    │       │      │                     │             └ False
    │    │       │      │                     └ True
    │    │       │      └ <function custom_model_init at 0x00000233D38FB910>
    │    │       └ (True, False, None, None, None, None)
    │    └ {}
    └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x00000233EB9E6AD0>

  File "c:\Users\49431\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line 126, in custom_model_init
    custom_model = CustomPEKModel(**model_input)
                   │                └ {'ocr': True, 'show_log': False, 'models_dir': 'C:\\Users\\49431\\.cache\\modelscope\\hub\\opendatalab\\PDF-Extract-Kit-1___0...
                   └ <class 'magic_pdf.model.pdf_extract_kit.CustomPEKModel'>

  File "c:\Users\49431\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\pdf_extract_kit.py", line 102, in __init__
    self.mfd_model = atom_model_manager.get_atom_model(
    │                │                  └ <function AtomModelSingleton.get_atom_model at 0x00000233EB9E2EF0>
    │                └ <magic_pdf.model.sub_modules.model_init.AtomModelSingleton object at 0x00000233EB9E7370>
    └ <magic_pdf.model.pdf_extract_kit.CustomPEKModel object at 0x00000233EBA68CD0>

  File "c:\Users\49431\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\sub_modules\model_init.py", line 99, in get_atom_model
    self._models[key] = atom_model_init(model_name=atom_model_name, **kwargs)
    │    │       │      │                          │                  └ {'mfd_weights': 'C:\\Users\\49431\\.cache\\modelscope\\hub\\opendatalab\\PDF-Extract-Kit-1___0/models\\MFD/YOLO/yolo_v8_ft.pt...
    │    │       │      │                          └ 'mfd'
    │    │       │      └ <function atom_model_init at 0x00000233EB9E2DD0>
    │    │       └ ('mfd', None, None)
    │    └ {}
    └ <magic_pdf.model.sub_modules.model_init.AtomModelSingleton object at 0x00000233EB9E7370>

  File "c:\Users\49431\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\sub_modules\model_init.py", line 118, in atom_model_init
    atom_model = mfd_model_init(
                 └ <function mfd_model_init at 0x00000233EB9E2950>

  File "c:\Users\49431\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\sub_modules\model_init.py", line 41, in mfd_model_init
    mfd_model = YOLOv8MFDModel(weight, device)
                │              │       └ 'cpu'
                │              └ 'C:\\Users\\49431\\.cache\\modelscope\\hub\\opendatalab\\PDF-Extract-Kit-1___0/models\\MFD/YOLO/yolo_v8_ft.pt'
                └ <class 'magic_pdf.model.sub_modules.mfd.yolov8.YOLOv8.YOLOv8MFDModel'>

  File "c:\Users\49431\.conda\envs\MinerU\lib\site-packages\magic_pdf\model\sub_modules\mfd\yolov8\YOLOv8.py", line 6, in __init__
    self.mfd_model = YOLO(weight)
    │                │    └ 'C:\\Users\\49431\\.cache\\modelscope\\hub\\opendatalab\\PDF-Extract-Kit-1___0/models\\MFD/YOLO/yolo_v8_ft.pt'
    │                └ <class 'ultralytics.models.yolo.model.YOLO'>
    └ <magic_pdf.model.sub_modules.mfd.yolov8.YOLOv8.YOLOv8MFDModel object at 0x00000233EBA69AB0>

  File "c:\Users\49431\.conda\envs\MinerU\lib\site-packages\ultralytics\models\yolo\model.py", line 26, in __init__
    safe_run("/tmp/ultralytics_runner")
    └ <function safe_run at 0x00000233DD9888B0>

  File "c:\Users\49431\.conda\envs\MinerU\lib\site-packages\ultralytics\utils\downloads.py", line 283, in safe_run
    os.chmod(path, 0o770)
    │  │     └ '/tmp/ultralytics_runner'
    │  └ <built-in function chmod>
    └ <module 'os' from 'c:\\Users\\49431\\.conda\\envs\\MinerU\\lib\\os.py'>

FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '/tmp/ultralytics_runner'
```

问AI，说可以使用
```
# 设置临时目录为当前用户目录下的 Temp 文件夹
os.environ['TEMP'] = os.path.join(os.environ['USERPROFILE'], 'Temp')
```
解决该问题，但仍然报相同的错误。

请大神不吝赐教！

注：我的笔记本CPU为AMD Ryzen 7 7840H，显卡为集成显卡Radeon 780M Graphics。

### How to reproduce the bug | 如何复现

配置好环境，在vscode中debug`demo.py`或`magic_pdf_parse_main.py`。

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
我们今天也遇到了这个问题，查了下是ultralytics官方在12月2号至12月6号间发布了两个有问题的版本，现在需要将ultralytics更新到最新版8.3.43即可解决这个问题

**Comment by myhloli** [comment]
https://github.com/ultralytics/ultralytics/issues/18027
