### ISSUE TITLE
pip installation successful, but 'magic-pdf --version' cannot display the version

### ISSUE THREAD

**Issue by poplar-young** [opendatalab/MinerU#1219]
After successfully installing 'pip install -U magic-pdf[full] --extra-index-url https://wheels.myhloli.com', the command 'magic-pdf --version' displays the following:

PS D:\MinerU> magic-pdf --version
Traceback (most recent call last):
File "E:\app\Anaconda\envs\MinerU\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "E:\app\Anaconda\envs\MinerU\lib\runpy.py", line 86, in _run_code
Execute the code in the given environment
File "E:\app\Anaconda\envs\MinerU\Scripts\magic-pdf.exe\__main__.py", line 4, in <module>
from magic_pdf.tools.cli import cli
File "E:\app\Anaconda\envs\MinerU\lib\site-packages\magic_pdf\tools\cli.py", line 10, in <module>
from magic_pdf.tools.common import do_parse, parse_pdf_methods
File "E:\app\Anaconda\envs\MinerU\lib\site-packages\magic_pdf\tools\common.py", line 14, in <module>
from magic_pdf.pipe.OCRPipe import OCRPipe
File "E:\app\Anaconda\envs\MinerU\lib\site-packages\magic_pdf\pipe\OCRPipe.py", line 7, in <module>
from magic_pdf.user_api import parse_ocr_pdf
File "E:\app\Anaconda\envs\MinerU\lib\site-packages\magic_pdf\user_api.py", line 15, in <module>
from magic_pdf.pdf_parse_by_ocr import parse_pdf_by_ocr
File "E:\app\Anaconda\envs\MinerU\lib\site-packages\magic_pdf\pdf_parse_by_ocr.py", line 3, in <module>
from magic_pdf.pdf_parse_union_core_v2 import pdf_parse_union
File "E:\app\Anaconda\envs\MinerU\lib\site-packages\magic_pdf\pdf_parse_union_core_v2.py", line 34, in <module>
from magic_pdf.model.sub_modules.model_init import AtomModelSingleton
File "E:\app\Anaconda\envs\MinerU\lib\site-packages\magic_pdf\model\sub_modules\model_init.py", line 9, in <module>
from magic_pdf.model.sub_modules.mfd.yolov8.YOLOv8MFDModel import YOLOv8MFDModel
File "E:\app\Anaconda\envs\MinerU\lib\site-packages\magic_pdf\model\sub_modules\mfd\yolov8\YOLOv8.py", line 1, in <module>
from ultralytics import YOLO
File "E:\app\Anaconda\envs\MinerU\lib\site-packages\ultralytics\__init__.py", line 6, in <module>
import package
ModuleNotFoundError: No module named 'package'

Do I need to download the model file first, and then use 'magic-pdf --version' to check the version?

#Python 3.10.16
#windows11

**Comment by myhloli** [comment]
Please downgrade ultralytics to version 8.3.43 or 8.3.40.

**Comment by myhloli** [comment]
https://github.com/opendatalab/MinerU/issues/1202
