### ISSUE TITLE
Docker容器执行报错：ModuleNotFoundError: No module named 'package'

### ISSUE THREAD

**Issue by SWZ128** [opendatalab/MinerU#1225]
### Description of the bug | 错误描述

构建好Docker镜像后启动容器执行：
```
magic-pdf --help
```
报错：
```
Traceback (most recent call last):
  File "/opt/mineru_venv/bin/magic-pdf", line 5, in <module>
    from magic_pdf.tools.cli import cli
  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/tools/cli.py", line 10, in <module>
    from magic_pdf.tools.common import do_parse, parse_pdf_methods
  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/tools/common.py", line 14, in <module>
    from magic_pdf.pipe.OCRPipe import OCRPipe
  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/pipe/OCRPipe.py", line 7, in <module>
    from magic_pdf.user_api import parse_ocr_pdf
  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/user_api.py", line 15, in <module>
    from magic_pdf.pdf_parse_by_ocr import parse_pdf_by_ocr
  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/pdf_parse_by_ocr.py", line 3, in <module>
    from magic_pdf.pdf_parse_union_core_v2 import pdf_parse_union
  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core_v2.py", line 34, in <module>
    from magic_pdf.model.sub_modules.model_init import AtomModelSingleton
  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/model/sub_modules/model_init.py", line 9, in <module>
    from magic_pdf.model.sub_modules.mfd.yolov8.YOLOv8 import YOLOv8MFDModel
  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf/model/sub_modules/mfd/yolov8/YOLOv8.py", line 1, in <module>
    from ultralytics import YOLO
  File "/opt/mineru_venv/lib/python3.10/site-packages/ultralytics/__init__.py", line 6, in <module>
    import package
ModuleNotFoundError: No module named 'package'
```

### How to reproduce the bug | 如何复现

按照文档执行：
```
wget https://github.com/opendatalab/MinerU/raw/master/Dockerfile
docker build -t mineru:latest .
docker run --rm -it --gpus=all mineru:latest /bin/bash
magic-pdf --help
```

已知设备可以支持在docker上使用CUDA加速

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by SWZ128** [comment]
#1202
