### ISSUE TITLE
FileBasedDataWriter.write() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by yyxg** [opendatalab/MinerU#1287]
### Description of the bug | 错误描述

在运行 MinerU/projects/web_api/app.py后 解析pdf文件报错

### How to reproduce the bug | 如何复现

2024-12-13 10:15:47.391 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 14, text_len: 26394, cid_chars_radio: 0.0005324003650745361
import tensorrt_llm failed, if do not use tensorrt, ignore this message
import lmdeploy failed, if do not use lmdeploy, ignore this message
2024-12-13 10:15:51.597 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:68 - DocAnalysis init, this may take some times, layout_model: doclayout_yolo, apply_formula: True, apply_ocr: False, apply_table: True, table_model: tablemaster, lang: None
2024-12-13 10:15:51.597 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:77 - using device: cpu
2024-12-13 10:15:51.597 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:79 - using models_dir: /Users/xialihui/.cache/modelscope/hub/opendatalab/PDF-Extract-Kit-1___0/models
CustomVisionEncoderDecoderModel init
VariableUnimerNetModel init
VariableUnimerNetPatchEmbeddings init
VariableUnimerNetModel init
VariableUnimerNetPatchEmbeddings init
CustomMBartForCausalLM init
CustomMBartDecoder init
2024-12-13 10:16:04.102 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:137 - DocAnalysis init done!
2024-12-13 10:16:04.102 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:custom_model_init:131 - model init cost: 16.709622859954834
2024-12-13 10:16:07.002 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:153 - layout detection time: 2.73
2024-12-13 10:16:09.730 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:161 - mfd time: 2.72
2024-12-13 10:16:13.872 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:168 - formula nums: 2, mfr time: 4.14
2024-12-13 10:16:13.872 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:224 - table time: 0.0
2024-12-13 10:16:13.872 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:226 - -----page total time: 9.6-----
2024-12-13 10:16:15.028 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:153 - layout detection time: 1.16
2024-12-13 10:16:17.449 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:161 - mfd time: 2.42
2024-12-13 10:16:45.923 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:168 - formula nums: 27, mfr time: 28.47
2024-12-13 10:16:45.923 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:224 - table time: 0.0
2024-12-13 10:16:45.923 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:226 - -----page total time: 32.05-----
2024-12-13 10:16:47.103 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:153 - layout detection time: 1.18
2024-12-13 10:16:49.541 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:161 - mfd time: 2.44
2024-12-13 10:17:27.398 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:168 - formula nums: 34, mfr time: 37.86
2024-12-13 10:17:27.398 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:224 - table time: 0.0
2024-12-13 10:17:27.398 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:226 - -----page total time: 41.47-----
2024-12-13 10:17:28.510 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:153 - layout detection time: 1.11
2024-12-13 10:17:30.761 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:161 - mfd time: 2.25
2024-12-13 10:17:43.801 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:168 - formula nums: 26, mfr time: 13.04
[2024/12/13 10:20:03] ppocr DEBUG: dt_boxes num : 27, elapse : 0.09906387329101562
[2024/12/13 10:20:05] ppocr DEBUG: rec_res num  : 27, elapse : 2.570420980453491
2024-12-13 10:20:05.992 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:224 - table time: 142.19
2024-12-13 10:20:05.992 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:226 - -----page total time: 158.59-----
2024-12-13 10:20:07.045 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:153 - layout detection time: 1.05
2024-12-13 10:20:09.531 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:161 - mfd time: 2.48
2024-12-13 10:20:18.298 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:168 - formula nums: 8, mfr time: 8.77
[2024/12/13 10:22:38] ppocr DEBUG: dt_boxes num : 45, elapse : 0.10980820655822754
[2024/12/13 10:22:41] ppocr DEBUG: rec_res num  : 45, elapse : 3.3931000232696533
2024-12-13 10:22:41.881 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:224 - table time: 143.58
2024-12-13 10:22:41.881 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:226 - -----page total time: 155.89-----
2024-12-13 10:22:43.059 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:153 - layout detection time: 1.18
2024-12-13 10:22:45.519 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:161 - mfd time: 2.46
2024-12-13 10:22:45.520 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:168 - formula nums: 0, mfr time: 0.0
2024-12-13 10:22:45.520 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:224 - table time: 0.0
2024-12-13 10:22:45.520 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:226 - -----page total time: 3.64-----
2024-12-13 10:22:45.673 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:doc_analyze:176 - gc time: 0.15
2024-12-13 10:22:45.673 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:doc_analyze:180 - doc analyze time: 401.4, speed: 0.01 pages/second
2024-12-13 10:22:45.797 | ERROR    | magic_pdf.user_api:parse_pdf:97 - FileBasedDataWriter.write() takes 3 positional arguments but 4 were given
Traceback (most recent call last):

  File "/Users/xialihui/Documents/myocr/MinerU/projects/web_api/app.py", line 157, in <module>
    uvicorn.run(app, host='0.0.0.0', port=8888)
    │       │   └ <fastapi.applications.FastAPI object at 0x100d93b20>
    │       └ <function run at 0x10188f880>
    └ <module 'uvicorn' from '/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/uvicorn/__init__.py'>

  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
    │      └ <function Server.run at 0x10188f130>
    └ <uvicorn.server.Server object at 0x13fd65c90>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x10188f1c0>
           │       │   └ <uvicorn.server.Server object at 0x13fd65c90>
           │       └ <function run at 0x100e9ecb0>
           └ <module 'asyncio' from '/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/asyncio/__init__.py'>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x10d516d50>
           │    └ <function BaseEventLoop.run_until_complete at 0x101369120>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 628, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x101369090>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 595, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x10136ab90>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 1881, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x1012ba320>
    └ <Handle Task.task_wakeup(<Future finis...0\r%%EOF\n\r'>)>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finis...0\r%%EOF\n\r'>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finis...0\r%%EOF\n\r'>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finis...0\r%%EOF\n\r'>)>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x13fda4490>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x13ff50520>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x13ff50520>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
                 │    └ <fastapi.applications.FastAPI object at 0x100d93b20>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x13fda4490>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x13ff50520>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x13ff50520>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x13ff50520>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x13ff50520>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x13ff0b670>
          └ <fastapi.applications.FastAPI object at 0x100d93b20>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x13fd91120>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x13ff50520>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x13ff0b640>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x13ff0b670>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
          │                            │    │    │     │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x13fd91120>
          │                            │    │    │     │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x13ff50520>>
          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │                            │    │    └ <starlette.requests.Request object at 0x13ff0bac0>
          │                            │    └ <fastapi.routing.APIRouter object at 0x13fd655a0>
          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x13ff0b640>
          └ <function wrap_app_handling_exceptions at 0x1026fa7a0>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x13ff07a30>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x13ff50520>>
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          └ <fastapi.routing.APIRouter object at 0x13fd655a0>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x13ff07a30>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x13ff50520>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x13fd655a0>>
          └ <fastapi.routing.APIRouter object at 0x13fd655a0>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x13ff07a30>
          │     │      │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x13ff50520>>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │     └ <function Route.handle at 0x1026fbeb0>
          └ APIRoute(path='/pdf_parse', name='pdf_parse_main', methods=['POST'])
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x13ff07a30>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x13ff50520>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │    └ <function request_response.<locals>.app at 0x13fd90af0>
          └ APIRoute(path='/pdf_parse', name='pdf_parse_main', methods=['POST'])
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x13ff07a30>
          │                            │    │        │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x13ff50520>>
          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          │                            │    └ <starlette.requests.Request object at 0x13ff0bc10>
          │                            └ <function request_response.<locals>.app.<locals>.app at 0x13ff07e20>
          └ <function wrap_app_handling_exceptions at 0x1026fa7a0>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x13ff07eb0>
          │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x13ff50520>>
          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8888), 'cl...
          └ <function request_response.<locals>.app.<locals>.app at 0x13ff07e20>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
                     │ └ <starlette.requests.Request object at 0x13ff0bc10>
                     └ <function get_request_handler.<locals>.app at 0x13fd90a60>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x102719a20>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'parse_method': 'auto', 'model_json_path': None, 'is_json_md_dump': True, 'output_dir': 'output', 'pdf_file': UploadFile(fil...
                 │         └ <function pdf_parse_main at 0x13fd6f910>
                 └ Dependant(path_params=[], query_params=[ModelField(field_info=Query(auto), name='parse_method', mode='validation'), ModelFiel...

  File "/Users/xialihui/Documents/myocr/MinerU/projects/web_api/app.py", line 131, in pdf_parse_main
    pipe.pipe_parse()
    │    └ <function UNIPipe.pipe_parse at 0x13fd6f2e0>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x13ff53a00>

  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 44, in pipe_parse
    self.pdf_mid_data = parse_union_pdf(self.pdf_bytes, self.model_list, self.image_writer,
    │    │              │               │    │          │    │           │    └ <magic_pdf.data.data_reader_writer.filebase.FileBasedDataWriter object at 0x13ff0ba30>
    │    │              │               │    │          │    │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x13ff53a00>
    │    │              │               │    │          │    └ [{'layout_dets': [{'category_id': 1, 'poly': [133, 926, 834, 926, 834, 1322, 133, 1322], 'score': 0.984, 'bbox': [47, 333, 30...
    │    │              │               │    │          └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x13ff53a00>
    │    │              │               │    └ b'%PDF-1.5\r%\x80\x84\x88\x8c\x90\x94\x98\x9c\xa0\xa4\xa8\xac\xb0\xb4\xb8\xbc\xc0\xc4\xc8\xcc\xd0\xd4\xd8\xdc\xe0\xe4\xe8\xec...
    │    │              │               └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x13ff53a00>
    │    │              └ <function parse_union_pdf at 0x13fd6e680>
    │    └ None
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x13ff53a00>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/magic_pdf/user_api.py", line 100, in parse_union_pdf
    pdf_info_dict = parse_pdf(parse_pdf_by_txt)
                    │         └ <function parse_pdf_by_txt at 0x13fd6e560>
                    └ <function parse_union_pdf.<locals>.parse_pdf at 0x13ff95d80>
> File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/magic_pdf/user_api.py", line 88, in parse_pdf
    return method(
           └ <function parse_pdf_by_txt at 0x13fd6e560>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/magic_pdf/pdf_parse_by_txt.py", line 15, in parse_pdf_by_txt
    return pdf_parse_union(dataset,
           │               └ <magic_pdf.data.dataset.PymuDocDataset object at 0x2afe37d90>
           └ <function pdf_parse_union at 0x13fd6e4d0>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core_v2.py", line 654, in pdf_parse_union
    page_info = parse_page_core(
                └ <function parse_page_core at 0x13fd6e440>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core_v2.py", line 541, in parse_page_core
    spans = ocr_cut_image_and_table(
            └ <function ocr_cut_image_and_table at 0x13fd4f370>
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/magic_pdf/pre_proc/cut_image.py", line 17, in ocr_cut_image_and_table
    span['image_path'] = cut_image(span['bbox'], page_id, page, return_path=return_path('images'),
    │                    │         │             │        │                 └ <function ocr_cut_image_and_table.<locals>.return_path at 0x2b0427e20>
    │                    │         │             │        └ <magic_pdf.data.dataset.Doc object at 0x2afe37910>
    │                    │         │             └ 0
    │                    │         └ {'bbox': [313, 244, 559, 349], 'score': 0.93, 'type': 'image'}
    │                    └ <function cut_image at 0x13fd4f520>
    └ {'bbox': [313, 244, 559, 349], 'score': 0.93, 'type': 'image'}
  File "/Users/xialihui/.pyenv/versions/3.10.0/lib/python3.10/site-packages/magic_pdf/libs/pdf_image_tools.py", line 31, in cut_image
    imageWriter.write(byte_data, img_hash256_path, AbsReaderWriter.MODE_BIN)
    │           │     │          │                 │               └ 'binary'
    │           │     │          │                 └ <class 'magic_pdf.rw.AbsReaderWriter.AbsReaderWriter'>
    │           │     │          └ '8688692fc656a65c2458014173fd9a4723111a439911d665d2255c3590f33759.jpg'
    │           │     └ b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x00`\x00`\x00\x00\xff\xdb\x00C\x00\x02\x01\x01\x01\x01\x01\x02\x01\x01\x01\x02...
    │           └ <function FileBasedDataWriter.write at 0x10280aef0>
    └ <magic_pdf.data.data_reader_writer.filebase.FileBasedDataWriter object at 0x13ff0ba30>

TypeError: FileBasedDataWriter.write() takes 3 positional arguments but 4 were given
2024-12-13 10:22:45.856 | WARNING  | magic_pdf.user_api:parse_union_pdf:102 - parse_pdf_by_txt drop or error, switch to parse_pdf_by_ocr

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
最近两个版本存在一些内部调用逻辑的重构，一些由外部贡献者提供的project未能及时更新，请参考最新的api文档自行改下内部的调用方式：

https://mineru.readthedocs.io/en/latest/user_guide/quick_start/to_markdown.html
