### ISSUE TITLE
`UNIPipe.pipe_classify` uses deleted `pdf_bytes` members in 0.10.6

### ISSUE THREAD

**Issue by CreeperLKF** [opendatalab/MinerU#1355]
### Description of the bug | 错误描述

Use UNIPipe class will cause the following error after upgrading to 0.10.6 (from 0.10.5 which works fine).
``` python
Traceback (most recent call last):
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/gradio/queueing.py", line 625, in process_events
    response = await route_utils.call_process_api(
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/gradio/blocks.py", line 2047, in process_api
    result = await self.call_function(
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/gradio/blocks.py", line 1594, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/gradio/utils.py", line 869, in wrapper
    response = f(*args, **kwargs)
  File "/root/shared-nvme/MinerU/MinerU-webui/webui.py", line 215, in pdf_parse
    file_name  = os.path.basename(pdf_path)
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
2024-12-24 16:03:00.661 | INFO     | __main__:pdf_parse_main:98 - 任务开始处理了
2024-12-24 16:03:00.665 | ERROR    | __main__:pdf_parse_main:170 - 'UNIPipe' object has no attribute 'pdf_bytes'
Traceback (most recent call last):

  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fdace0f4c10>
    └ <WorkerThread(AnyIO worker thread, started daemon 140561931564608)>
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
    │    └ <function WorkerThread.run at 0x7fd82ca84820>
    └ <WorkerThread(AnyIO worker thread, started daemon 140561931564608)>
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1005, in run
    result = context.run(func, *args)
             │       │   │      └ ('/tmp/gradio/2433bce368ba52d9a07da344a6d3e898b6ca1ead825efe7c22e6b0c9c47149b1/Next_Generation_Design_For_Testability_Debug_a...
             │       │   └ <function pdf_parse at 0x7fd82cac0310>
             │       └ <method 'run' of '_contextvars.Context' objects>
             └ <_contextvars.Context object at 0x7fd82d0e2540>
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/gradio/utils.py", line 869, in wrapper
    response = f(*args, **kwargs)
               │  │       └ {}
               │  └ ('/tmp/gradio/2433bce368ba52d9a07da344a6d3e898b6ca1ead825efe7c22e6b0c9c47149b1/Next_Generation_Design_For_Testability_Debug_a...
               └ <function pdf_parse at 0x7fd83b60ec20>

  File "/root/shared-nvme/MinerU/MinerU-webui/webui.py", line 222, in pdf_parse
    [markdown_content,file_path] = pdf_parse_main(target_pdf_path,progress)
                                   │              │               └ <gradio.helpers.Progress object at 0x7fd82cab4fa0>
                                   │              └ '/root/shared-nvme/MinerU/MinerU-webui/.temp/Next_Generation_Design_For_Testability_Debug_and_Reliability_Using_Formal_Techni...
                                   └ <function pdf_parse_main at 0x7fd83b60d3f0>

> File "/root/shared-nvme/MinerU/MinerU-webui/webui.py", line 147, in pdf_parse_main
    pipe.pipe_classify()
    │    └ <function UNIPipe.pipe_classify at 0x7fd84044c790>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fd82cab5db0>

  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 48, in pipe_classify
    self.pdf_type = AbsPipe.classify(self.pdf_bytes)
    │    │          │       │        └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fd82cab5db0>
    │    │          │       └ <staticmethod(<function AbsPipe.classify at 0x7fd840437eb0>)>
    │    │          └ <class 'magic_pdf.pipe.AbsPipe.AbsPipe'>
    │    └ ''
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fd82cab5db0>

AttributeError: 'UNIPipe' object has no attribute 'pdf_bytes'. Did you mean: 'pdf_type'?
Traceback (most recent call last):
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/gradio/queueing.py", line 625, in process_events
    response = await route_utils.call_process_api(
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/gradio/blocks.py", line 2047, in process_api
    result = await self.call_function(
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/gradio/blocks.py", line 1594, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "/root/shared-nvme/conda/envs/MinerU/lib/python3.10/site-packages/gradio/utils.py", line 869, in wrapper
    response = f(*args, **kwargs)
  File "/root/shared-nvme/MinerU/MinerU-webui/webui.py", line 222, in pdf_parse
    [markdown_content,file_path] = pdf_parse_main(target_pdf_path,progress)
TypeError: cannot unpack non-iterable NoneType object
```

### How to reproduce the bug | 如何复现

The following code doesn't work in 0.10.6 but works in 0.10.5 (from MinerU-webui).
``` python
pipe = UNIPipe(pdf_bytes, jso_useful_key, image_writer)
```

The `pdf_bytes` member has been changed into `dataset` but it remains unchanged in `UNIPipe.pipe_classify` in:
https://github.com/opendatalab/MinerU/blob/c4f252d316a72b5dc51e164bffa62aa8adf2bba9/magic_pdf/pipe/UNIPipe.py#L47-L48

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.10.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
We have upgraded the invocation method of our internal interfaces. Unipipe has been deprecated and will be completely removed in future releases. Version 0.10.6 serves as a transitional version from 0.x to 1.x; the invocation methods and documentation for the interfaces are not yet finalized. If you need to continue using unipipe to invoke core functionalities, please maintain your version at <=0.10.5. We will update the interface invocation documentation after the release of version 1.0.x.
