### ISSUE TITLE
解析文本型pdf时出现 magic_pdf.user_api:parse_pdf:85 - list index out of range

### ISSUE THREAD

**Issue by madlogos** [opendatalab/MinerU#162]
### Description of the bug | 错误描述

医学论文pdf，图文俱备。解析时报两个错：

- INFO        | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 3, text_len: 45665, cid_chars_radio: 6.57217341774925e-05
- ERROR    | magic_pdf.user_api:parse_pdf:85 - list index out of range

最后，没有直接提取文本，而是通过ocr识别得到的markdown文档，出现不少错误：

1. 上标注释很多都识别错误，比如作者列表5、6、7、8都识别错了
2. 部分文字丢失，比如Table1的第一行，完全丢失
3. 一些小排版问题，比如单词换行连接符仍然保留了下来，没有还原单词。

### How to reproduce the bug | 如何复现

```python
import pathlib
import json

from loguru import logger

from magic_pdf.pipe.UNIPipe import UNIPipe
from magic_pdf.rw.DiskReaderWriter import DiskReaderWriter

import magic_pdf.model as model_config 
model_config.__use_inside_model__ = True

def gen_md(pdf_file: str):
    try:
        pdf_path = pathlib.Path(pdf_file)
        task_name = pdf_path.stem
        task_dir = pdf_path.parent
        model_path = task_dir.joinpath(task_name + '.json')
        pdf_bytes = open(pdf_path, 'rb').read()
        # model_json = json.loads(open(model_path, 'r', encoding='utf-8').read())
        model_json = []  # model_json传空list使用内置模型解析
        jso_useful_key = {'_pdf_type': '', 'model_list': model_json}
        local_image_dir = task_dir.joinpath(task_name, 'img')
        image_dir = str(pathlib.PurePath(local_image_dir).name)
        image_writer = DiskReaderWriter(local_image_dir)
        pipe = UNIPipe(pdf_bytes, jso_useful_key, image_writer)
        pipe.pipe_classify()
        pipe.pipe_parse()
        md_content = pipe.pipe_mk_markdown(image_dir, drop_mode='none')
        with open(f'{task_name}_mineru.md', 'w', encoding='utf-8') as f:
            f.write(md_content)
    except Exception as e:
        logger.exception(e)

gen_md('demo1.pdf')
```

日志：

```
2024-07-17 23:38:42.992 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 3, text_len: 45665, cid_chars_radio: 6.57217341774925e-05
2024-07-17 23:38:42.998 | ERROR    | magic_pdf.user_api:parse_pdf:85 - list index out of range
Traceback (most recent call last):

  File "[/opt/anaconda3/envs/mineru/lib/python3.10/runpy.py", line 196](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/runpy.py#line=195), in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x7fd8c4c7ece0, file "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel_launcher.py](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel_launcher.py)"...
           └ <function _run_code at 0x7fd8c4c8b2e0>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/runpy.py", line 86](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/runpy.py#line=85), in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x7fd8c4c7ece0, file "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel_launcher.py](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel_launcher.py)"...
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel_launcher.py", line 17](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel_launcher.py#line=16), in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel/kernelapp.py](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel/kernelapp.py)'>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/traitlets/config/application.py", line 1075](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/traitlets/config/application.py#line=1074), in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x7fd8c8014af0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x7fd8c4c21150>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 701](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel/kernelapp.py#line=700), in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x7fd8c80155a0>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fd8c8046b00>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x7fd8c4c21150>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 195](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/tornado/platform/asyncio.py#line=194), in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x7fd8c6234dc0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fd8c8046b00>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/asyncio/base_events.py", line 603](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/asyncio/base_events.py#line=602), in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7fd8c62368c0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/asyncio/base_events.py", line 1909](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/asyncio/base_events.py#line=1908), in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7fd8c61e1bd0>
    └ <Handle Task.task_wakeup(<Future finis...e50>, ...],))>)>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/asyncio/events.py", line 80](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/asyncio/events.py#line=79), in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finis...e50>, ...],))>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finis...e50>, ...],))>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finis...e50>, ...],))>)>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel/kernelbase.py#line=533), in dispatch_queue
    await self.process_one()
          │    └ <function Kernel.process_one at 0x7fd8c79e85e0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x7fd8c8047100>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 523](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel/kernelbase.py#line=522), in process_one
    await dispatch(*args)
          │         └ ([<zmq.sugar.frame.Frame object at 0x7fd8cde3e820>, <zmq.sugar.frame.Frame object at 0x7fd8cde3fe20>, <zmq.sugar.frame.Frame ...
          └ <bound method Kernel.dispatch_shell of <ipykernel.ipkernel.IPythonKernel object at 0x7fd8c8047100>>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 429](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel/kernelbase.py#line=428), in dispatch_shell
    await result
          └ <coroutine object Kernel.execute_request at 0x7fd8cde9edc0>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 767](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel/kernelbase.py#line=766), in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x7fd8cddebae0>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 429](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel/ipkernel.py#line=428), in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x7fd8c7ff63b0>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7fd8c80475b0>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/ipykernel/zmqshell.py#line=548), in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': 'b3d9eb6a-9a32-4f7e-8922-aff3c5e4a314'}
                             └ ("gen_md('demo1.pdf')",)
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3075](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/IPython/core/interactiveshell.py#line=3074), in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x7fd8c7046dd0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7fd8c80475b0>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3130](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/IPython/core/interactiveshell.py#line=3129), in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x7fd8cddeb990>
             └ <function _pseudo_sync_runner at 0x7fd8c702a710>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/IPython/core/async_helpers.py#line=128), in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x7fd8cddeb990>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3334](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/IPython/core/interactiveshell.py#line=3333), in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '[/var/folders/lw/mt_gxt9143zgcck9x_tsm2240000gn/T/ipykernel_88890/2769732803.py](http://localhost:8888/var/folders/lw/mt_gxt9143zgcck9x_tsm2240000gn/T/ipykernel_88890/2769732803.py)'
                       │    │             │        └ [<ast.Expr object at 0x7fd8c84b17b0>]
                       │    │             └ <ast.Module object at 0x7fd8c84b1b40>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x7fd8c70470a0>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7fd8c80475b0>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3517](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/IPython/core/interactiveshell.py#line=3516), in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 7fd8c84b1720, execution_count=6 error_before_exec=None error_in_exec=None info=<ExecutionInfo obje...
             │    │        └ <code object <module> at 0x7fd8cde55dc0, file "[/var/folders/lw/mt_gxt9143zgcck9x_tsm2240000gn/T/ipykernel_88890/2769732803.py...](http://localhost:8888/var/folders/lw/mt_gxt9143zgcck9x_tsm2240000gn/T/ipykernel_88890/2769732803.py...)
             │    └ <function InteractiveShell.run_code at 0x7fd8c7047130>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7fd8c80475b0>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/IPython/core/interactiveshell.py#line=3576), in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ {'__name__': '__main__', '__doc__': 'Automatically created module for IPython interactive environment', '__package__': None, ...
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7fd8c80475b0>
         │         │    └ <property object at 0x7fd8c702e7f0>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7fd8c80475b0>
         └ <code object <module> at 0x7fd8cde55dc0, file "[/var/folders/lw/mt_gxt9143zgcck9x_tsm2240000gn/T/ipykernel_88890/2769732803.py...](http://localhost:8888/var/folders/lw/mt_gxt9143zgcck9x_tsm2240000gn/T/ipykernel_88890/2769732803.py...)

  File "[/var/folders/lw/mt_gxt9143zgcck9x_tsm2240000gn/T/ipykernel_88890/2769732803.py", line 1](http://localhost:8888/var/folders/lw/mt_gxt9143zgcck9x_tsm2240000gn/T/ipykernel_88890/2769732803.py#line=0), in <module>
    gen_md('demo1.pdf')
    └ <function gen_md at 0x7fd8c84cd360>

  File "[/var/folders/lw/mt_gxt9143zgcck9x_tsm2240000gn/T/ipykernel_88890/2159648948.py", line 16](http://localhost:8888/var/folders/lw/mt_gxt9143zgcck9x_tsm2240000gn/T/ipykernel_88890/2159648948.py#line=15), in gen_md
    pipe.pipe_parse()
    │    └ <function UNIPipe.pipe_parse at 0x7fd8cde40e50>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fd8cc3bf430>

  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 35](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py#line=34), in pipe_parse
    self.pdf_mid_data = parse_union_pdf(self.pdf_bytes, self.model_list, self.image_writer,
    │    │              │               │    │          │    │           │    └ <magic_pdf.rw.DiskReaderWriter.DiskReaderWriter object at 0x7fd8c855a9e0>
    │    │              │               │    │          │    │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fd8cc3bf430>
    │    │              │               │    │          │    └ []
    │    │              │               │    │          └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fd8cc3bf430>
    │    │              │               │    └ b'%PDF-1.3\n%\xe4\xe3\xcf\xd2\n76 0 obj\n<<\n[/Linearized](http://localhost:8888/Linearized) 1.0\n[/O](http://localhost:8888/O) 78\n[/H](http://localhost:8888/H) [ 1149 392 ]\n[/L](http://localhost:8888/L) 391252\n[/E](http://localhost:8888/E) 87074\n[/N](http://localhost:8888/N) 11\n[/T](http://localhost:8888/T) 389688\n...
    │    │              │               └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fd8cc3bf430>
    │    │              └ <function parse_union_pdf at 0x7fd8cde40c10>
    │    └ None
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7fd8cc3bf430>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/user_api.py", line 88](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/user_api.py#line=87), in parse_union_pdf
    pdf_info_dict = parse_pdf(parse_pdf_by_txt)
                    │         └ <function parse_pdf_by_txt at 0x7fd8cde40af0>
                    └ <function parse_union_pdf.<locals>.parse_pdf at 0x7fd8c84cd240>
> File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/user_api.py", line 77](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/user_api.py#line=76), in parse_pdf
    return method(
           └ <function parse_pdf_by_txt at 0x7fd8cde40af0>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/pdf_parse_by_txt.py", line 12](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/pdf_parse_by_txt.py#line=11), in parse_pdf_by_txt
    return pdf_parse_union(pdf_bytes,
           │               └ b'%PDF-1.3\n%\xe4\xe3\xcf\xd2\n76 0 obj\n<<\n[/Linearized](http://localhost:8888/Linearized) 1.0\n[/O](http://localhost:8888/O) 78\n[/H](http://localhost:8888/H) [ 1149 392 ]\n[/L](http://localhost:8888/L) 391252\n[/E](http://localhost:8888/E) 87074\n[/N](http://localhost:8888/N) 11\n[/T](http://localhost:8888/T) 389688\n...
           └ <function pdf_parse_union at 0x7fd8cde40940>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core.py", line 225](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core.py#line=224), in pdf_parse_union
    page_info = parse_page_core(pdf_docs, magic_model, page_id, pdf_bytes_md5, imageWriter, parse_mode)
                │               │         │            │        │              │            └ 'txt'
                │               │         │            │        │              └ <magic_pdf.rw.DiskReaderWriter.DiskReaderWriter object at 0x7fd8c855a9e0>
                │               │         │            │        └ '3DDDBCDE75F2248F9AB9BC8E266EE16E'
                │               │         │            └ 0
                │               │         └ <magic_pdf.model.magic_model.MagicModel object at 0x7fd8cde1b9d0>
                │               └ Document('', <memory, doc# 4>)
                └ <function parse_page_core at 0x7fd8cde408b0>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core.py", line 83](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core.py#line=82), in parse_page_core
    img_blocks = magic_model.get_imgs(page_id)
                 │           │        └ 0
                 │           └ <function MagicModel.get_imgs at 0x7fd8cc416e60>
                 └ <magic_pdf.model.magic_model.MagicModel object at 0x7fd8cde1b9d0>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/model/magic_model.py", line 459](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/model/magic_model.py#line=458), in get_imgs
    records, _ = self.__tie_up_category_by_distance(page_no, 3, 4)
                 │                                  └ 0
                 └ <magic_pdf.model.magic_model.MagicModel object at 0x7fd8cde1b9d0>
  File "[/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/model/magic_model.py", line 186](http://localhost:8888/opt/anaconda3/envs/mineru/lib/python3.10/site-packages/magic_pdf/model/magic_model.py#line=185), in __tie_up_category_by_distance
    self.__model_list[page_no]["layout_dets"],
    │                 └ 0
    └ <magic_pdf.model.magic_model.MagicModel object at 0x7fd8cde1b9d0>

IndexError: list index out of range
2024-07-17 23:38:43.019 | WARNING  | magic_pdf.user_api:parse_union_pdf:90 - parse_pdf_by_txt drop or error, switch to parse_pdf_by_ocr
```

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
看到是今天晚上刚合进去的代码在解析时未能对边界进行有效检查导致文本型解析逻辑失败，系统兜底使用ocr进行了解析，稍晚会把情况反映给开发同事进行修复。

**Comment by myhloli** [comment]
和 https://github.com/opendatalab/MinerU/issues/163 是同一个问题，这个先关闭了
