### ISSUE TITLE
pymupdf.mupdf.FzErrorFormat: code=7: object out of range (0 0 R); xref size 161

### ISSUE THREAD

**Issue by shutter-cp** [opendatalab/MinerU#167]
### Description of the bug | 错误描述

```
Traceback (most recent call last):
  File "/root/miniconda3/envs/MinerU/bin/magic-pdf", line 8, in <module>
    sys.exit(cli())
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 325, in pdf_command
    do_parse(
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 120, in do_parse
    draw_layout_bbox(pdf_info, pdf_bytes, local_md_dir)
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/libs/draw_bbox.py", line 142, in draw_layout_bbox
    pdf_docs.save(f"{out_path}/layout.pdf")
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/pymupdf/__init__.py", line 5444, in save
    mupdf.pdf_save_document(pdf, filename, opts)
  File "/root/miniconda3/envs/MinerU/lib/python3.10/site-packages/pymupdf/mupdf.py", line 50563, in pdf_save_document
    return _mupdf.pdf_save_document(doc, filename, opts)
pymupdf.mupdf.FzErrorFormat: code=7: object out of range (0 0 R); xref size 161
(MinerU) [root@n01v PDF-Extract]# magic-pdf --version
magic-pdf, version 0.6.1
```

### How to reproduce the bug | 如何复现

```
magic-pdf pdf-command --pdf ./test2.pdf --inside_model true
```

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
可能是pdf文件本身的问题导致依赖库pymupdf在保存可视化文件时发生错误，能上传一份报错的pdf文件用来测试吗？

**Comment by shutter-cp** [comment]
[test2.pdf](https://github.com/user-attachments/files/16281700/test2.pdf)

**Comment by myhloli** [comment]
> [test2.pdf](https://github.com/user-attachments/files/16281700/test2.pdf)

复测，确认是由于pdf文档特殊导致pymupdf库再写出文件时导致了异常，markdown解析倒是没有问题，如果需要临时缓解此case类似情况，可以参考 https://github.com/opendatalab/MinerU/blob/master/demo/demo.py 通过api方式进行解析。
付解析结果：
[test2.zip](https://github.com/user-attachments/files/16281912/test2.zip)


如果在使用过程中还有其他问题，可以继续反馈。
