### ISSUE TITLE
 除零错误 float division by zero

### ISSUE THREAD

**Issue by Lincyaw** [opendatalab/MinerU#197]
### Description of the bug | 错误描述

输入文件后出现除零错误

```
2024-07-23 13:27:16.527 | INFO     | magic_pdf.model.pdf_extract_kit:__call__:165 - formula nums: 0, mfr time: 0.0
2024-07-23 13:27:16.527 | INFO     | magic_pdf.model.doc_analyze_by_custom_model:doc_analyze:116 - doc analyze cost: 21.667120456695557
2024-07-23 13:27:16.915 | ERROR    | magic_pdf.user_api:parse_pdf:85 - float division by zero
Traceback (most recent call last):

  File "/code/main.py", line 57, in <module>
    process_pdf_files_in_directory(directory_path)
    │                              └ 'papers'
    └ <function process_pdf_files_in_directory at 0x74fa505b36d0>

  File "/code/main.py", line 49, in process_pdf_files_in_directory
    process_pdf_file(directory, pdf_file)
    │                │          └ '13.pdf'
    │                └ 'papers'
    └ <function process_pdf_file at 0x74fa5081fd90>

  File "/code/main.py", line 36, in process_pdf_file
    pipe.pipe_parse()
    │    └ <function UNIPipe.pipe_parse at 0x74f9ccb7e3b0>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x74fa4e18fb80>

  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf-0.6.1-py3.10.egg/magic_pdf/pipe/UNIPipe.py", line 35, in pipe_parse
    self.pdf_mid_data = parse_union_pdf(self.pdf_bytes, self.model_list, self.image_writer,
    │    │              │               │    │          │    │           │    └ <magic_pdf.rw.DiskReaderWriter.DiskReaderWriter object at 0x74fa50757c70>
    │    │              │               │    │          │    │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x74fa4e18fb80>
    │    │              │               │    │          │    └ [{'layout_dets': [{'category_id': 2, 'poly': [147.7293243408203, 1720.90625, 819.2872924804688, 1720.90625, 819.287292
    │    │              │               │    │          └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x74fa4e18fb80>
    │    │              │               │    └ b'%PDF-1.5\n%\xe2\xe3\xcf\xd3\n1 0 obj\n<</ColorSpace/DeviceGray/Subtype/Image/Height 1004/Filter/FlateDecode/Type/XObject/Wi...
    │    │              │               └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x74fa4e18fb80>
    │    │              └ <function parse_union_pdf at 0x74f9ccb7e170>
    │    └ None
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x74fa4e18fb80>
  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf-0.6.1-py3.10.egg/magic_pdf/user_api.py", line 88, in parse_union_pdf
    pdf_info_dict = parse_pdf(parse_pdf_by_txt)
                    │         └ <function parse_pdf_by_txt at 0x74f9ccb7e050>
                    └ <function parse_union_pdf.<locals>.parse_pdf at 0x74f8cbf3e050>
> File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf-0.6.1-py3.10.egg/magic_pdf/user_api.py", line 77, in parse_pdf
    return method(
           └ <function parse_pdf_by_txt at 0x74f9ccb7e050>
  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf-0.6.1-py3.10.egg/magic_pdf/pdf_parse_by_txt.py", line 12, in parse_pdf_by_txt
    return pdf_parse_union(pdf_bytes,
           │               └ b'%PDF-1.5\n%\xe2\xe3\xcf\xd3\n1 0 obj\n<</ColorSpace/DeviceGray/Subtype/Image/Height 1004/Filter/FlateDecode/Type/XObject/Wi...
           └ <function pdf_parse_union at 0x74f9ccb7dfc0>
  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf-0.6.1-py3.10.egg/magic_pdf/pdf_parse_union_core.py", line 225, in pdf_parse_union
    page_info = parse_page_core(pdf_docs, magic_model, page_id, pdf_bytes_md5, imageWriter, parse_mode)
                │               │         │            │        │              │            └ 'txt'
                │               │         │            │        │              └ <magic_pdf.rw.DiskReaderWriter.DiskReaderWriter object at 0x74fa50757c70>
                │               │         │            │        └ '190DE130B4E15C2DD775EA2A0297C11C'
                │               │         │            └ 2
                │               │         └ <magic_pdf.model.magic_model.MagicModel object at 0x74f8d5c20910>
                │               └ Document('', <memory, doc# 5>)
                └ <function parse_page_core at 0x74f9ccb7df30>
  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf-0.6.1-py3.10.egg/magic_pdf/pdf_parse_union_core.py", line 97, in parse_page_core
    pymu_spans = txt_spans_extract(
                 └ <function txt_spans_extract at 0x74f9ccb7db40>
  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf-0.6.1-py3.10.egg/magic_pdf/pdf_parse_union_core.py", line 53, in txt_spans_extract
    text_blocks = remove_citation_marker(text_blocks)
                  │                      └ [{'number': 0, 'type': 0, 'bbox': (53.79800033569336, 61.119380950927734, 558.1991577148438, 69.2159652709961), 'lines': [{'s...
                  └ <function remove_citation_marker at 0x74f9ccb5b520>
  File "/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf-0.6.1-py3.10.egg/magic_pdf/pre_proc/citationmarker_remove.py", line 139, in remove_citation_marker
    if (base_span_mid_y-span_mid_y)/span_hi>0.2 or (base_span_mid_y-span_mid_y>0 and abs(span_font_sz-min_font_sz)/min_font_sz<0.1):
        │               │           │               │               │                    │            │            └ 3.700600075262628e-07
        │               │           │               │               │                    │            └ 3.700600075262628e-07
        │               │           │               │               │                    └ 3.700600075262628e-07
        │               │           │               │               └ 153.45814514160156
        │               │           │               └ 151.14015197753906
        │               │           └ 0.0
        │               └ 153.45814514160156
        └ 151.14015197753906

ZeroDivisionError: float division by zero
2024-07-23 13:27:17.003 | WARNING  | magic_pdf.user_api:parse_union_pdf:90 - parse_pdf_by_txt drop or error, switch to parse_pdf_by_ocr
2024-07-23 13:27:17.007 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:93 - DocAnalysis init, this may take some times. apply_layout: True, apply_formula: True, apply_ocr: Tr
2024-07-23 13:27:17.007 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:101 - using device: cuda
CustomVisionEncoderDecoderModel init
CustomMBartForCausalLM init
CustomMBartDecoder init
[07/23 13:27:22 detectron2]: Rank of current process: 0. World size: 1
[07/23 13:27:22 detectron2]: Environment info:
-------------------------------  -----------------------------------------------------------------------
sys.platform                     linux
Python                           3.10.14 (main, Apr 27 2024, 21:17:55) [GCC 13.2.0]
numpy                            1.26.4
detectron2                       0.6 @/opt/mineru_venv/lib/python3.10/site-packages/detectron2
Compiler                         GCC 11.4
CUDA compiler                    not available
DETECTRON2_ENV_MODULE            <not set>
PyTorch                          2.3.1+cu121 @/opt/mineru_venv/lib/python3.10/site-packages/torch
PyTorch debug build              False
torch._C._GLIBCXX_USE_CXX11_ABI  False
GPU available                    Yes
GPU 0                            NVIDIA GeForce RTX 4060 (arch=8.9)
Driver version                   535.183.01
CUDA_HOME                        None - invalid!
Pillow                           10.4.0
torchvision                      0.18.1+cu121 @/opt/mineru_venv/lib/python3.10/site-packages/torchvision
torchvision arch flags           /opt/mineru_venv/lib/python3.10/site-packages/torchvision/_C.so
fvcore                           0.1.5.post20221221
iopath                           0.1.9
cv2                              4.6.0
-------------------------------  -----------------------------------------------------------------------
PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.6 (Git Hash 86e6af5974177e513fd3fee58425e1063e7f1361)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.3.1, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,

[07/23 13:27:22 detectron2]: Command line arguments: {'config_file': '/opt/mineru_venv/lib/python3.10/site-packages/magic_pdf-0.6.1-py3.10.egg/magic_pdf/resources/model_config/layoutlmv3/layoutlmv3_base_inference.yaml', 'resume': False, 'eval_only': False, 'num_gpus': 1, 'num_machines': 1, 'machine_rank': 0, 'dist_url': 'tcp://127.0.0.1:57823', 'opts': ['MODEL.WEIGHTS', '/opt/models/Layout/model_final.pth']}



[07/23 13:27:23 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from /opt/models/Layout/model_final.pth ...
[07/23 13:27:23 fvcore.common.checkpoint]: [Checkpointer] Loading from /opt/models/Layout/model_final.pth ...


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::framework::ir::SelfAttentionFusePass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::framework::ir::GraphPatternDetector::operator()(paddle::framework::ir::Graph*, std::function<void (std::map<paddle::framework::ir::PDNode*, paddle::framework::ir::Node*, paddle::framework::ir::GraphPatternDetector::PDNodeCompare, std::allocator<std::pair<paddle::framework::ir::PDNode* const, paddle::framework::ir::Node*> > > const&, paddle::framework::ir::Graph*)>)

----------------------
Error Message Summary:
----------------------
FatalError: `Illegal instruction` is detected by the operating system.
  [TimeInfo: *** Aborted at 1721741243 (unix time) try "date -d @1721741243" if you are using GNU date ***]
  [SignalInfo: *** SIGILL (@0x74f90385a13a) received by PID 1781 (TID 0x74fa5091a080) from PID 59089210 ***]

Illegal instruction (core dumped)
```

### How to reproduce the bug | 如何复现

稍微改了一下示例代码，使用附件里的这个 13.pdf，执行的时候会出现除零错误。 环境是 docker，cuda。Dockerfile 使用的是 https://github.com/Lincyaw/MinerU/blob/master/Dockerfile  。 其中，我自行替换了最新版本（本地编译安装的）

[13.pdf](https://github.com/user-attachments/files/16349531/13.pdf)

```
import os
import json
from loguru import logger
from magic_pdf.pipe.UNIPipe import UNIPipe

from magic_pdf.rw.DiskReaderWriter import DiskReaderWriter
import magic_pdf.model as model_config
import os

model_config.__use_inside_model__ = True

def process_pdf_file(directory, pdf_file):
    demo_name = os.path.splitext(pdf_file)[0]
    pdf_path = os.path.join(directory, pdf_file)
    model_path = os.path.join(directory, f"{demo_name}.json")
    
    try:
        with open(pdf_path, "rb") as f:
            pdf_bytes = f.read()
        
        model_json = []  # 使用内置模型解析
        jso_useful_key = {"_pdf_type": "", "model_list": model_json}
        local_image_dir = os.path.join(directory, 'images')
        os.makedirs(local_image_dir, exist_ok=True)
        image_dir = str(os.path.basename(local_image_dir))
        image_writer = DiskReaderWriter(local_image_dir)
        pipe = UNIPipe(pdf_bytes, jso_useful_key, image_writer)
        
        pipe.pipe_classify()
        if len(model_json) == 0:
            if model_config.__use_inside_model__:
                pipe.pipe_analyze()
            else:
                logger.error("Need model list input")
                return
        
        pipe.pipe_parse()
        md_content = pipe.pipe_mk_markdown(image_dir, drop_mode="none")
        with open(os.path.join(f"/output", f"{demo_name}.md"), "w", encoding="utf-8") as f:
            f.write(md_content)
        
        logger.info(f"Processed '{pdf_file}' and generated '{demo_name}.md'")
    except Exception as e:
        logger.exception(f"Failed to process {pdf_file}: {e}")

def process_pdf_files_in_directory(directory):
    pdf_files = sorted([f for f in os.listdir(directory) if f.lower().endswith('.pdf')])
    for pdf_file in pdf_files:
        if pdf_file == "13.pdf":
            process_pdf_file(directory, pdf_file)
            break

if __name__ == "__main__":
    directory_path = "papers"
    if not os.path.isdir(directory_path):
        print(f"Directory '{directory_path}' does not exist.")
    else:
        process_pdf_files_in_directory(directory_path)
```

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
fix done. https://github.com/opendatalab/MinerU/commit/8411c91029a4b915ff36c460dcc89b7a8f0f34c9
