### ISSUE TITLE
您好，windows下配置完模型地址后提示无法找到文件

### ISSUE THREAD

**Issue by JokerHYC** [opendatalab/MinerU#207]
### Description of the bug | 错误描述

{
    "bucket_info":{
        "bucket-name-1":["ak", "sk", "endpoint"],
        "bucket-name-2":["ak", "sk", "endpoint"]
    },
    "temp-output-dir":"M:/linux/PDF-Extract",
    "models-dir":"M:/linux/PDF-Extract-Kit",
    "device-mode":"cpu"
}
配置文件如上

### How to reproduce the bug | 如何复现

错误日志如下

(minerU) C:\Users\joker>magic-pdf pdf-command --pdf "M:\1.pdf" --inside_model true
2024-07-25 00:19:05.813 | WARNING  | magic_pdf.cli.magicpdf:get_model_json:310 - not found json M:\1.json existed
2024-07-25 00:19:05.813 | INFO     | magic_pdf.cli.magicpdf:do_parse:91 - local output dir is M:/linux/PDF-Extract\magic-pdf\1\auto
2024-07-25 00:19:06.389 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 0, text_len: 14461, cid_chars_radio: 0.0
2024-07-25 00:19:14.274 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:92 - DocAnalysis init, this may take some times. apply_layout: True, apply_formula: True, apply_ocr: False
2024-07-25 00:19:14.274 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:100 - using device: cpu
Traceback (most recent call last):
  File "C:\Users\joker\anaconda3\envs\minerU\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\joker\anaconda3\envs\minerU\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\joker\anaconda3\envs\minerU\Scripts\magic-pdf.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\magic_pdf\cli\magicpdf.py", line 325, in pdf_command
    do_parse(
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\magic_pdf\cli\magicpdf.py", line 111, in do_parse
    pipe.pipe_analyze()
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\magic_pdf\pipe\UNIPipe.py", line 29, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=False)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line 69, in doc_analyze
    custom_model = CustomPEKModel(ocr=ocr, show_log=show_log, models_dir=local_models_dir, device=device)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\magic_pdf\model\pdf_extract_kit.py", line 106, in __init__
    self.mfd_model = mfd_model_init(str(os.path.join(models_dir, self.configs["weights"]["mfd"])))
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\magic_pdf\model\pdf_extract_kit.py", line 29, in mfd_model_init
    mfd_model = YOLO(weight)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\ultralytics\engine\model.py", line 141, in __init__
    self._load(model, task=task)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\ultralytics\engine\model.py", line 293, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\ultralytics\nn\tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\ultralytics\nn\tasks.py", line 781, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\ultralytics\utils\patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\torch\serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\torch\serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\torch\serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'M:\\linux\\PDF-Extract-Kit\\MFD\\weights.pt'

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by JokerHYC** [comment]
错误日志中最后的是
`FileNotFoundError: [Errno 2] No such file or directory: 'M:\\linux\\PDF-Extract-Kit\\MFD\\weights.pt'`

**Comment by JokerHYC** [comment]
`(minerU) C:\Users\joker>magic-pdf pdf-command --pdf "M:\1.pdf" --inside_model true
2024-07-25 00:19:05.813 | WARNING  | magic_pdf.cli.magicpdf:get_model_json:310 - not found json M:\1.json existed
2024-07-25 00:19:05.813 | INFO     | magic_pdf.cli.magicpdf:do_parse:91 - local output dir is M:/linux/PDF-Extract\magic-pdf\1\auto
2024-07-25 00:19:06.389 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 0, text_len: 14461, cid_chars_radio: 0.0
2024-07-25 00:19:14.274 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:92 - DocAnalysis init, this may take some times. apply_layout: True, apply_formula: True, apply_ocr: False
2024-07-25 00:19:14.274 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:100 - using device: cpu
Traceback (most recent call last):
  File "C:\Users\joker\anaconda3\envs\minerU\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\joker\anaconda3\envs\minerU\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\joker\anaconda3\envs\minerU\Scripts\magic-pdf.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\magic_pdf\cli\magicpdf.py", line 325, in pdf_command
    do_parse(
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\magic_pdf\cli\magicpdf.py", line 111, in do_parse
    pipe.pipe_analyze()
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\magic_pdf\pipe\UNIPipe.py", line 29, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=False)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line 69, in doc_analyze
    custom_model = CustomPEKModel(ocr=ocr, show_log=show_log, models_dir=local_models_dir, device=device)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\magic_pdf\model\pdf_extract_kit.py", line 106, in __init__
    self.mfd_model = mfd_model_init(str(os.path.join(models_dir, self.configs["weights"]["mfd"])))
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\magic_pdf\model\pdf_extract_kit.py", line 29, in mfd_model_init
    mfd_model = YOLO(weight)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\ultralytics\engine\model.py", line 141, in __init__
    self._load(model, task=task)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\ultralytics\engine\model.py", line 293, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\ultralytics\nn\tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\ultralytics\nn\tasks.py", line 781, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\ultralytics\utils\patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\torch\serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\torch\serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\joker\anaconda3\envs\minerU\lib\site-packages\torch\serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'M:\\linux\\PDF-Extract-Kit\\MFD\\weights.pt'`

**Comment by myhloli** [comment]
模型路径配置有误，是不是中间少了一层models

**Comment by JokerHYC** [comment]
"models-dir":"M:/linux/PDF-Extract-Kit",
![图片](https://github.com/user-attachments/assets/0cfbd662-d0b4-4fdb-a3b2-614d65d76671)

您好，我模型路径是按教程写的来的，是直接git clone下来的文件夹。

**Comment by JokerHYC** [comment]
是我的问题，模型需要配置到clone来来的文件夹的下层models 

{
    "bucket_info":{
        "bucket-name-1":["ak", "sk", "endpoint"],
        "bucket-name-2":["ak", "sk", "endpoint"]
    },
    "temp-output-dir":"M:/linux/PDF-Extract",
    "models-dir":"M:/linux/PDF-Extract-Kit/models",
    "device-mode":"cpu"
}

目前已经正常运行。
