### ISSUE TITLE
WinError 127 本地使用弹出错误“无法找到程序入口”

### ISSUE THREAD

**Issue by jn-jia** [opendatalab/MinerU#230]
### Description of the bug | 错误描述

输入命令：magic-pdf pdf-command --pdf "Rise.pdf" --inside_model true
弹出窗口：python.exe - 无法找到入口
![image](https://github.com/user-attachments/assets/863e417e-23a9-453b-9ab3-ba9c3d8605d5)
错误输出如下：
2024-07-28 23:02:54.761 | WARNING  | magic_pdf.cli.magicpdf:get_model_json:310 - not found json C:/Users/PC-Jia/Desktop/Rise.json existed
2024-07-28 23:02:54.762 | INFO     | magic_pdf.cli.magicpdf:do_parse:91 - local output dir is C:/Users/PC-Jia/Desktop/pdf_parse\magic-pdf\Rise\auto
2024-07-28 23:02:55.557 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 13, text_len: 39317, cid_chars_radio: 0.000331421287444232
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\anaconda3\envs\env_py310\Scripts\magic-pdf.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\magic_pdf\cli\magicpdf.py", line 325, in pdf_command
    do_parse(
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\magic_pdf\cli\magicpdf.py", line 111, in do_parse
    pipe.pipe_analyze()
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\magic_pdf\pipe\UNIPipe.py", line 29, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=False)
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line 65, in doc_analyze
    from magic_pdf.model.pdf_extract_kit import CustomPEKModel
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\magic_pdf\model\pdf_extract_kit.py", line 16, in <module>
    from unimernet.common.config import Config
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\unimernet\__init__.py", line 18, in <module>
    from unimernet.tasks import *
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\unimernet\tasks\__init__.py", line 10, in <module>
    from unimernet.tasks.unimernet_train import UniMERNet_Train
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\unimernet\tasks\unimernet_train.py", line 11, in <module>
    from torchtext.data import metrics
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\torchtext\__init__.py", line 18, in <module>
    from torchtext import _extension  # noqa: F401
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\torchtext\_extension.py", line 64, in <module>
    _init_extension()
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\torchtext\_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\torchtext\_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\site-packages\torch\_ops.py", line 1295, in load_library
    ctypes.CDLL(path)
  File "D:\ProgramData\anaconda3\envs\env_py310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] 找不到指定的程序。

### How to reproduce the bug | 如何复现

对于Magic-PDF，严格按照“安装配置”步骤，没有出现问题（包括直接使用pytorch官网的conda命令，安装了2.4.0的pytorch，对应于CUDA 12.1）。

只是在调用命令行时，出现了上述错误。

环境：
windows 11 64位
python版本 3.10.14

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
>TorchText development is stopped and the 0.18 release (April 2024) will be the last stable release of the library.

The versions of torch, torchvision, and torchtext need to be compatible. but torchtext 0.18.0 not compatibility of torch 2.4.0
maybe you can 
```bash
pip install --force-reinstall torch==2.3.1 torchvision==0.18.1
```

**Comment by jn-jia** [comment]
Thank you for your timely reply. I just looked into this issue (https://github.com/pytorch/text) and am now switching to PyTorch 2.3.0.

**Comment by jn-jia** [comment]
Yes, it's confirmed that the issue is due to the incompatibility between PyTorch 2.4.0 and torchtext 0.18.0. Using PyTorch 2.3.1 can resolve the problem. Thanks！
