### ISSUE TITLE
magic-pdf pdf-command --pdf "/root/Changhong_V1.1.pdf" --inside_model true

### ISSUE THREAD

**Issue by jiaguangqi** [opendatalab/MinerU#257]
### Description of the bug | 错误描述

2024-07-31 14:03:58.049 | WARNING  | magic_pdf.cli.magicpdf:get_model_json:310 - not found json /root/Changhong_ES7990_V1.1.json existed
2024-07-31 14:03:58.049 | INFO     | magic_pdf.cli.magicpdf:do_parse:91 - local output dir is /tmp/magic-pdf/Changhong_ES7990_V1.1/auto
2024-07-31 14:03:59.094 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 0, text_len: 7653, cid_chars_radio: 0.0
2024-07-31 14:04:05.093 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:92 - DocAnalysis init, this may take some times. apply_layout: True, apply_formula: True, apply_ocr: False
2024-07-31 14:04:05.094 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:100 - using device: cuda
Traceback (most recent call last):
  File "/home/apps/anaconda3/envs/pdf/bin/magic-pdf", line 8, in <module>
    sys.exit(cli())
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 325, in pdf_command
    do_parse(
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 111, in do_parse
    pipe.pipe_analyze()
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 29, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=False)
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 69, in doc_analyze
    custom_model = CustomPEKModel(ocr=ocr, show_log=show_log, models_dir=local_models_dir, device=device)
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/magic_pdf/model/pdf_extract_kit.py", line 106, in __init__
    self.mfd_model = mfd_model_init(str(os.path.join(models_dir, self.configs["weights"]["mfd"])))
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/magic_pdf/model/pdf_extract_kit.py", line 29, in mfd_model_init
    mfd_model = YOLO(weight)
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/ultralytics/engine/model.py", line 142, in __init__
    self._load(model, task=task)
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/ultralytics/engine/model.py", line 294, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 781, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/ultralytics/utils/patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/apps/anaconda3/envs/pdf/lib/python3.10/site-packages/torch/serialization.py", line 1262, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

### How to reproduce the bug | 如何复现

运行就会报错，不知道原因在哪
CPU版和GPU版本都测试过，一样的报错

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
检查一下已下载模型文件的大小和网页上是否一致，这个问题一般是下载过程中模型文件损坏导致的。

**Comment by jiaguangqi** [comment]
谢谢，重新下载了模型文件后，现在可以正常完成了

**Comment by wanglf1979** [comment]
> 谢谢，重新下载了模型文件后，现在可以正常完成了

哪儿下载的模型？？我用的清华的源，不行。readme里推荐的那个源太慢了。

> 检查一下已下载模型文件的大小和网页上是否一致，这个问题一般是下载过程中模型文件损坏导致的。

https://www.modelscope.cn/wanderkid/PDF-Extract-Kit
我从这儿用git下载了一个，也是不行。您是从那个源下的？？

**Comment by jiaguangqi** [comment]
https://www.modelscope.cn/models/wanderkid/PDF-Extract-Kit/files

**Comment by jiaguangqi** [comment]
https://www.modelscope.cn/models/wanderkid/PDF-Extract-Kit/files
![Uploading 11111.png…]()
