### ISSUE TITLE
已在/tmp文件下解压缩fasttext-langdetect但是依旧报错网络错误_ssl.c:1007

### ISSUE THREAD

**Issue by dengdengdengfei** [opendatalab/MinerU#269]
## 错误名称
urllib.error.URLError: <urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)>

##情况描述 

已按照issue解压缩文件至/tmp
版本为0.6.1
命令为:
magic-pdf pdf-command --pdf "/home/ollama/code/ghui/indexing/pdf/lpa/2018 A Report of the ACC - 正文译文.pdf" --inside_model true
报错

##全部log
~$ magic-pdf pdf-command --pdf "/home/ollama/code/ghui/indexing/pdf/lpa/2018 A Report of the ACC - 正文译文.pdf" --inside_modeuetrue

2024-07-31 13:06:13.731 | WARNING  | magic_pdf.cli.magicpdf:get_model_json:310 - not found json /home/ollama/code/ghui/indexing/pdf/lpa/2018 A Report of the ACC - 正文译文.json existed

2024-07-31 13:06:13.732 | INFO     | magic_pdf.cli.magicpdf:do_parse:91 - local output dir is /tmp/magic-pdf/2018 A Report of the ACC - 正文译文/auto

Traceback (most recent call last):
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/libs/language.py", line 9, in detect_lang
    lang_upper = detect_language(text)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/fast_langdetect/ft_detect/__init__.py", line 23, in detect_language
    lang_code = detect(sentence, low_memory=low_memory).get("lang").upper()
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/fast_langdetect/ft_detect/infer.py", line 80, in detect
    model = get_model_loaded(low_memory=low_memory, download_proxy=model_download_proxy)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/fast_langdetect/ft_detect/infer.py", line 70, in get_model_loaded
    download(url=url, folder=cache, filename=name, proxy=download_proxy, retry_max=3, timeout=20)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/robust_downloader/downloader.py", line 69, in download
    url = _get_redirect_url(url, max_hops=max_redirect_hops)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/robust_downloader/downloader.py", line 272, in _get_redirect_url
    with urllib.request.urlopen(
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ollama/anaconda3/envs/MinerU/bin/magic-pdf", line 8, in <module>
    sys.exit(cli())
  File "/home/ollama/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ollama/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ollama/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ollama/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ollama/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 325, in pdf_command
    do_parse(
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 106, in do_parse
    pipe.pipe_classify()
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 25, in pipe_classify
    self.pdf_type = AbsPipe.classify(self.pdf_bytes)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pipe/AbsPipe.py", line 63, in classify
    pdf_meta = pdf_meta_scan(pdf_bytes)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/filter/pdf_meta_scan.py", line 337, in pdf_meta_scan
    text_language = get_language(doc)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/filter/pdf_meta_scan.py", line 289, in get_language
    page_language = detect_lang(text_block)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/libs/language.py", line 12, in detect_lang
    lang_upper = detect_language(html_no_ctrl_chars)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/fast_langdetect/ft_detect/__init__.py", line 23, in detect_language
    lang_code = detect(sentence, low_memory=low_memory).get("lang").upper()
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/fast_langdetect/ft_detect/infer.py", line 80, in detect
    model = get_model_loaded(low_memory=low_memory, download_proxy=model_download_proxy)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/fast_langdetect/ft_detect/infer.py", line 70, in get_model_loaded
    download(url=url, folder=cache, filename=name, proxy=download_proxy, retry_max=3, timeout=20)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/robust_downloader/downloader.py", line 69, in download
    url = _get_redirect_url(url, max_hops=max_redirect_hops)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/site-packages/robust_downloader/downloader.py", line 272, in _get_redirect_url
    with urllib.request.urlopen(
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/ollama/anaconda3/envs/MinerU/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)>

### How to reproduce the bug | 如何复现

magic-pdf pdf-command --pdf "/home/ollama/code/ghui/indexing/pdf/lpa/2018 A Report of the ACC - 正文译文.pdf" --inside_model true

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
```bash
pip install magic-pdf[full]==0.6.2b1 -i https://mirrors.aliyun.com/pypi/simple/
```

update to 0.6.2 will help you solve this problem
