### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by CzLiu223** [opendatalab/MinerU#307]
### Description of the bug | 错误描述

按照README.md操作，出现以下报错，请问如何解决？
(MinerU) C:\Users\73276>magic-pdf pdf-command --pdf "C:/Users/73276/magic-pdf.pdf" --inside_model true
2024-08-02 23:34:45.652 | INFO     | magic_pdf.cli.magicpdf:do_parse:91 - local output dir is /tmp\magic-pdf\magic-pdf\auto
2024-08-02 23:34:47.138 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 0, text_len: 8038, cid_chars_radio: 0.0
2024-08-02 23:34:47.138 | WARNING  | magic_pdf.filter.pdf_classify_by_type:classify:334 - pdf is not classified by area and text_len, by_image_area: False, by_text: True, by_avg_words: True, by_img_num: True, by_text_layout: True, by_img_narrow_strips: True, by_invalid_chars: True
Traceback (most recent call last):
  File "C:\Anaconda3\envs\MinerU\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Anaconda3\envs\MinerU\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\MinerU\Scripts\magic-pdf.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "C:\Anaconda3\envs\MinerU\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Anaconda3\envs\MinerU\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Anaconda3\envs\MinerU\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Anaconda3\envs\MinerU\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Anaconda3\envs\MinerU\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Anaconda3\envs\MinerU\lib\site-packages\magic_pdf\cli\magicpdf.py", line 325, in pdf_command
    do_parse(
  File "C:\Anaconda3\envs\MinerU\lib\site-packages\magic_pdf\cli\magicpdf.py", line 117, in do_parse
    pipe.pipe_parse()
  File "C:\Anaconda3\envs\MinerU\lib\site-packages\magic_pdf\pipe\UNIPipe.py", line 38, in pipe_parse
    self.pdf_mid_data = parse_ocr_pdf(self.pdf_bytes, self.model_list, self.image_writer,
  File "C:\Anaconda3\envs\MinerU\lib\site-packages\magic_pdf\user_api.py", line 53, in parse_ocr_pdf
    pdf_info_dict = parse_pdf_by_ocr(
  File "C:\Anaconda3\envs\MinerU\lib\site-packages\magic_pdf\pdf_parse_by_ocr.py", line 11, in parse_pdf_by_ocr
    return pdf_parse_union(pdf_bytes,
  File "C:\Anaconda3\envs\MinerU\lib\site-packages\magic_pdf\pdf_parse_union_core.py", line 206, in pdf_parse_union
    magic_model = MagicModel(model_list, pdf_docs)
  File "C:\Anaconda3\envs\MinerU\lib\site-packages\magic_pdf\model\magic_model.py", line 101, in __init__
    self.__fix_axis()
  File "C:\Anaconda3\envs\MinerU\lib\site-packages\magic_pdf\model\magic_model.py", line 34, in __fix_axis
    page_no = model_page_info["page_info"]["page_no"]
TypeError: string indices must be integers

### How to reproduce the bug | 如何复现

完全按照README.md操作，其中pytorch的安装步骤按照官网上的NOTE(https://pytorch.org/get-started/locally/#windows-prerequisites-2)设置为：
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
CUDA安装的版本为12.4。

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
你的问题是pdf同目录下有一个同名的magic-pdf.json，~~需要删掉这个json再运行~~如果是用户目录的magic-pdf.json是不能删的，最好把pdf文件改个名字，不要和目录下的json同名。但是我感觉你应该不止这一个问题，所以我建议你按照下面这个教程，从头到尾走一遍
https://github.com/opendatalab/MinerU/blob/master/docs/README_Windows_CUDA_Acceleration_zh_CN.md

有问题可以及时反馈

**Comment by CzLiu223** [comment]
> 你的问题是pdf同目录下有一个同名的magic-pdf.json，~需要删掉这个json再运行~如果是用户目录的magic-pdf.json是不能删的，最好把pdf文件改个名字，不要和目录下的json同名。但是我感觉你应该不止这一个问题，所以我建议你按照下面这个教程，从头到尾走一遍 https://github.com/opendatalab/MinerU/blob/master/docs/README_Windows_CUDA_Acceleration_zh_CN.md
> 
> 有问题可以及时反馈



> 你的问题是pdf同目录下有一个同名的magic-pdf.json，~需要删掉这个json再运行~如果是用户目录的magic-pdf.json是不能删的，最好把pdf文件改个名字，不要和目录下的json同名。但是我感觉你应该不止这一个问题，所以我建议你按照下面这个教程，从头到尾走一遍 https://github.com/opendatalab/MinerU/blob/master/docs/README_Windows_CUDA_Acceleration_zh_CN.md
> 
> 有问题可以及时反馈

OK多谢，我试试
