### ISSUE TITLE
Mac M1部署安装报错【已解决，同款可进】

### ISSUE THREAD

**Issue by samqin123** [opendatalab/MinerU#315]
### Description of the bug | 错误描述

1. 清华源报错
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/41a9aaf9-6b78-4542-8020-0299e42d0a6f"

2.pdf路径配置后，执行，无法生成文件.json文件。配置文件都提供，按照readme进行配置，mac M1，model放了绝对路径，配置了mps参数；
<img width="1760" alt="image" src="https://github.com/user-attachments/assets/85462257-97f6-48cb-86d8-a91dd7114557">

### How to reproduce the bug | 如何复现

1. 清华源报错
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/41a9aaf9-6b78-4542-8020-0299e42d0a6f"

2.pdf路径配置后，执行，无法生成文件.json文件。配置文件都提供，按照readme进行配置，mac M1，model放了绝对路径，配置了mps参数；
<img width="1760" alt="image" src="https://github.com/user-attachments/assets/85462257-97f6-48cb-86d8-a91dd7114557">

**magic-pdf.json配置** 
<img width="1258" alt="image" src="https://github.com/user-attachments/assets/4a12d1f4-9442-478d-a949-e4bc2fb9a4b2">

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

mps

**Comment by myhloli** [comment]
1.detectron2必须安装
```bash
pip install detectron2 --extra-index-url https://wheels.myhloli.com
```
如果以上命令安装失败，可以尝试在https://wheels.myhloli.com
手动下载适配自己设备的版本手动安装

2. detectron2安装后可通过以下命令安装0.6.2b1版本
```bash

pip install magic-pdf[full]==0.6.2b1
```
这样如果报错可以打印出详细堆栈信息，以便排查修复

**Comment by samqin123** [comment]
pip install magic-pdf==0.6.2b1 这个可以顺利安装，加上[full]不行，我已经指定了清华源，用readme的extra url也可以。

**Comment by samqin123** [comment]
执行命令：magic-pdf pdf-command --pdf "/Users/qinxiaoqiang/Downloads/MinerU-PDF/ga.pdf" --inside_model true

报错内容：
2024-08-04 16:38:34.524 | WARNING  | magic_pdf.cli.magicpdf:get_model_json:312 - not found json /Users/qinxiaoqiang/Downloads/MinerU-PDF/ga.json existed
2024-08-04 16:38:34.524 | WARNING  | magic_pdf.libs.config_reader:get_local_dir:64 - 'temp-output-dir' not found in magic-pdf.json, use '/tmp' as default
2024-08-04 16:38:35.993 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 0, text_len: 10, cid_chars_radio: 0.0
2024-08-04 16:38:35.996 | WARNING  | magic_pdf.filter.pdf_classify_by_type:classify:334 - pdf is not classified by area and text_len, by_image_area: True, by_text: False, by_avg_words: False, by_img_num: True, by_text_layout: False, by_img_narrow_strips: True, by_invalid_chars: True
2024-08-04 16:38:36.935 | ERROR    | magic_pdf.cli.magicpdf:parse_doc:338 - dlopen(/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so, 0x0006): Symbol not found: __ZN3c105ErrorC1ENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES7_PKv
  Referenced from: <8349B302-A1C9-3870-AB5A-21A14A352BC2> /opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so
  Expected in:     <69A84A04-EB16-3227-9FED-383D2FE98E93> /opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torch/lib/libc10.dylib
Traceback (most recent call last):

  File "/opt/miniconda3/envs/MinerU/bin/magic-pdf", line 8, in <module>
    sys.exit(cli())
    │   │    └ <Group cli>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x10164c670>
           └ <Group cli>
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x1011e2a40>
         │    └ <function MultiCommand.invoke at 0x10164d630>
         └ <Group cli>
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x168c0d7e0>
           │               │       │       └ <function Command.invoke at 0x10164d120>
           │               │       └ <Command pdf-command>
           │               └ <click.core.Context object at 0x168c0d7e0>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x1010e3d90>
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'pdf': '/Users/qinxiaoqiang/Downloads/MinerU-PDF/ga.pdf', 'inside_model': True, 'model': None, 'method': 'auto', 'model_mode...
           │   │      │    │           └ <click.core.Context object at 0x168c0d7e0>
           │   │      │    └ <function pdf_command at 0x168c25c60>
           │   │      └ <Command pdf-command>
           │   └ <function Context.invoke at 0x10162fe20>
           └ <click.core.Context object at 0x168c0d7e0>
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'pdf': '/Users/qinxiaoqiang/Downloads/MinerU-PDF/ga.pdf', 'inside_model': True, 'model': None, 'method': 'auto', 'model_mode...
                       └ ()
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 352, in pdf_command
    parse_doc(pdf)
    │         └ '/Users/qinxiaoqiang/Downloads/MinerU-PDF/ga.pdf'
    └ <function pdf_command.<locals>.parse_doc at 0x168c25990>
> File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 330, in parse_doc
    do_parse(
    └ <function do_parse at 0x168c255a0>
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 111, in do_parse
    pipe.pipe_analyze()
    │    └ <function UNIPipe.pipe_analyze at 0x168c241f0>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x168c0d3f0>
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 31, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=True)
    │    │            │           │    └ b'%PDF-1.5\r%\xe2\xe3\xcf\xd3\r\n2515 0 obj\r<</Linearized 1/L 6997002/O 2517/E 320192/N 17/T 6993824/H [ 885 565]>>\rendobj\...
    │    │            │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x168c0d3f0>
    │    │            └ <function doc_analyze at 0x10444c1f0>
    │    └ []
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x168c0d3f0>
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 103, in doc_analyze
    custom_model = model_manager.get_model(ocr, show_log)
                   │             │         │    └ False
                   │             │         └ True
                   │             └ <function ModelSingleton.get_model at 0x10444c160>
                   └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x168c74100>
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 63, in get_model
    self._models[key] = custom_model_init(ocr=ocr, show_log=show_log)
    │    │       │      │                     │             └ False
    │    │       │      │                     └ True
    │    │       │      └ <function custom_model_init at 0x10444c040>
    │    │       └ (True, False)
    │    └ {}
    └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x168c74100>
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 83, in custom_model_init
    from magic_pdf.model.pdf_extract_kit import CustomPEKModel
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/pdf_extract_kit.py", line 12, in <module>
    import torchtext
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/__init__.py", line 18, in <module>
    from torchtext import _extension  # noqa: F401
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/_extension.py", line 64, in <module>
    _init_extension()
    └ <function _init_extension at 0x308a864d0>
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
    └ <function _load_lib at 0x308a86440>
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
    │     │   │            └ PosixPath('/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so')
    │     │   └ <function _Ops.load_library at 0x3068ce7a0>
    │     └ <module 'torch.ops' from '_ops.py'>
    └ <module 'torch' from '/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torch/__init__.py'>
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torch/_ops.py", line 1295, in load_library
    ctypes.CDLL(path)
    │      │    └ '/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so'
    │      └ <class 'ctypes.CDLL'>
    └ <module 'ctypes' from '/opt/miniconda3/envs/MinerU/lib/python3.10/ctypes/__init__.py'>
  File "/opt/miniconda3/envs/MinerU/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
    │    │         │       │    │      └ 4
    │    │         │       │    └ '/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so'
    │    │         │       └ <CDLL '/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so', handle 0 at 0x308a88eb0>
    │    │         └ <built-in function dlopen>
    │    └ 0
    └ <CDLL '/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so', handle 0 at 0x308a88eb0>

OSError: dlopen(/opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so, 0x0006): Symbol not found: __ZN3c105ErrorC1ENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES7_PKv
  Referenced from: <8349B302-A1C9-3870-AB5A-21A14A352BC2> /opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so
  Expected in:     <69A84A04-EB16-3227-9FED-383D2FE98E93> /opt/miniconda3/envs/MinerU/lib/python3.10/site-packages/torch/lib/libc10.dylib

**Comment by samqin123** [comment]
考虑是缺少依赖包，git clone项目后pip install -r requirements.txt / requirements-qa.txt，没有报错。

**Comment by samqin123** [comment]
mac的mps安装指令 建议文档补上  pip install --upgrade pip                                                                        
pip install --no-cache-dir torch torchvision torchtext

**Comment by samqin123** [comment]
<img width="535" alt="image" src="https://github.com/user-attachments/assets/e0e4dcd4-d31b-4db7-b398-4f0121d6785b">
这3个版本是否对？

**Comment by myhloli** [comment]
> <img width="535" alt="image" src="https://github.com/user-attachments/assets/e0e4dcd4-d31b-4db7-b398-4f0121d6785b">
> 
> 这3个版本是否对？

最高只支持到

torch 2.3.1
torchvision 0.18.1
torchtext 0.18.0

您这个版本应该是无法支持的

**Comment by samqin123** [comment]
需要补充这多个依赖包 ultralytics，unimernet， paddle，对mac的部署建议你们再完善一下。

**Comment by myhloli** [comment]
> 需要补充这多个依赖包 ultralytics，unimernet， paddle，对mac的部署建议你们再完善一下。

这两个在full包中是有的，您按照readme安装0.6.2b1版本就会自动添加这两个依赖的。

**Comment by samqin123** [comment]
我已经安装了0.6.2b1版本，可是执行时报错，是不是并没有纳入  我在用pdf-extractor里的pip install -r requirements+cpu.txt添加相关插件。你可以测试一下。
https://github.com/opendatalab/PDF-Extract-Kit/blob/main/docs/Install_in_macOS_zh_cn.md

结果 ---- 执行成功了。

**Comment by samqin123** [comment]
<img width="1121" alt="image" src="https://github.com/user-attachments/assets/67061b95-4153-4c3d-ac20-68e8d8b7f182">

<img width="1725" alt="image" src="https://github.com/user-attachments/assets/df4ecd6e-8125-4841-9693-9a51f939beb7">

**Comment by samqin123** [comment]
closed
