### ISSUE TITLE
已更新0.6.2b1仍出现Required dependency not installed问题

### ISSUE THREAD

**Issue by CeliaShu1024** [opendatalab/MinerU#323]
### Description of the bug | 错误描述

如题，共有如下两个报错：
```{PlainText}
magic_pdf.model.pdf_extract_kit:<module>:24 - libGL.so.1: cannot open shared object file: No such file or directory
```
```{PlainText}
 magic_pdf.model.pdf_extract_kit:<module>:25 - Required dependency not installed, please install by 
"pip install magic-pdf[full] detectron2 --extra-index-url https://myhloli.github.io/wheels/"
```
详细过程见下文。此外是否能提供项目所需的requirements以避免依赖库版本冲突等问题？

### How to reproduce the bug | 如何复现

直接从conda创建了全新虚拟环境并按MinerU项目给出的流程进行安装。首次出现依赖库不全的报错后使用了如下更新依赖库语句：
```{PlainText}
pip cache purge
pip install magic-pdf[full]==0.6.2b1 -i https://pypi.tuna.tsinghua.edu.cn/simple detectron2 --extra-index-url https://myhloli.github.io/wheels/ --force-reinstall
```
跑测试文件的输入输出:
```{PlainText}
(MinerU) root@iZf8z73npm2neua8j5km4fZ:~# magic-pdf pdf-command --pdf "/root/data/pdfs/0ceb182a-f194-4d67-bbc4-6bb1546e6f6e.pdf" --inside_model true
2024-08-05 13:33:29.119 | WARNING  | magic_pdf.cli.magicpdf:get_model_json:312 - not found json /root/data/pdfs/0ceb182a-f194-4d67-bbc4-6bb1546e6f6e.json existed
2024-08-05 13:33:29.120 | WARNING  | magic_pdf.libs.config_reader:get_local_dir:64 - 'temp-output-dir' not found in magic-pdf.json, use '/tmp' as default
2024-08-05 13:33:30.349 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 0, text_len: 4, cid_chars_radio: 0.0
2024-08-05 13:33:30.350 | WARNING  | magic_pdf.filter.pdf_classify_by_type:classify:334 - pdf is not classified by area and text_len, by_image_area: False, by_text: False, by_avg_words: False, by_img_num: True, by_text_layout: False, by_img_narrow_strips: True, by_invalid_chars: True
2024-08-05 13:33:30.353 | ERROR    | magic_pdf.model.pdf_extract_kit:<module>:24 - libGL.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):

  File "/root/anaconda3/envs/MinerU/bin/magic-pdf", line 8, in <module>
    sys.exit(cli())
    │   │    └ <Group cli>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f8168e7b7f0>
           └ <Group cli>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f81692ffc40>
         │    └ <function MultiCommand.invoke at 0x7f8168e8c820>
         └ <Group cli>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f8150712050>
           │               │       │       └ <function Command.invoke at 0x7f8168e8c310>
           │               │       └ <Command pdf-command>
           │               └ <click.core.Context object at 0x7f8150712050>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f816935bd90>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'pdf': '/root/data/pdfs/0ceb182a-f194-4d67-bbc4-6bb1546e6f6e.pdf', 'inside_model': True, 'model': None, 'method': 'auto', 'm...
           │   │      │    │           └ <click.core.Context object at 0x7f8150712050>
           │   │      │    └ <function pdf_command at 0x7f8150732050>
           │   │      └ <Command pdf-command>
           │   └ <function Context.invoke at 0x7f8168e7b010>
           └ <click.core.Context object at 0x7f8150712050>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'pdf': '/root/data/pdfs/0ceb182a-f194-4d67-bbc4-6bb1546e6f6e.pdf', 'inside_model': True, 'model': None, 'method': 'auto', 'm...
                       └ ()
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 352, in pdf_command
    parse_doc(pdf)
    │         └ '/root/data/pdfs/0ceb182a-f194-4d67-bbc4-6bb1546e6f6e.pdf'
    └ <function pdf_command.<locals>.parse_doc at 0x7f8150731d80>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 330, in parse_doc
    do_parse(
    └ <function do_parse at 0x7f8150731990>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 111, in do_parse
    pipe.pipe_analyze()
    │    └ <function UNIPipe.pipe_analyze at 0x7f81507305e0>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f8150711c60>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 31, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=True)
    │    │            │           │    └ b'%PDF-1.6\r%\xe2\xe3\xcf\xd3\r\n53 0 obj\r<</Linearized 1/L 2128191/O 55/E 531771/N 4/T 2127832/H [ 442 190]>>\rendobj\r    ...
    │    │            │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f8150711c60>
    │    │            └ <function doc_analyze at 0x7f8167ac7520>
    │    └ []
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f8150711c60>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 103, in doc_analyze
    custom_model = model_manager.get_model(ocr, show_log)
                   │             │         │    └ False
                   │             │         └ True
                   │             └ <function ModelSingleton.get_model at 0x7f8167ac7490>
                   └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x7f8150712d40>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 63, in get_model
    self._models[key] = custom_model_init(ocr=ocr, show_log=show_log)
    │    │       │      │                     │             └ False
    │    │       │      │                     └ True
    │    │       │      └ <function custom_model_init at 0x7f8167ac7370>
    │    │       └ (True, False)
    │    └ {}
    └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x7f8150712d40>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 83, in custom_model_init
    from magic_pdf.model.pdf_extract_kit import CustomPEKModel
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/pdf_extract_kit.py", line 7, in <module>
    import cv2
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
    └ <function bootstrap at 0x7f81507325f0>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    │         └ <function import_module at 0x7f81691c3f40>
                    └ <module 'importlib' from '/root/anaconda3/envs/MinerU/lib/python3.10/importlib/__init__.py'>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'cv2'
           │          └ <function _gcd_import at 0x7f816935b400>
           └ <module '_frozen_importlib' (frozen)>

ImportError: libGL.so.1: cannot open shared object file: No such file or directory
2024-08-05 13:33:30.383 | ERROR    | magic_pdf.model.pdf_extract_kit:<module>:25 - Required dependency not installed, please install by 
"pip install magic-pdf[full] detectron2 --extra-index-url https://myhloli.github.io/wheels/"
```

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
0.6.2的好处是可以直接通过日志定位问题点，直接搜索这个问题

ImportError: libGL.so.1: cannot open shared object file: No such file or directory

就能找到解决方案

https://github.com/opendatalab/MinerU/issues/165#issuecomment-2245202282

**Comment by CeliaShu1024** [comment]
已解决
