### ISSUE TITLE
invalid load key, 'v'.

### ISSUE THREAD

**Issue by THEONEBUKE** [opendatalab/MinerU#341]
### Description of the bug | 错误描述

2024-08-06 14:23:33.971 | WARNING  | magic_pdf.cli.magicpdf:get_model_json:312 - not found json demo1.json existed
2024-08-06 14:23:33.971 | WARNING  | magic_pdf.libs.config_reader:get_local_dir:64 - 'temp-output-dir' not found in magic-pdf.json, use '/tmp' as default
2024-08-06 14:23:35.446 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 9, text_len: 32295, cid_chars_radio: 0.0002791476691169629
INFO:datasets:PyTorch version 2.3.1 available.
2024-08-06 14:23:45.388 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:99 - DocAnalysis init, this may take some times. apply_layout: True, apply_formula: True, apply_ocr: False
2024-08-06 14:23:45.388 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:107 - using device: cuda
2024-08-06 14:23:45.388 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:109 - using models_dir: /data/Miner_modle/PDF-Extract-Kit/models
2024-08-06 14:23:45.389 | ERROR    | magic_pdf.cli.magicpdf:parse_doc:338 - invalid load key, 'v'.
Traceback (most recent call last):

  File "/root/anaconda3/envs/MinerU/bin/magic-pdf", line 8, in <module>
    sys.exit(cli())
    │   │    └ <Group cli>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f5a6668f7f0>
           └ <Group cli>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f5a66b13c40>
         │    └ <function MultiCommand.invoke at 0x7f5a666a0820>
         └ <Group cli>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f5a1be2e170>
           │               │       │       └ <function Command.invoke at 0x7f5a666a0310>
           │               │       └ <Command pdf-command>
           │               └ <click.core.Context object at 0x7f5a1be2e170>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f5a66b6fd90>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'pdf': 'demo1.pdf', 'inside_model': True, 'model': None, 'method': 'auto', 'model_mode': 'full'}
           │   │      │    │           └ <click.core.Context object at 0x7f5a1be2e170>
           │   │      │    └ <function pdf_command at 0x7f5a1b832200>
           │   │      └ <Command pdf-command>
           │   └ <function Context.invoke at 0x7f5a6668f010>
           └ <click.core.Context object at 0x7f5a1be2e170>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'pdf': 'demo1.pdf', 'inside_model': True, 'model': None, 'method': 'auto', 'model_mode': 'full'}
                       └ ()
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 352, in pdf_command
    parse_doc(pdf)
    │         └ 'demo1.pdf'
    └ <function pdf_command.<locals>.parse_doc at 0x7f5a1b831f30>
> File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 330, in parse_doc
    do_parse(
    └ <function do_parse at 0x7f5a1b831b40>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/cli/magicpdf.py", line 111, in do_parse
    pipe.pipe_analyze()
    │    └ <function UNIPipe.pipe_analyze at 0x7f5a1b830790>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f5a1be2ddb0>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 29, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=False)
    │    │            │           │    └ b'%PDF-1.3\r%\xe2\xe3\xcf\xd3\r\n236 0 obj\r<< \r/Linearized 1 \r/O 242 \r/H [ 2994 878 ] \r/L 336919 \r/E 56128 \r/N 13 \r/T...
    │    │            │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f5a1be2ddb0>
    │    │            └ <function doc_analyze at 0x7f5a650b7640>
    │    └ []
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f5a1be2ddb0>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 103, in doc_analyze
    custom_model = model_manager.get_model(ocr, show_log)
                   │             │         │    └ False
                   │             │         └ False
                   │             └ <function ModelSingleton.get_model at 0x7f5a650b75b0>
                   └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x7f5a1ae6f430>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 63, in get_model
    self._models[key] = custom_model_init(ocr=ocr, show_log=show_log)
    │    │       │      │                     │             └ False
    │    │       │      │                     └ False
    │    │       │      └ <function custom_model_init at 0x7f5a650b7490>
    │    │       └ (False, False)
    │    └ {}
    └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x7f5a1ae6f430>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 87, in custom_model_init
    custom_model = CustomPEKModel(ocr=ocr, show_log=show_log, models_dir=local_models_dir, device=device)
                   │                  │             │                    │                        └ 'cuda'
                   │                  │             │                    └ '/data/Miner_modle/PDF-Extract-Kit/models'
                   │                  │             └ False
                   │                  └ False
                   └ <class 'magic_pdf.model.pdf_extract_kit.CustomPEKModel'>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/pdf_extract_kit.py", line 114, in __init__
    self.mfd_model = mfd_model_init(str(os.path.join(models_dir, self.configs["weights"]["mfd"])))
    │                │                  │  │    │    │           │    └ {'config': {'device': 'cpu', 'layout': True, 'formula': True}, 'weights': {'layout': 'Layout/model_final.pth', 'mfd': 'MFD/we...
    │                │                  │  │    │    │           └ <magic_pdf.model.pdf_extract_kit.CustomPEKModel object at 0x7f5a1be2ec50>
    │                │                  │  │    │    └ '/data/Miner_modle/PDF-Extract-Kit/models'
    │                │                  │  │    └ <function join at 0x7f5a66a7ab00>
    │                │                  │  └ <module 'posixpath' from '/root/anaconda3/envs/MinerU/lib/python3.10/posixpath.py'>
    │                │                  └ <module 'os' from '/root/anaconda3/envs/MinerU/lib/python3.10/os.py'>
    │                └ <function mfd_model_init at 0x7f5a1b832950>
    └ <magic_pdf.model.pdf_extract_kit.CustomPEKModel object at 0x7f5a1be2ec50>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/pdf_extract_kit.py", line 36, in mfd_model_init
    mfd_model = YOLO(weight)
                │    └ '/data/Miner_modle/PDF-Extract-Kit/models/MFD/weights.pt'
                └ <class 'ultralytics.models.yolo.model.YOLO'>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
                           │           │             └ False
                           │           └ None
                           └ '/data/Miner_modle/PDF-Extract-Kit/models/MFD/weights.pt'
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/ultralytics/engine/model.py", line 142, in __init__
    self._load(model, task=task)
    │    │     │           └ None
    │    │     └ '/data/Miner_modle/PDF-Extract-Kit/models/MFD/weights.pt'
    │    └ <function Model._load at 0x7f595b1f7760>
    └ YOLO()
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/ultralytics/engine/model.py", line 294, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
    │    │      │    │      │                       └ '/data/Miner_modle/PDF-Extract-Kit/models/MFD/weights.pt'
    │    │      │    │      └ <function attempt_load_one_weight at 0x7f595b17a290>
    │    │      │    └ None
    │    │      └ YOLO()
    │    └ None
    └ YOLO()
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   │               └ '/data/Miner_modle/PDF-Extract-Kit/models/MFD/weights.pt'
                   └ <function torch_safe_load at 0x7f595b17a170>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 781, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
           │     │    └ '/data/Miner_modle/PDF-Extract-Kit/models/MFD/weights.pt'
           │     └ <function torch_load at 0x7f595b2ffa30>
           └ <module 'torch' from '/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/torch/__init__.py'>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/ultralytics/utils/patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
           │            │       └ {'map_location': 'cpu', 'weights_only': False}
           │            └ ('/data/Miner_modle/PDF-Extract-Kit/models/MFD/weights.pt',)
           └ <function load at 0x7f5a1a7840d0>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           │            │            │             │                └ {'encoding': 'utf-8'}
           │            │            │             └ <module 'pickle' from '/root/anaconda3/envs/MinerU/lib/python3.10/pickle.py'>
           │            │            └ 'cpu'
           │            └ <_io.BufferedReader name='/data/Miner_modle/PDF-Extract-Kit/models/MFD/weights.pt'>
           └ <function _legacy_load at 0x7f5a1a784280>
  File "/root/anaconda3/envs/MinerU/lib/python3.10/site-packages/torch/serialization.py", line 1262, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   │             │    │    └ {'encoding': 'utf-8'}
                   │             │    └ <_io.BufferedReader name='/data/Miner_modle/PDF-Extract-Kit/models/MFD/weights.pt'>
                   │             └ <built-in function load>
                   └ <module 'pickle' from '/root/anaconda3/envs/MinerU/lib/python3.10/pickle.py'>

_pickle.UnpicklingError: invalid load key, 'v'.

### How to reproduce the bug | 如何复现

magic-pdf pdf-command --pdf demo1.pdf --inside_model true

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
refer: https://github.com/opendatalab/MinerU/issues/211

Please check local model files size & sha256.

**Comment by THEONEBUKE** [comment]
我看了下大小只有几MB...那应该是不完整

**Comment by xflhxz** [comment]
macos 遇到了一样的问题，请问最后是怎么解决的

**Comment by THEONEBUKE** [comment]
> macos 遇到了一样的问题，请问最后是怎么解决的

https://github.com/opendatalab/MinerU/blob/master/docs/how_to_download_models_zh_cn.md#2%E5%88%A9%E7%94%A8sdk%E4%B8%8B%E8%BD%BD
