### ISSUE TITLE
ّI have many problems on installing dependency 

### ISSUE THREAD

**Issue by tabatabaei** [opendatalab/MinerU#424]
### Description of the bug | 错误描述

the requirements file is not complete and I have got many errors in dependency then I had to install manually package  but I can't success to install all

 magic-pdf -p whisper.pdf -o whisper 
2024-08-14 07:05:24.995 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 0, text_len: 41923, cid_chars_radio: 0.0
2024-08-14 07:05:25.593 | ERROR    | magic_pdf.model.pdf_extract_kit:<module>:27 - No module named 'torchtext'
Traceback (most recent call last):

  File "/home/tabatabaei/anaconda3/envs/llm/bin/magic-pdf", line 8, in <module>
    sys.exit(cli())
    │   │    └ <Command cli>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x746fb2c7d800>
           └ <Command cli>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x746fb1fe0e90>
         │    └ <function Command.invoke at 0x746fb2c7e3e0>
         └ <Command cli>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'path': 'whisper.pdf', 'output_dir': 'whisper', 'method': 'auto'}
           │   │      │    │           └ <click.core.Context object at 0x746fb1fe0e90>
           │   │      │    └ <function cli at 0x746f521e1080>
           │   │      └ <Command cli>
           │   └ <function Context.invoke at 0x746fb2c7cd60>
           └ <click.core.Context object at 0x746fb1fe0e90>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'path': 'whisper.pdf', 'output_dir': 'whisper', 'method': 'auto'}
                       └ ()
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/tools/cli.py", line 75, in cli
    parse_doc(path)
    │         └ 'whisper.pdf'
    └ <function cli.<locals>.parse_doc at 0x746fb2ea93a0>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/tools/cli.py", line 60, in parse_doc
    do_parse(
    └ <function do_parse at 0x746fb1fdd580>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/tools/common.py", line 65, in do_parse
    pipe.pipe_analyze()
    │    └ <function UNIPipe.pipe_analyze at 0x746f521e0360>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x746f521e5550>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/pipe/UNIPipe.py", line 29, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=False)
    │    │            │           │    └ b'%PDF-1.5\n%\xbf\xf7\xa2\xfe\n1141 0 obj\n<< /Linearized 1 /L 857252 /H [ 6451 461 ] /O 1146 /E 85153 /N 28 /T 850133 >>\nen...
    │    │            │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x746f521e5550>
    │    │            └ <function doc_analyze at 0x746faa966840>
    │    └ []
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x746f521e5550>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 109, in doc_analyze
    custom_model = model_manager.get_model(ocr, show_log)
                   │             │         │    └ False
                   │             │         └ False
                   │             └ <function ModelSingleton.get_model at 0x746faa9667a0>
                   └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x746f5ab6a710>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 63, in get_model
    self._models[key] = custom_model_init(ocr=ocr, show_log=show_log)
    │    │       │      │                     │             └ False
    │    │       │      │                     └ False
    │    │       │      └ <function custom_model_init at 0x746faa966660>
    │    │       └ (False, False)
    │    └ {}
    └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x746f5ab6a710>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 83, in custom_model_init
    from magic_pdf.model.pdf_extract_kit import CustomPEKModel
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/pdf_extract_kit.py", line 14, in <module>
    import torchtext

ModuleNotFoundError: No module named 'torchtext'
2024-08-14 07:05:25.600 | ERROR    | magic_pdf.model.pdf_extract_kit:<module>:28 - Required dependency not installed, please install by 
"pip install magic-pdf[full] --extra-index-url https://myhloli.github.io/wheels/"

$ magic-pdf -p whisper.pdf -o whisper -m ocr
2024-08-14 07:06:06.689 | ERROR    | magic_pdf.model.pdf_extract_kit:<module>:27 - No module named 'unimernet'
Traceback (most recent call last):

  File "/home/tabatabaei/anaconda3/envs/llm/bin/magic-pdf", line 8, in <module>
    sys.exit(cli())
    │   │    └ <Command cli>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x70170787d800>
           └ <Command cli>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7016c695b3d0>
         │    └ <function Command.invoke at 0x70170787e3e0>
         └ <Command cli>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'path': 'whisper.pdf', 'output_dir': 'whisper', 'method': 'ocr'}
           │   │      │    │           └ <click.core.Context object at 0x7016c695b3d0>
           │   │      │    └ <function cli at 0x7016a6fbd080>
           │   │      └ <Command cli>
           │   └ <function Context.invoke at 0x70170787cd60>
           └ <click.core.Context object at 0x7016c695b3d0>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'path': 'whisper.pdf', 'output_dir': 'whisper', 'method': 'ocr'}
                       └ ()
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/tools/cli.py", line 75, in cli
    parse_doc(path)
    │         └ 'whisper.pdf'
    └ <function cli.<locals>.parse_doc at 0x701707aa93a0>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/tools/cli.py", line 60, in parse_doc
    do_parse(
    └ <function do_parse at 0x701706efd580>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/tools/common.py", line 65, in do_parse
    pipe.pipe_analyze()
    │    └ <function OCRPipe.pipe_analyze at 0x7016a6fbc860>
    └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7016a6fc4650>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/pipe/OCRPipe.py", line 19, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=True)
    │    │            │           │    └ b'%PDF-1.5\n%\xbf\xf7\xa2\xfe\n1141 0 obj\n<< /Linearized 1 /L 857252 /H [ 6451 461 ] /O 1146 /E 85153 /N 28 /T 850133 >>\nen...
    │    │            │           └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7016a6fc4650>
    │    │            └ <function doc_analyze at 0x7016ff67a840>
    │    └ []
    └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7016a6fc4650>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 109, in doc_analyze
    custom_model = model_manager.get_model(ocr, show_log)
                   │             │         │    └ False
                   │             │         └ True
                   │             └ <function ModelSingleton.get_model at 0x7016ff67a7a0>
                   └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x7016a6fc4550>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 63, in get_model
    self._models[key] = custom_model_init(ocr=ocr, show_log=show_log)
    │    │       │      │                     │             └ False
    │    │       │      │                     └ True
    │    │       │      └ <function custom_model_init at 0x7016ff67a660>
    │    │       └ (True, False)
    │    └ {}
    └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x7016a6fc4550>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 83, in custom_model_init
    from magic_pdf.model.pdf_extract_kit import CustomPEKModel
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/pdf_extract_kit.py", line 22, in <module>
    from unimernet.common.config import Config

ModuleNotFoundError: No module named 'unimernet'
2024-08-14 07:06:06.702 | ERROR    | magic_pdf.model.pdf_extract_kit:<module>:28 - Required dependency not installed, please install by 
"pip install magic-pdf[full] --extra-index-url https://myhloli.github.io/wheels/"

$ magic-pdf -p whisper.pdf -o whisper -m ocr
2024-08-14 07:07:04.328 | ERROR    | magic_pdf.tools.cli:parse_doc:69 - No module named 'pycocotools'
Traceback (most recent call last):

  File "/home/tabatabaei/anaconda3/envs/llm/bin/magic-pdf", line 8, in <module>
    sys.exit(cli())
    │   │    └ <Command cli>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x79841f781800>
           └ <Command cli>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7983bedb1f90>
         │    └ <function Command.invoke at 0x79841f7823e0>
         └ <Command cli>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'path': 'whisper.pdf', 'output_dir': 'whisper', 'method': 'ocr'}
           │   │      │    │           └ <click.core.Context object at 0x7983bedb1f90>
           │   │      │    └ <function cli at 0x7983beded080>
           │   │      └ <Command cli>
           │   └ <function Context.invoke at 0x79841f780d60>
           └ <click.core.Context object at 0x7983bedb1f90>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'path': 'whisper.pdf', 'output_dir': 'whisper', 'method': 'ocr'}
                       └ ()
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/tools/cli.py", line 75, in cli
    parse_doc(path)
    │         └ 'whisper.pdf'
    └ <function cli.<locals>.parse_doc at 0x79841f9ad3a0>
> File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/tools/cli.py", line 60, in parse_doc
    do_parse(
    └ <function do_parse at 0x79841eafd580>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/tools/common.py", line 65, in do_parse
    pipe.pipe_analyze()
    │    └ <function OCRPipe.pipe_analyze at 0x7983bedec860>
    └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7983bedf46d0>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/pipe/OCRPipe.py", line 19, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=True)
    │    │            │           │    └ b'%PDF-1.5\n%\xbf\xf7\xa2\xfe\n1141 0 obj\n<< /Linearized 1 /L 857252 /H [ 6451 461 ] /O 1146 /E 85153 /N 28 /T 850133 >>\nen...
    │    │            │           └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7983bedf46d0>
    │    │            └ <function doc_analyze at 0x798417482840>
    │    └ []
    └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7983bedf46d0>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 109, in doc_analyze
    custom_model = model_manager.get_model(ocr, show_log)
                   │             │         │    └ False
                   │             │         └ True
                   │             └ <function ModelSingleton.get_model at 0x7984174827a0>
                   └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x7983bed43f50>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 63, in get_model
    self._models[key] = custom_model_init(ocr=ocr, show_log=show_log)
    │    │       │      │                     │             └ False
    │    │       │      │                     └ True
    │    │       │      └ <function custom_model_init at 0x798417482660>
    │    │       └ (True, False)
    │    └ {}
    └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x7983bed43f50>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 83, in custom_model_init
    from magic_pdf.model.pdf_extract_kit import CustomPEKModel
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/pdf_extract_kit.py", line 33, in <module>
    from magic_pdf.model.pek_sub_modules.layoutlmv3.model_init import Layoutlmv3_Predictor
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/pek_sub_modules/layoutlmv3/model_init.py", line 1, in <module>
    from .visualizer import Visualizer
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/pek_sub_modules/layoutlmv3/visualizer.py", line 11, in <module>
    import pycocotools.mask as mask_util

ModuleNotFoundError: No module named 'pycocotools'

$ magic-pdf -p whisper.pdf -o whisper -m ocr
2024-08-14 07:07:37.113 | ERROR    | magic_pdf.tools.cli:parse_doc:69 - No module named 'detectron2'
Traceback (most recent call last):

  File "/home/tabatabaei/anaconda3/envs/llm/bin/magic-pdf", line 8, in <module>
    sys.exit(cli())
    │   │    └ <Command cli>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7dc07ac7d800>
           └ <Command cli>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7dc03934c250>
         │    └ <function Command.invoke at 0x7dc07ac7e3e0>
         └ <Command cli>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'path': 'whisper.pdf', 'output_dir': 'whisper', 'method': 'ocr'}
           │   │      │    │           └ <click.core.Context object at 0x7dc03934c250>
           │   │      │    └ <function cli at 0x7dc0203bd080>
           │   │      └ <Command cli>
           │   └ <function Context.invoke at 0x7dc07ac7cd60>
           └ <click.core.Context object at 0x7dc03934c250>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'path': 'whisper.pdf', 'output_dir': 'whisper', 'method': 'ocr'}
                       └ ()
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/tools/cli.py", line 75, in cli
    parse_doc(path)
    │         └ 'whisper.pdf'
    └ <function cli.<locals>.parse_doc at 0x7dc07aea93a0>
> File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/tools/cli.py", line 60, in parse_doc
    do_parse(
    └ <function do_parse at 0x7dc07a2fd580>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/tools/common.py", line 65, in do_parse
    pipe.pipe_analyze()
    │    └ <function OCRPipe.pipe_analyze at 0x7dc0203bc860>
    └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7dc027719850>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/pipe/OCRPipe.py", line 19, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=True)
    │    │            │           │    └ b'%PDF-1.5\n%\xbf\xf7\xa2\xfe\n1141 0 obj\n<< /Linearized 1 /L 857252 /H [ 6451 461 ] /O 1146 /E 85153 /N 28 /T 850133 >>\nen...
    │    │            │           └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7dc027719850>
    │    │            └ <function doc_analyze at 0x7dc072a7a840>
    │    └ []
    └ <magic_pdf.pipe.OCRPipe.OCRPipe object at 0x7dc027719850>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 109, in doc_analyze
    custom_model = model_manager.get_model(ocr, show_log)
                   │             │         │    └ False
                   │             │         └ True
                   │             └ <function ModelSingleton.get_model at 0x7dc072a7a7a0>
                   └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x7dc022d43b10>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 63, in get_model
    self._models[key] = custom_model_init(ocr=ocr, show_log=show_log)
    │    │       │      │                     │             └ False
    │    │       │      │                     └ True
    │    │       │      └ <function custom_model_init at 0x7dc072a7a660>
    │    │       └ (True, False)
    │    └ {}
    └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x7dc022d43b10>
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 83, in custom_model_init
    from magic_pdf.model.pdf_extract_kit import CustomPEKModel
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/pdf_extract_kit.py", line 33, in <module>
    from magic_pdf.model.pek_sub_modules.layoutlmv3.model_init import Layoutlmv3_Predictor
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/pek_sub_modules/layoutlmv3/model_init.py", line 1, in <module>
    from .visualizer import Visualizer
  File "/home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/magic_pdf/model/pek_sub_modules/layoutlmv3/visualizer.py", line 16, in <module>
    from detectron2.data import MetadataCatalog

ModuleNotFoundError: No module named 'detectron2'

### How to reproduce the bug | 如何复现

Create new Conda environment whitout any pakages and install in with this command `pip install magic-pdf[full]==0.7.0b1 --extra-index-url https://wheels.myhloli.com
` 
which is in manual 

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.11

### Software version | 软件版本 (magic-pdf --version)

0.6.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
Why not try to install it by following the tutorial?

**Comment by tabatabaei** [comment]
> Why not try to install it by following the tutorial?
I follow this 
https://github.com/opendatalab/MinerU/blob/master/docs/README_Ubuntu_CUDA_Acceleration_en_US.md

I got error in this command `pip install magic-pdf[full]==0.7.0b1 --extra-index-url https://myhloli.github.io/wheels/`
I seem there is not have full option in new version 


$ pip install magic-pdf[full]==0.7.0b1 --extra-index-url https://myhloli.github.io/wheels/
DEPRECATION: Loading egg at /home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/flashrag-0.0.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages/flash_attn-2.6.3-py3.11-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://myhloli.github.io/wheels/
Collecting magic-pdf==0.7.0b1 (from magic-pdf[full]==0.7.0b1)
  Downloading magic_pdf-0.7.0b1-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: boto3>=1.28.43 in /home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages (from magic-pdf==0.7.0b1->magic-pdf[full]==0.7.0b1) (1.34.145)
Requirement already satisfied: Brotli>=1.1.0 in /home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages (from magic-pdf==0.7.0b1->magic-pdf[full]==0.7.0b1) (1.1.0)
Requirement already satisfied: click>=8.1.7 in /home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages (from magic-pdf==0.7.0b1->magic-pdf[full]==0.7.0b1) (8.1.7)
Requirement already satisfied: PyMuPDF>=1.24.9 in /home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages (from magic-pdf==0.7.0b1->magic-pdf[full]==0.7.0b1) (1.24.9)
Requirement already satisfied: loguru>=0.6.0 in /home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages (from magic-pdf==0.7.0b1->magic-pdf[full]==0.7.0b1) (0.6.0)
Requirement already satisfied: numpy<2.0.0,>=1.21.6 in /home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages (from magic-pdf==0.7.0b1->magic-pdf[full]==0.7.0b1) (1.26.4)
Collecting fast-langdetect==0.2.0 (from magic-pdf==0.7.0b1->magic-pdf[full]==0.7.0b1)
  Downloading fast_langdetect-0.2.0-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: wordninja>=2.0.0 in /home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages (from magic-pdf==0.7.0b1->magic-pdf[full]==0.7.0b1) (2.0.0)
Requirement already satisfied: scikit-learn>=1.0.2 in /home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages (from magic-pdf==0.7.0b1->magic-pdf[full]==0.7.0b1) (1.3.2)
Requirement already satisfied: pdfminer.six==20231228 in /home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages (from magic-pdf==0.7.0b1->magic-pdf[full]==0.7.0b1) (20231228)
Requirement already satisfied: unimernet==0.1.6 in /home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages (from magic-pdf[full]==0.7.0b1) (0.1.6)
Requirement already satisfied: ultralytics in /home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages (from magic-pdf[full]==0.7.0b1) (8.2.76)
Collecting paddleocr==2.7.3 (from magic-pdf[full]==0.7.0b1)
  Downloading paddleocr-2.7.3-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: pypandoc in /home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages (from magic-pdf[full]==0.7.0b1) (1.13)
Requirement already satisfied: struct-eqtable==0.1.0 in /home/tabatabaei/anaconda3/envs/llm/lib/python3.11/site-packages (from magic-pdf[full]==0.7.0b1) (0.1.0)
INFO: pip is looking at multiple versions of magic-pdf[full] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement detectron2; extra == "full" (from magic-pdf[full]) (from versions: none)
ERROR: No matching distribution found for detectron2; extra == "full"

**Comment by myhloli** [comment]
You missed step 4.

Specify Python version 3.10.

conda create -n MinerU python=3.10
conda activate MinerU

**Comment by tabatabaei** [comment]
Thanks 
Not much different between python3.10 and 3.11. I have cuda12 and try to solve last step "installing paddlepaddle-gpu==3.0.0b1" which is not in package dependency. I think my problem from that. If not solved I'll try python3.10

**Comment by tabatabaei** [comment]
Thanks 
Not much different between python3.10 and 3.11. I have cuda12 and try to solve last step "installing paddlepaddle-gpu==3.0.0b1" which is not in package dependency. I thick my problem from that. If not solved I'll try python3.10

**Comment by myhloli** [comment]
> Thanks Not much different between python3.10 and 3.11. I have cuda12 and try to solve last step "installing paddlepaddle-gpu==3.0.0b1" which is not in package dependency. I think my problem from that. If not solved I'll try python3.10


You must use python3.10 instead of 3.11 version.
Because our pre-compiled “detectron2” installation package is only for version 3.10.

**Comment by tabatabaei** [comment]
I create new Conda env with python3.10 and install again. I have new error and after uninstall flash attention library it's worked. thanks
