### ISSUE TITLE
[WinError 127] 找不到指定的程序

### ISSUE THREAD

**Issue by HalitHe** [opendatalab/MinerU#445]
### Description of the bug | 错误描述

2024-08-16 16:39:45.419 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 0, text_len: 1, cid_chars_radio: 0.0
2024-08-16 16:39:45.420 | WARNING  | magic_pdf.filter.pdf_classify_by_type:classify:334 - pdf is not classified by area and text_len, by_image_area: False, by_text: False, by_avg_words: False, by_img_num: True, by_text_layout: False, by_img_narrow_strips: True, by_invalid_chars: True
2024-08-16 16:39:47.282 | ERROR    | magic_pdf.tools.cli:parse_doc:69 - [WinError 127] 找不到指定的程序。
Traceback (most recent call last):

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Users\XN963FS\AppData\Loca...
           │         └ <code object <module> at 0x00000208217B0240, file "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\Scripts\magic-pdf...
           └ <function _run_code at 0x00000208214EFC70>

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "C:\Users\XN963FS\AppData\Loca...
         └ <code object <module> at 0x00000208217B0240, file "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\Scripts\magic-pdf...

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\Scripts\magic-pdf.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
    │   │    └ <Command cli>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x0000020823398A60>
           └ <Command cli>

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x00000208217E87C0>
         │    └ <function Command.invoke at 0x0000020823399510>
         └ <Command cli>

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'path': 'C:\\Users\\XN963FS\\Downloads\\PDF-Extract-Kit', 'output_dir': 'C:\\Users\\XN963FS\\Downloads', 'method': 'auto'}
           │   │      │    │           └ <click.core.Context object at 0x00000208217E87C0>
           │   │      │    └ <function cli at 0x0000020857363A30>
           │   │      └ <Command cli>
           │   └ <function Context.invoke at 0x0000020823398280>
           └ <click.core.Context object at 0x00000208217E87C0>

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'path': 'C:\\Users\\XN963FS\\Downloads\\PDF-Extract-Kit', 'output_dir': 'C:\\Users\\XN963FS\\Downloads', 'method': 'auto'}
                       └ ()

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\site-packages\magic_pdf\tools\cli.py", line 73, in cli
    parse_doc(doc_path)
    │         └ WindowsPath('C:/Users/XN963FS/Downloads/PDF-Extract-Kit/186e654a02c94ecf0c0800342099e8c.pdf')
    └ <function cli.<locals>.parse_doc at 0x00000208217EC9D0>

> File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\site-packages\magic_pdf\tools\cli.py", line 60, in parse_doc
    do_parse(
    └ <function do_parse at 0x00000208237A13F0>

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\site-packages\magic_pdf\tools\common.py", line 65, in do_parse
    pipe.pipe_analyze()
    │    └ <function UNIPipe.pipe_analyze at 0x0000020857362E60>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000002085737C0D0>

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\site-packages\magic_pdf\pipe\UNIPipe.py", line 31, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=True)
    │    │            │           │    └ b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n1 0 obj\n<<\n/CreationDate (D:20240719121335+08\'00\')\n/CreatorTool (PDF-XChange Standard \\(...
    │    │            │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000002085737C0D0>
    │    │            └ <function doc_analyze at 0x000002083B9BBD90>
    │    └ []
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x000002085737C0D0>

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line 109, in doc_analyze
    custom_model = model_manager.get_model(ocr, show_log)
                   │             │         │    └ False
                   │             │         └ True
                   │             └ <function ModelSingleton.get_model at 0x000002083B9BBD00>
                   └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x000002085737D780>

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line 63, in get_model
    self._models[key] = custom_model_init(ocr=ocr, show_log=show_log)
    │    │       │      │                     │             └ False
    │    │       │      │                     └ True
    │    │       │      └ <function custom_model_init at 0x000002083B9BBBE0>
    │    │       └ (True, False)
    │    └ {}
    └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x000002085737D780>

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\site-packages\magic_pdf\model\doc_analyze_by_custom_model.py", line 83, in custom_model_init
    from magic_pdf.model.pdf_extract_kit import CustomPEKModel

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\site-packages\magic_pdf\model\pdf_extract_kit.py", line 14, in <module>
    import torchtext

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\site-packages\torchtext\__init__.py", line 18, in <module>
    from torchtext import _extension  # noqa: F401

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\site-packages\torchtext\_extension.py", line 64, in
 <module>
    _init_extension()
    └ <function _init_extension at 0x000002085FF03760>

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\site-packages\torchtext\_extension.py", line 58, in
 _init_extension
    _load_lib("libtorchtext")
    └ <function _load_lib at 0x000002085FF035B0>

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\site-packages\torchtext\_extension.py", line 50, in
 _load_lib
    torch.ops.load_library(path)
    │     │   │            └ WindowsPath('C:/Users/XN963FS/AppData/Local/Programs/Python/Python310/lib/site-packages/torchtext/lib/libtorchtext.pyd')
    │     │   └ <function _Ops.load_library at 0x000002085DA59360>
    │     └ <module 'torch.ops' from '_ops.py'>
    └ <module 'torch' from 'C:\\Users\\XN963FS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\torch\\__init__.py'>

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_ops.py", line 1295, in load_library
    ctypes.CDLL(path)
    │      │    └ 'C:\\Users\\XN963FS\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\torchtext\\lib\\libtorchtext.pyd'
    │      └ <class 'ctypes.CDLL'>
    └ <module 'ctypes' from 'C:\\Users\\XN963FS\\AppData\\Local\\Programs\\Python\\Python310\\lib\\ctypes\\__init__.py'>

  File "C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
    │    │         │       │    │      └ 4352
    │    │         │       │    └ 'C:\\Users\\XN963FS\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\torchtext\\lib\\libtorchtext.pyd'
    │    │         │       └ <CDLL 'C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\Lib\site-packages\torchtext\lib\libtorchtext.pyd', handle 0 a...
    │    │         └ <built-in function LoadLibrary>
    │    └ 0
    └ <CDLL 'C:\Users\XN963FS\AppData\Local\Programs\Python\Python310\Lib\site-packages\torchtext\lib\libtorchtext.pyd', handle 0 a...

OSError: [WinError 127] 找不到指定的程序。

### How to reproduce the bug | 如何复现

magic-pdf command

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.7.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
pip list 看一下你的torch 和torchvision版本，
正常情况应该是2.3.1和0.18.1，高版本的情况下和torchtext库0.18.0不适配

**Comment by vanchy-z** [comment]
您好我也是同样的问题，而且我的torch和torchvision版本对的
![Snipaste_2024-08-19_13-22-48](https://github.com/user-attachments/assets/99c2beb4-d812-4b73-9dfd-4e8119130662)

**Comment by HalitHe** [comment]
> pip list 看一下你的torch 和torchvision版本， 正常情况应该是2.3.1和0.18.1，高版本的情况下和torchtext库0.18.0不适配

已解决，谢谢
