### ISSUE TITLE
无法使用HTTPSConnectionPool

### ISSUE THREAD

**Issue by moli-jie** [opendatalab/MinerU#605]
### Description of the bug | 错误描述

PS F:\study\python\1\MinerU-master> magic-pdf -p D://文件//25_jie_guo_san.pdf -o 66 -m auto
2024-09-12 17:37:17.128 | INFO     | magic_pdf.libs.pdf_check:detect_invalid_chars:57 - cid_count: 0, text_len: 192, cid_chars_radio: 0.0
2024-09-12 17:37:17.129 | WARNING  | magic_pdf.filter.pdf_classify_by_type:classify:334 - pdf is not classified by area and text_len, by_image_area: False, by_text: True, by_avg_words: True, by_img_num: True, by_text_layout: True, by_img_narrow_strips: True, by_invalid_chars: True
2024-09-12 17:37:28.733 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:180 - DocAnalysis init, this may take 
some times. apply_layout: True, apply_formula: True, apply_ocr: True, apply_table: False
2024-09-12 17:37:28.733 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:188 - using device: cpu
2024-09-12 17:37:28.733 | INFO     | magic_pdf.model.pdf_extract_kit:__init__:190 - using models_dir: F:/study/python/1/MinerU-master/mo
2024-09-12 17:37:28.742 | ERROR    | magic_pdf.tools.cli:parse_doc:96 - HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/ultralytics/assets/releases/tags/v8.2.0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))
Traceback (most recent call last):

  File "E:\anda\envs\myenv\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x0000013B64C73E20>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x0000013B25222320>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x0000013B64C736D0>

  File "E:\anda\envs\myenv\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x0000013B25212710>
    └ <urllib3.connection.HTTPSConnection object at 0x0000013B64C73E20>

  File "E:\anda\envs\myenv\lib\site-packages\urllib3\connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        └ <function _ssl_wrap_socket_and_match_hostname at 0x0000013B251BBA30>

  File "E:\anda\envs\myenv\lib\site-packages\urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               └ <function ssl_wrap_socket at 0x0000013B2518E050>

  File "E:\anda\envs\myenv\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               │                     │     │        │           └ 'api.github.com'
               │                     │     │        └ False
               │                     │     └ <ssl.SSLContext object at 0x0000013B35C4DFC0>
               │                     └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>
               └ <function _ssl_wrap_socket_impl at 0x0000013B2518E200>

  File "E:\anda\envs\myenv\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'api.github.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>
           │           └ <function SSLContext.wrap_socket at 0x0000013B24918040>
           └ <ssl.SSLContext object at 0x0000013B35C4DFC0>

  File "E:\anda\envs\myenv\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod(<function SSLSocket._create at 0x0000013B24919BD0>)>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x0000013B35C4DFC0>

  File "E:\anda\envs\myenv\lib\ssl.py", line 1104, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x0000013B2491AE60>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>

  File "E:\anda\envs\myenv\lib\ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "E:\anda\envs\myenv\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               │    └ <function HTTPConnectionPool._make_request at 0x0000013B25221F30>
               └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x0000013B64C736D0>

  File "E:\anda\envs\myenv\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
          └ SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer ...

urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer 
certificate (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "E:\anda\envs\myenv\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x0000013B252220E0>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x0000013B64C736D0>

  File "E:\anda\envs\myenv\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x0000013B2514EF80>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)

  File "E:\anda\envs\myenv\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
          │             │      │    │            └ SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer ...
          │             │      │    └ SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer ...
          │             │      └ '/repos/ultralytics/assets/releases/tags/v8.2.0'
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x0000013B64C736D0>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/ultralytics/assets/releases/tags/v8.2.0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "E:\anda\envs\myenv\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "E:\anda\envs\myenv\Scripts\ma...
           │         └ <code object <module> at 0x0000013B22B17C00, file "E:\anda\envs\myenv\Scripts\magic-pdf.exe\__main__.py", line 1>
           └ <function _run_code at 0x0000013B22B00C10>

  File "E:\anda\envs\myenv\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "E:\anda\envs\myenv\Scripts\ma...
         └ <code object <module> at 0x0000013B22B17C00, file "E:\anda\envs\myenv\Scripts\magic-pdf.exe\__main__.py", line 1>

  File "E:\anda\envs\myenv\Scripts\magic-pdf.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
    │   │    └ <Command cli>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "E:\anda\envs\myenv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x0000013B22F9C160>
           └ <Command cli>

  File "E:\anda\envs\myenv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x0000013B22B68D60>
         │    └ <function Command.invoke at 0x0000013B22F9CC10>
         └ <Command cli>

  File "E:\anda\envs\myenv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'path': 'D://文件//25_jie_guo_san.pdf', 'output_dir': '66', 'method': 
'auto', 'debug_able': False, 'start_page_id': 0, 'end_pa...
         └ <Command cli>

  File "E:\anda\envs\myenv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'path': 'D://文件//25_jie_guo_san.pdf', 'output_dir': '66', 'method': 
'auto', 'debug_able': False, 'start_page_id': 0, 'end_pa...

  File "E:\anda\envs\myenv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'path': 'D://文件//25_jie_guo_san.pdf', 'output_dir': '66', 'method': 
'auto', 'debug_able': False, 'start_page_id': 0, 'end_pa...
  File "E:\anda\envs\myenv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'path': 'D://文件//25_jie_guo_san.pdf', 'output_dir': '66', 'method': 
'auto', 'debug_able': False, 'start_page_id': 0, 'end_pa...
           │   │      │    │           └ <click.core.Context object at 0x0000013B22B68D60>
           │   │      │    └ <function cli at 0x0000013B34F34F70>
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'path': 'D://文件//25_jie_guo_san.pdf', 'output_dir': '66', 'method': 
'auto', 'debug_able': False, 'start_page_id': 0, 'end_pa...
           │   │      │    │           └ <click.core.Context object at 0x0000013B22B68D60>
           │   │      │    └ <function cli at 0x0000013B34F34F70>
           │   │      └ <Command cli>
           │   │      │    │           │   └ {'path': 'D://文件//25_jie_guo_san.pdf', 'output_dir': '66', 'method': 
'auto', 'debug_able': False, 'start_page_id': 0, 'end_pa...
           │   │      │    │           └ <click.core.Context object at 0x0000013B22B68D60>
           │   │      │    └ <function cli at 0x0000013B34F34F70>
           │   │      └ <Command cli>
           │   └ <function Context.invoke at 0x0000013B22F77910>
           │   │      │    │           └ <click.core.Context object at 0x0000013B22B68D60>
           │   │      │    └ <function cli at 0x0000013B34F34F70>
           │   │      └ <Command cli>
           │   └ <function Context.invoke at 0x0000013B22F77910>
           │   │      └ <Command cli>
           │   └ <function Context.invoke at 0x0000013B22F77910>
           └ <click.core.Context object at 0x0000013B22B68D60>
           │   └ <function Context.invoke at 0x0000013B22F77910>
           └ <click.core.Context object at 0x0000013B22B68D60>

           └ <click.core.Context object at 0x0000013B22B68D60>

  File "E:\anda\envs\myenv\lib\site-packages\click\core.py", line 783, in invoke

  File "E:\anda\envs\myenv\lib\site-packages\click\core.py", line 783, in invoke
  File "E:\anda\envs\myenv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
    return __callback(*args, **kwargs)
                       │       └ {'path': 'D://文件//25_jie_guo_san.pdf', 'output_dir': '66', 'method': 'auto', 'deb                       │       └ {'path': 'D://文件//25_jie_guo_san.pdf', 'output_dir': '66', 'method': 'auto', 'debug_able': False, 'start_page_id': 0, 'end_pa...
                       └ ()
ug_able': False, 'start_page_id': 0, 'end_pa...
                       └ ()
                       └ ()

  File "E:\anda\envs\myenv\lib\site-packages\magic_pdf\tools\cli.py", line 102, in cli
    parse_doc(path)
    parse_doc(path)
    │         └ 'D://文件//25_jie_guo_san.pdf'
    └ <function cli.<locals>.parse_doc at 0x0000013B22B63130>

    └ <function cli.<locals>.parse_doc at 0x0000013B22B63130>

> File "E:\anda\envs\myenv\lib\site-packages\magic_pdf\tools\cli.py", line 84, in parse_doc

> File "E:\anda\envs\myenv\lib\site-packages\magic_pdf\tools\cli.py", line 84, in parse_doc
> File "E:\anda\envs\myenv\lib\site-packages\magic_pdf\tools\cli.py", line 84, in parse_doc
    do_parse(
    └ <function do_parse at 0x0000013B34F34700>

  File "E:\anda\envs\myenv\lib\site-packages\magic_pdf\tools\co

### How to reproduce the bug | 如何复现

magic-pdf -p D://文件//25_jie_guo_san.pdf -o 66 -m auto

### Operating system | 操作系统

Windows

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cpu

**Comment by yetao2023** [comment]
你好，请问最后是怎么解决的？

**Comment by plainwater8199** [comment]
unsubscribe



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年8月25日(周一) 晚上10:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [opendatalab/MinerU] 无法使用HTTPSConnectionPool (Issue #605)


yetao2023 left a comment (opendatalab/MinerU#605)
 
你好，请问最后是怎么解决的？
