### ISSUE TITLE
部分PDF解析遇到错误

### ISSUE THREAD

**Issue by Ajax-Yi** [opendatalab/MinerU#611]
### Description of the bug | 错误描述

2024-09-13 10:11:03.130 | ERROR    | magic_pdf.user_api:parse_pdf:91 - 0
Traceback (most recent call last):

  File "/public/home/yidongyi/anaconda3/envs/MinerU/bin/magic-pdf", line 8, in <module>
    sys.exit(cli())
    │   │    └ <Command cli>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/public/home/yidongyi/anaconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x2b7f57a9e950>
           └ <Command cli>
  File "/public/home/yidongyi/anaconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x2b7f577f8580>
         │    └ <function Command.invoke at 0x2b7f57a9f400>
         └ <Command cli>
  File "/public/home/yidongyi/anaconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'path': 'medical_1w_4', 'output_dir': 'medical_1w_4_output', 'method': 'auto', 'debug_able': False, 'start_page_id': 0, 'end...
           │   │      │    │           └ <click.core.Context object at 0x2b7f577f8580>
           │   │      │    └ <function cli at 0x2b7f84f9f7f0>
           │   │      └ <Command cli>
           │   └ <function Context.invoke at 0x2b7f57a9e170>
           └ <click.core.Context object at 0x2b7f577f8580>
  File "/public/home/yidongyi/anaconda3/envs/MinerU/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'path': 'medical_1w_4', 'output_dir': 'medical_1w_4_output', 'method': 'auto', 'debug_able': False, 'start_page_id': 0, 'end...
                       └ ()
  File "/public/home/yidongyi/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/tools/cli.py", line 100, in cli
    parse_doc(doc_path)
    │         └ PosixPath('medical_1w_4/890afe1e2f9e45bb1a0601f6def2761b.pdf')
    └ <function cli.<locals>.parse_doc at 0x2b7f57897490>
  File "/public/home/yidongyi/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/tools/cli.py", line 84, in parse_doc
    do_parse(
    └ <function do_parse at 0x2b7f84f9ef80>
  File "/public/home/yidongyi/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/tools/common.py", line 85, in do_parse
    pipe.pipe_parse()
    │    └ <function UNIPipe.pipe_parse at 0x2b7f84f9f1c0>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x2b7f84fbecb0>
  File "/public/home/yidongyi/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 77, in pipe_parse
    self.pdf_mid_data = parse_union_pdf(self.pdf_bytes, self.model_list, self.image_writer,
    │    │              │               │    │          │    │           │    └ <magic_pdf.rw.DiskReaderWriter.DiskReaderWriter object at 0x2b7f84fbebc0>
    │    │              │               │    │          │    │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x2b7f84fbecb0>
    │    │              │               │    │          │    └ [{'layout_dets': [{'category_id': 2, 'poly': [1407.9771728515625, 104.75070190429688, 1490.17578125, 104.75070190429688, 1490...
    │    │              │               │    │          └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x2b7f84fbecb0>
    │    │              │               │    └ b'%PDF-1.6\r%\xe2\xe3\xcf\xd3\r\n266 0 obj\r<</Linearized 1/L 1342377/O 270/E 150984/N 9/T 1336936/H [ 2356 757]>>\rendobj\r ...
    │    │              │               └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x2b7f84fbecb0>
    │    │              └ <function parse_union_pdf at 0x2b7f84f9e830>
    │    └ None
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x2b7f84fbecb0>
  File "/public/home/yidongyi/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/user_api.py", line 94, in parse_union_pdf
    pdf_info_dict = parse_pdf(parse_pdf_by_txt)
                    │         └ <function parse_pdf_by_txt at 0x2b7f84f9e710>
                    └ <function parse_union_pdf.<locals>.parse_pdf at 0x2b8158adf400>
> File "/public/home/yidongyi/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/user_api.py", line 82, in parse_pdf
    return method(
           └ <function parse_pdf_by_txt at 0x2b7f84f9e710>
  File "/public/home/yidongyi/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pdf_parse_by_txt.py", line 12, in parse_pdf_by_txt
    return pdf_parse_union(pdf_bytes,
           │               └ b'%PDF-1.6\r%\xe2\xe3\xcf\xd3\r\n266 0 obj\r<</Linearized 1/L 1342377/O 270/E 150984/N 9/T 1336936/H [ 2356 757]>>\rendobj\r ...
           └ <function pdf_parse_union at 0x2b7f84f9e680>
  File "/public/home/yidongyi/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/pdf_parse_union_core.py", line 225, in pdf_parse_union
    magic_model = MagicModel(model_list, pdf_docs)
                  │          │           └ Document('', <memory, doc# 2>)
                  │          └ [{'layout_dets': [{'category_id': 2, 'poly': [1407.9771728515625, 104.75070190429688, 1490.17578125, 104.75070190429688, 1490...
                  └ <class 'magic_pdf.model.magic_model.MagicModel'>
  File "/public/home/yidongyi/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/magic_model.py", line 109, in __init__
    self.__fix_footnote()
    └ <magic_pdf.model.magic_model.MagicModel object at 0x2b813edcc640>
  File "/public/home/yidongyi/anaconda3/envs/MinerU/lib/python3.10/site-packages/magic_pdf/model/magic_model.py", line 168, in __fix_footnote
    if dis_table_footnote.get(i, float('inf')) > dis_figure_footnote[i]:
       │                  │   │                  │                   └ 0
       │                  │   │                  └ {}
       │                  │   └ 0
       │                  └ <method 'get' of 'dict' objects>
       └ {0: 7}

KeyError: 0

### How to reproduce the bug | 如何复现

[890afe1e2f9e45bb1a0601f6def2761b.pdf](https://github.com/user-attachments/files/16987900/890afe1e2f9e45bb1a0601f6def2761b.pdf)
PDF文件如上。使用在线版的解析中是正常的。
参数：
"device-mode":"cuda",
    "table-config": {
        "model": "TableMaster",
        "is_table_recog_enable": true,
        "max_time": 400
    }

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
昨天修复了一个bug，请更新0.8.1版本
