### ISSUE TITLE
M3芯片的MacBook pro 依赖已经成功安装，但是app.py启动报错

### ISSUE THREAD

**Issue by pzc163** [opendatalab/MinerU#792]
### Description of the bug | 错误描述

NotImplementedError: The operator 'aten::upsample_bicubic2d.out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/opt/homebrew/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/opt/homebrew/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/opt/homebrew/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/Users/magicyang/Project/MinerU/app.py", line 97, in to_markdown
    local_md_dir, file_name = parse_pdf(file_path, './output', end_pages - 1)
TypeError: cannot unpack non-iterable NoneType object
<img width="1015" alt="image" src="https://github.com/user-attachments/assets/2f85501f-8dcb-47f1-ac39-d6d2888e4e6b">

### How to reproduce the bug | 如何复现

Mac 依赖安装完成后，用python app.py命令启动即可复现

### Operating system | 操作系统

MacOS

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
torch对mps兼容性不佳，请修改magic-pdf.json中devicemode为cpu

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
