### ISSUE TITLE
/repos/ultralytics/assets/releases/tags/v8.3.0

### ISSUE THREAD

**Issue by WangJianQ-0118** [opendatalab/MinerU#803]
### Description of the bug | 错误描述

2024-10-28 17:18:04.253 | ERROR    | magic_pdf.tools.cli:parse_doc:96 - HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/ultralytics/assets/releases/tags/v8.3.0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5b4c5310f0>, 'Connection to api.github.com timed out. (connect timeout=None)'))
Traceback (most recent call last):

  File "/root/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           │          └ <function create_connection at 0x7f5d93770700>
           └ <module 'urllib3.util.connection' from '/root/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/urllib3/util/con...
  File "/root/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
          └ None
  File "/root/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
    │    │       └ ('20.205.243.168', 443)
    │    └ <method 'connect' of '_socket.socket' objects>
    └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/root/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               │    └ <function HTTPConnectionPool._make_request at 0x7f5d933d81f0>
               └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f5b4c530d90>
  File "/root/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
          └ ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5b4c5310f0>, 'Connection to api.github.com timed out. (...
  File "/root/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7f5b4c5310f0>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7f5d933d85e0>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f5b4c530d90>
  File "/root/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7f5d933cc9d0>
    └ <urllib3.connection.HTTPSConnection object at 0x7f5b4c5310f0>
  File "/root/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/urllib3/connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
    │    │             │    └ <function HTTPConnection._new_conn at 0x7f5d933cc0d0>
    │    │             └ <urllib3.connection.HTTPSConnection object at 0x7f5b4c5310f0>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7f5b4c5310f0>
  File "/root/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/urllib3/connection.py", line 208, in _new_conn
    raise ConnectTimeoutError(
          └ <class 'urllib3.exceptions.ConnectTimeoutError'>

urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f5b4c5310f0>, 'Connection to api.github.com timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/root/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7f5d933d83a0>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f5b4c530d90>
  File "/root/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7f5d93772d40>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/root/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
          │             │      │    │            └ ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5b4c5310f0>, 'Connection to api.github.com timed out. (...
          │             │      │    └ ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5b4c5310f0>, 'Connection to api.github.com timed out. (...
          │             │      └ '/repos/ultralytics/assets/releases/tags/v8.3.0'
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f5b4c530d90>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/ultralytics/assets/releases/tags/v8.3.0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5b4c5310f0>, 'Connection to api.github.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

### How to reproduce the bug | 如何复现

1

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cpu

**Comment by myhloli** [comment]
模型没有正确下载并加载，请使用官方的模型下载脚本处理该问题

**Comment by yetao2023** [comment]
你好，请问本地模型是怎么配置的？
