### ISSUE TITLE
undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

### ISSUE THREAD

**Issue by WangJianQ-0118** [opendatalab/MinerU#811]
### Description of the bug | 错误描述

2024-10-29 12:52:25.233 | ERROR    | magic_pdf.tools.cli:parse_doc:96 - /home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
Traceback (most recent call last):

  File "/home/wangjianqiang/miniforge3/envs/pdf/bin/magic-pdf", line 8, in <module>
    sys.exit(cli())
    │   │    └ <Command cli>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f61cd7467a0>
           └ <Command cli>
  File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f61cdb74070>
         │    └ <function Command.invoke at 0x7f61cd747250>
         └ <Command cli>
  File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'path': '/home/wangjianqiang/PDF/test.pdf', 'output_dir': '/root/wangjianqiang/PDF/', 'method': 'auto', 'debug_able': False,...
           │   │      │    │           └ <click.core.Context object at 0x7f61cdb74070>
           │   │      │    └ <function cli at 0x7f607c2b2e60>
           │   │      └ <Command cli>
           │   └ <function Context.invoke at 0x7f61cd745fc0>
           └ <click.core.Context object at 0x7f61cdb74070>
  File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'path': '/home/wangjianqiang/PDF/test.pdf', 'output_dir': '/root/wangjianqiang/PDF/', 'method': 'auto', 'debug_able': False,...
                       └ ()
  File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/magic_pdf/tools/cli.py", line 102, in cli
    parse_doc(path)
    │         └ '/home/wangjianqiang/PDF/test.pdf'
    └ <function cli.<locals>.parse_doc at 0x7f61cd9b6560>
> File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/magic_pdf/tools/cli.py", line 84, in parse_doc
    do_parse(
    └ <function do_parse at 0x7f607c2b25f0>
  File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/magic_pdf/tools/common.py", line 79, in do_parse
    pipe.pipe_analyze()
    │    └ <function UNIPipe.pipe_analyze at 0x7f607c2b27a0>
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f607c89eec0>
  File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/magic_pdf/pipe/UNIPipe.py", line 30, in pipe_analyze
    self.model_list = doc_analyze(self.pdf_bytes, ocr=False,
    │    │            │           │    └ b'%PDF-1.5\n%\xe2\xe3\xcf\xd3\r\n6 0 obj\n22262\nendobj\n5 0 obj\n<</Type/XObject\n/Subtype/Image\n/Width 1240\n/Height 1754\...
    │    │            │           └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f607c89eec0>
    │    │            └ <function doc_analyze at 0x7f61273a7370>
    │    └ []
    └ <magic_pdf.pipe.UNIPipe.UNIPipe object at 0x7f607c89eec0>
  File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 110, in doc_analyze
    custom_model = model_manager.get_model(ocr, show_log)
                   │             │         │    └ False
                   │             │         └ False
                   │             └ <function ModelSingleton.get_model at 0x7f61273a72e0>
                   └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x7f607c2d41c0>
  File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 63, in get_model
    self._models[key] = custom_model_init(ocr=ocr, show_log=show_log)
    │    │       │      │                     │             └ False
    │    │       │      │                     └ False
    │    │       │      └ <function custom_model_init at 0x7f61273a71c0>
    │    │       └ (False, False)
    │    └ {}
    └ <magic_pdf.model.doc_analyze_by_custom_model.ModelSingleton object at 0x7f607c2d41c0>
  File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/magic_pdf/model/doc_analyze_by_custom_model.py", line 83, in custom_model_init
    from magic_pdf.model.pdf_extract_kit import CustomPEKModel
  File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/magic_pdf/model/pdf_extract_kit.py", line 15, in <module>
    import torchtext
  File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/torchtext/__init__.py", line 18, in <module>
    from torchtext import _extension  # noqa: F401
  File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/torchtext/_extension.py", line 64, in <module>
    _init_extension()
    └ <function _init_extension at 0x7f5facbed000>
  File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/torchtext/_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
    └ <function _load_lib at 0x7f5facbecf70>
  File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/torchtext/_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
    │     │   │            └ PosixPath('/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so')
    │     │   └ <function _Ops.load_library at 0x7f5fae2101f0>
    │     └ <module 'torch.ops' from '_ops.py'>
    └ <module 'torch' from '/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/torch/__init__.py'>
  File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/torch/_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
    │      │    └ '/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so'
    │      └ <class 'ctypes.CDLL'>
    └ <module 'ctypes' from '/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/ctypes/__init__.py'>
  File "/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
    │    │         │       │    │      └ 0
    │    │         │       │    └ '/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so'
    │    │         │       └ <CDLL '/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so', handle 0 at 0x7f5...
    │    │         └ <built-in function dlopen>
    │    └ 0
    └ <CDLL '/home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so', handle 0 at 0x7f5...

OSError: /home/wangjianqiang/miniforge3/envs/pdf/lib/python3.10/site-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

### How to reproduce the bug | 如何复现

1

### Operating system | 操作系统

Linux

### Python version | Python 版本

3.10

### Software version | 软件版本 (magic-pdf --version)

0.8.x

### Device mode | 设备模式

cuda

**Comment by myhloli** [comment]
torch和torchtext版本不匹配，需要调整到torch2.3.1+torchtext0.18.0
